project:
  type: book

book:
  title: "Problems and Solutions in Applied Statistics (2nd ed)"
  author: "Ken Butler"
  date: now
  chapters:
    - index.qmd
    - getting_used.qmd
    - reading-in.Rmd
    - data-summaries.Rmd
    - one-sample-inference.Rmd
    - two-sample-inference.Rmd
    - power.Rmd
    - sign.Rmd
    - mood-median.Rmd
    - matched-pairs-sign.Rmd
format:
  html:
    theme: cosmo
    df-print: paged
  pdf:
    documentclass: scrreprt



