project:
  type: book

book:
  title: "Problems and Solutions in Applied Statistics (2nd ed)"
  author: "Ken Butler"
  date: "2023-05-23"
  chapters:
    - index.qmd
    - getting_used.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



