project:
  type: book

book:
  title: "Problems and Solutions in Applied Statistics (2nd ed)"
  author: "Ken Butler"
  date: "2023-05-23"
  chapters:
    - index.qmd
    - getting_used.qmd
    - reading-in.Rmd

format:
  html:
    theme: cosmo
    df-print: paged
  pdf:
    documentclass: scrreprt



