# Logistic regression

```{r 15-logistic-regression-1, eval=F}
library(tidyverse)
```

```{r 15-logistic-regression-2, child="_packages.qmd"}
```


```{r 15-logistic-regression-3, wolfspider,child="_wolfspider_qq.Rmd"}
```

```{r 15-logistic-regression-4, aphids, child="_aphids_qq.Rmd"}
```

```{r 15-logistic-regression-5, doseresponse, child="_doseresponse_qq.Rmd"}
```

```{r 15-logistic-regression-6, parasite, child="_parasite_qq.Rmd"}
```

```{r 15-logistic-regression-7, ethics, child="_ethics_qq.Rmd"}
```

```{r 15-logistic-regression-8, heart,  child="_heart_qq.Rmd"}
```

```{r 15-logistic-regression-9, breastfeed, child="_breastfeed_qq.Rmd"}
```

```{r 15-logistic-regression-10, donner, child="_donner_qq.Rmd"}
```

```{r 15-logistic-regression-11, apache, child="_apache_qq.Rmd"}
```

```{r 15-logistic-regression-12, ha2, child="_ha2_qq.Rmd"}
```

My solutions follow:

```{r 15-logistic-regression-13, wolfspider,child="_wolfspider.Rmd"}
```

```{r 15-logistic-regression-14, aphids, child="_aphids.Rmd"}
```

```{r 15-logistic-regression-15, doseresponse, child="_doseresponse.Rmd"}
```

```{r 15-logistic-regression-16, parasite, child="_parasite.Rmd"}
```

```{r 15-logistic-regression-17, ethics, child="_ethics.Rmd"}
```

```{r 15-logistic-regression-18, heart,  child="_heart.Rmd"}
```

```{r 15-logistic-regression-19, breastfeed, child="_breastfeed.Rmd"}
```

```{r 15-logistic-regression-20, donner, child="_donner.Rmd"}
```

```{r 15-logistic-regression-21, apache, child="_apache.Rmd"}
```

```{r 15-logistic-regression-22, ha2, child="_ha2.Rmd"}
```

