<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Problems and Solutions in Applied Statistics (2nd ed) - 8&nbsp; Mood median test</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./matched-pairs-sign.html" rel="next">
<link href="./sign.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<link href="site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="site_libs/pagedtable-1.1/js/pagedtable.js"></script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./mood-median.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Mood median test</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Problems and Solutions in Applied Statistics (2nd ed)</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./getting_used.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Getting used to R and R Studio</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./reading-in.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Reading in data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-summaries.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data exploration</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./one-sample-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">One-sample inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./two-sample-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Two-sample inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Power and sample size</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sign.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">The sign test</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mood-median.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Mood median test</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./matched-pairs-sign.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Matched pairs t and sign test</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./normal-quantile.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Normal quantile plots</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./analysis-of-variance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Analysis of variance</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./reports.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Writing reports</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./coding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Learning to code</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dandruff.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Treating dandruff</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tidying-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Tidying data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./simple-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Simple regression</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sugar-in-breakfast-cereals" id="toc-sugar-in-breakfast-cereals" class="nav-link active" data-scroll-target="#sugar-in-breakfast-cereals"><span class="header-section-number">8.1</span> Sugar in breakfast cereals</a></li>
  <li><a href="#fear-of-math" id="toc-fear-of-math" class="nav-link" data-scroll-target="#fear-of-math"><span class="header-section-number">8.2</span> Fear of math</a></li>
  <li><a href="#medical-instructions" id="toc-medical-instructions" class="nav-link" data-scroll-target="#medical-instructions"><span class="header-section-number">8.3</span> Medical instructions</a></li>
  <li><a href="#handspans-revisited" id="toc-handspans-revisited" class="nav-link" data-scroll-target="#handspans-revisited"><span class="header-section-number">8.4</span> Handspans revisited</a></li>
  <li><a href="#sugar-in-breakfast-cereals-1" id="toc-sugar-in-breakfast-cereals-1" class="nav-link" data-scroll-target="#sugar-in-breakfast-cereals-1"><span class="header-section-number">8.5</span> Sugar in breakfast cereals</a></li>
  <li><a href="#fear-of-math-1" id="toc-fear-of-math-1" class="nav-link" data-scroll-target="#fear-of-math-1"><span class="header-section-number">8.6</span> Fear of math</a></li>
  <li><a href="#medical-instructions-1" id="toc-medical-instructions-1" class="nav-link" data-scroll-target="#medical-instructions-1"><span class="header-section-number">8.7</span> Medical instructions</a></li>
  <li><a href="#handspans-revisited-1" id="toc-handspans-revisited-1" class="nav-link" data-scroll-target="#handspans-revisited-1"><span class="header-section-number">8.8</span> Handspans revisited</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Mood median test</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.2     ✔ readr     2.1.4
✔ forcats   0.5.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.2     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.1     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(smmr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="sugar-in-breakfast-cereals" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="sugar-in-breakfast-cereals"><span class="header-section-number">8.1</span> Sugar in breakfast cereals</h2>
<p>The data for this question are in <a href="http://ritsokiguess.site/datafiles/cereal-sugar.txt">http://ritsokiguess.site/datafiles/cereal-sugar.txt</a>. The story here is whether breakfast cereals marketed to children have a lot of sugar in them; in particular, whether they have more sugar on average than cereals marketed to adults.</p>
<ol type="a">
<li><p>Read in the data (to R) and display the data set. Do you have a variable that distinguishes the children’s cereals from the adults’ cereals, and another that contains the amount of sugar?</p></li>
<li><p>Calculate the mean sugar content for each group of cereals (the adults’ ones and the children’s ones). Do they look similar or different?</p></li>
<li><p>Make side-by-side boxplots of the sugar contents of the two types of cereal. What do you see that is out of the ordinary?</p></li>
<li><p>Explain briefly why you would not trust a two-sample <span class="math inline">\(t\)</span>-test with these data. (That is, say what the problem is, and why it’s a problem.)</p></li>
<li><p>Run a suitable test to see whether the “typical” amount of sugar differs between adult’s and children’s cereals. Justify the test that you run. (You can use the version of your test that lives in a package, if that is easier for you.) What do you conclude, in the context of the data?</p></li>
</ol>
</section>
<section id="fear-of-math" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="fear-of-math"><span class="header-section-number">8.2</span> Fear of math</h2>
<p>Two new short courses have been proposed for helping students who suffer from severe math phobia. The courses are labelled A and B. Ten students were randomly allocated to one of these two courses, and each student’s score on a math phobia test was recorded after they completed their course. The math phobia test produces whole-number scores between 0 and 10, with a higher score indicating a greater fear of mathematics. The data can be found in <a href="http://ritsokiguess.site/datafiles/mathphobia.txt">link</a>. We start with R for this question.</p>
<ol type="a">
<li><p>Read in the data and check, however you like, that you have 10 observations, 5 from each course.</p></li>
<li><p>Do a two-sample <span class="math inline">\(t\)</span>-test to assess whether there is a difference in mean phobia scores after the students have taken the two courses. What do you conclude? (You have no <a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> reason to suppose that a particular one of the tests will produce a higher mean than the other, so do a two-sided test.)</p></li>
<li><p>Draw boxplots of the math phobia scores for each group (one line of code). What is the most striking thing that you notice?</p></li>
<li><p>Explain briefly why a <span class="math inline">\(t\)</span>-test would not be good for these data. (There are two things that you need to say.)</p></li>
<li><p>Run a suitable test to compare the “typical” scores for the two courses. (You can use the version from a package rather than building your own.) What do you conclude?</p></li>
</ol>
</section>
<section id="medical-instructions" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="medical-instructions"><span class="header-section-number">8.3</span> Medical instructions</h2>
<p>Do people understand medical instructions better at certain times of the day? In a study, students in a grade 12 class are randomly divided into two groups, A and B. All students see a video describing how to use an infant forehead thermometer. The students in Group A see the video at 8:30 am, while the students in Group B see the same video at 3:00 pm (on the same day). The next day, all the students are given a test on the material in the video (graded out of 100). The observed scores are in <a href="http://ritsokiguess.site/datafiles/forehead.txt">link</a> (values separated by spaces).</p>
<ol type="a">
<li><p>Read the data into R and display the (first ten) values.</p></li>
<li><p>Obtain a suitable plot that will enable you to assess the assumptions for a two-sample <span class="math inline">\(t\)</span>-test.</p></li>
<li><p>Why might you have doubts about using a two-sample <span class="math inline">\(t\)</span>-test here?</p></li>
<li><p>Run Mood’s median test as in class (<em>without</em> using <code>smmr</code>). What do you conclude, in the context of the data? What recommendation would you make about the time of day to see the video? (You might get a warning about “chisquared approximation being incorrect”, which you can ignore here.)</p></li>
<li><p>Run Mood’s median test on these data using my <code>smmr</code> package, and verify that you get the same answer.</p></li>
</ol>
</section>
<section id="handspans-revisited" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="handspans-revisited"><span class="header-section-number">8.4</span> Handspans revisited</h2>
<p>Take your right hand, and stretch the fingers out as far as you can. The distance between the tip of your thumb and the tip of your little (pinky) finger is your handspan. The students in a Statistics class at Penn State measured their handspans and also whether they identified as male or female. The data are at <a href="http://ritsokiguess.site/datafiles/handspan.txt">http://ritsokiguess.site/datafiles/handspan.txt</a>, with handspans measured in inches. We want to see whether male students have a larger mean handspan than female students.</p>
<ol type="a">
<li><p>Read in and display (some of) the data.</p></li>
<li><p>Make a suitable (facetted) normal quantile plot of the data. (Bear in mind what is supposed to have a normal distribution.)</p></li>
<li><p>Discuss briefly whether you might prefer to use Mood’s median test to compare the handspans of the male and female students, compared to a two-sample <span class="math inline">\(t\)</span>-test.</p></li>
<li><p>Run Mood’s median test. What do you conclude from the test, in the context of the data?</p></li>
</ol>
<p>My solutions follow:</p>
</section>
<section id="sugar-in-breakfast-cereals-1" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="sugar-in-breakfast-cereals-1"><span class="header-section-number">8.5</span> Sugar in breakfast cereals</h2>
<p>The data for this question are in <a href="http://ritsokiguess.site/datafiles/cereal-sugar.txt">http://ritsokiguess.site/datafiles/cereal-sugar.txt</a>. The story here is whether breakfast cereals marketed to children have a lot of sugar in them; in particular, whether they have more sugar on average than cereals marketed to adults.</p>
<ol type="a">
<li>Read in the data (to R) and display the data set. Do you have a variable that distinguishes the children’s cereals from the adults’ cereals, and another that contains the amount of sugar?</li>
</ol>
<p>Solution</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>my_url<span class="ot">=</span><span class="st">"http://ritsokiguess.site/datafiles/cereal-sugar.txt"</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>cereals<span class="ot">=</span><span class="fu">read_delim</span>(my_url,<span class="st">" "</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 40 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: " "
chr (1): who
dbl (1): sugar

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>cereals</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["who"],"name":[1],"type":["chr"],"align":["left"]},{"label":["sugar"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"children","2":"40.3"},{"1":"children","2":"55.0"},{"1":"children","2":"45.7"},{"1":"children","2":"43.3"},{"1":"children","2":"50.3"},{"1":"children","2":"45.9"},{"1":"children","2":"53.5"},{"1":"children","2":"43.0"},{"1":"children","2":"44.2"},{"1":"children","2":"44.0"},{"1":"children","2":"47.4"},{"1":"children","2":"44.0"},{"1":"children","2":"20.0"},{"1":"children","2":"55.1"},{"1":"children","2":"48.8"},{"1":"children","2":"50.4"},{"1":"children","2":"37.8"},{"1":"children","2":"70.3"},{"1":"children","2":"46.6"},{"1":"adults","2":"20.0"},{"1":"adults","2":"40.2"},{"1":"adults","2":"2.2"},{"1":"adults","2":"7.5"},{"1":"adults","2":"4.4"},{"1":"adults","2":"37.2"},{"1":"adults","2":"16.6"},{"1":"adults","2":"14.5"},{"1":"adults","2":"4.1"},{"1":"adults","2":"15.8"},{"1":"adults","2":"4.1"},{"1":"adults","2":"2.4"},{"1":"adults","2":"3.5"},{"1":"adults","2":"8.5"},{"1":"adults","2":"10.0"},{"1":"adults","2":"1.0"},{"1":"adults","2":"4.4"},{"1":"adults","2":"1.3"},{"1":"adults","2":"8.1"},{"1":"adults","2":"4.7"},{"1":"adults","2":"18.4"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>The variable <code>who</code> is a categorical variable saying who the cereal is intended for, and the variable <code>sugar</code> says how much sugar each cereal has.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" type="a">
<li>Calculate the mean sugar content for each group of cereals (the adults’ ones and the children’s ones). Do they look similar or different?</li>
</ol>
<p>Solution</p>
<p><code>group_by</code> and <code>summarize</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>cereals <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(who) <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summarize</span>(<span class="at">sugar_mean=</span><span class="fu">mean</span>(sugar))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["who"],"name":[1],"type":["chr"],"align":["left"]},{"label":["sugar_mean"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"adults","2":"10.90000"},{"1":"children","2":"46.61053"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>These means look very different, though it would be better to look at a boxplot (coming up in a moment).</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" type="a">
<li>Make side-by-side boxplots of the sugar contents of the two types of cereal. What do you see that is out of the ordinary?</li>
</ol>
<p>Solution</p>
<p>The usual:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(cereals,<span class="fu">aes</span>(<span class="at">x=</span>who,<span class="at">y=</span>sugar))<span class="sc">+</span><span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="mood-median_files/figure-html/cerealsugar-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>I see outliers: two high ones on the adults’ cereals, and one high and one low on the children’s cereals.</p>
<p>My thought above about the means being very different is definitely supported by the medians being very different on the boxplots. We should have no trouble declaring that the “typical” amounts of sugar in the adults’ and children’s cereals are different.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" type="a">
<li>Explain briefly why you would not trust a two-sample <span class="math inline">\(t\)</span>-test with these data. (That is, say what the problem is, and why it’s a problem.)</li>
</ol>
<p>Solution</p>
<p>The problem is the outliers (which is rather a giveaway), but the reason it’s a problem is that the two-sample <span class="math inline">\(t\)</span>-test assumes (approximately) normal data, and a normal distribution doesn’t have outliers. Not only do you need to note the outliers, but you also need to say why the outliers cause a problem <em>in this case</em>. Anything less than that is not a complete answer.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" type="a">
<li>Run a suitable test to see whether the “typical” amount of sugar differs between adult’s and children’s cereals. Justify the test that you run. (You can use the version of your test that lives in a package, if that is easier for you.) What do you conclude, in the context of the data?</li>
</ol>
<p>Solution</p>
<p>Having ruled out the two-sample <span class="math inline">\(t\)</span>-test, we are left with Mood’s median test. I didn’t need you to build it yourself, so you can use package <code>smmr</code> to run it with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(smmr)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">median_test</span>(cereals,sugar,who)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$table
          above
group      above below
  adults       2    19
  children    18     1

$test
       what        value
1 statistic 2.897243e+01
2        df 1.000000e+00
3   P-value 7.341573e-08</code></pre>
</div>
</div>
<p>We conclude that there <em>is</em> a difference between the median amounts of sugar between the two groups of cereals, the P-value of 0.00000007 being extremely small.</p>
<p>Why did it come out so small? Because the amount of sugar was smaller than the overall median for almost all the adult cereals, and larger than the overall median for almost all the children’s ones. That is, the children’s cereals really do have more sugar.</p>
<p>Mood’s median test doesn’t come with a confidence interval (for the difference in population medians), because whether or not a certain difference in medians is rejected depends on what those medians actually are, and the idea of the duality of the test and CI doesn’t carry over as we would like.</p>
<p>My daughter likes chocolate Cheerios, but she also likes Shredded Wheat and <em>Bran Flakes</em>. Go figure. (Her current favourite is Raisin Bran, even though she doesn’t like raisins by themselves.)</p>
<p>Mood’s median test is the test we should trust, but you might be curious about how the <span class="math inline">\(t\)</span>-test stacks up here:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(sugar<span class="sc">~</span>who,<span class="at">data=</span>cereals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  sugar by who
t = -11.002, df = 37.968, p-value = 2.278e-13
alternative hypothesis: true difference in means between group adults and group children is not equal to 0
95 percent confidence interval:
 -42.28180 -29.13925
sample estimates:
  mean in group adults mean in group children 
              10.90000               46.61053 </code></pre>
</div>
</div>
<p>The P-value is <em>even smaller</em>, and we have the advantage of getting a confidence interval for the difference in means: from about 30 to about 40 units less sugar in the adult cereals. Whatever the units were.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</section>
<section id="fear-of-math-1" class="level2" data-number="8.6">
<h2 data-number="8.6" class="anchored" data-anchor-id="fear-of-math-1"><span class="header-section-number">8.6</span> Fear of math</h2>
<p>Two new short courses have been proposed for helping students who suffer from severe math phobia. The courses are labelled A and B. Ten students were randomly allocated to one of these two courses, and each student’s score on a math phobia test was recorded after they completed their course. The math phobia test produces whole-number scores between 0 and 10, with a higher score indicating a greater fear of mathematics. The data can be found in <a href="http://ritsokiguess.site/datafiles/mathphobia.txt">link</a>. We start with R for this question.</p>
<ol type="a">
<li>Read in the data and check, however you like, that you have 10 observations, 5 from each course.</li>
</ol>
<p>Solution</p>
<p>This doesn’t need much comment:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>my_url <span class="ot">&lt;-</span> <span class="st">"http://ritsokiguess.site/datafiles/mathphobia.txt"</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>math <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(my_url, <span class="st">" "</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 10 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: " "
chr (1): course
dbl (1): phobia

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>math</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["course"],"name":[1],"type":["chr"],"align":["left"]},{"label":["phobia"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"a","2":"8"},{"1":"a","2":"7"},{"1":"a","2":"7"},{"1":"a","2":"6"},{"1":"a","2":"6"},{"1":"b","2":"9"},{"1":"b","2":"8"},{"1":"b","2":"7"},{"1":"b","2":"2"},{"1":"b","2":"1"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>This will do, counting the <code>a</code> and <code>b</code>. Or, to save yourself that trouble:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>math <span class="sc">%&gt;%</span> <span class="fu">count</span>(course)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["course"],"name":[1],"type":["chr"],"align":["left"]},{"label":["n"],"name":[2],"type":["int"],"align":["right"]}],"data":[{"1":"a","2":"5"},{"1":"b","2":"5"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>Five each. The story is to get the computer to do the grunt work for you, if you can make it do so. Other ways:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>math <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(course) <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["course"],"name":[1],"type":["chr"],"align":["left"]},{"label":["count"],"name":[2],"type":["int"],"align":["right"]}],"data":[{"1":"a","2":"5"},{"1":"b","2":"5"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>and this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(math, <span class="fu">table</span>(course))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>course
a b 
5 5 </code></pre>
</div>
</div>
<p>giving the same answer. Lots of ways.</p>
<p>Extra: there is an experimental design issue here. You might have noticed that each student did only <em>one</em> of the courses. Couldn’t students do both, in a matched-pairs kind of way? Well, it’s a bit like the kids learning to read in that if the first of the courses reduces a student’s anxiety, the second course won’t appear to do much good (even if it actually would have been helpful had the student done that one first). This is the same idea as the kids learning to read: once you’ve learned to read, you’ve learned to read, and learning to read a second way won’t help much. The place where matched pairs scores is when you can “wipe out” the effect of one treatment before a subject gets the other one. We have an example of kids throwing baseballs and softballs that is like that: if you throw one kind of ball, that won’t affect how far you can throw the other kind.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" type="a">
<li>Do a two-sample <span class="math inline">\(t\)</span>-test to assess whether there is a difference in mean phobia scores after the students have taken the two courses. What do you conclude? (You have no <a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> reason to suppose that a particular one of the tests will produce a higher mean than the other, so do a two-sided test.)</li>
</ol>
<p>Solution</p>
<p>A two-sided test is the default, so there is not much to do here:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(phobia <span class="sc">~</span> course, <span class="at">data =</span> math)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  phobia by course
t = 0.83666, df = 4.4199, p-value = 0.4456
alternative hypothesis: true difference in means between group a and group b is not equal to 0
95 percent confidence interval:
 -3.076889  5.876889
sample estimates:
mean in group a mean in group b 
            6.8             5.4 </code></pre>
</div>
</div>
<p>The P-value of 0.4456 is nowhere near less than 0.05, so there is no evidence at all that the<br>
mean math phobia scores are different between the two courses.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" type="a">
<li>Draw boxplots of the math phobia scores for each group (one line of code). What is the most striking thing that you notice?</li>
</ol>
<p>Solution</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(math, <span class="fu">aes</span>(<span class="at">x =</span> course, <span class="at">y =</span> phobia)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="mood-median_files/figure-html/mathphobia-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Boxplot <code>a</code> is just weird. The bar across the middle is actually at the top, and it has no bottom. (Noting something sensible like this is enough.) Boxplot <code>b</code> is hugely spread out.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<p>By way of explanation: the course <code>a</code> scores have a number of values equal so that the 3rd quartile and the median are the name, and also that the first quartile and the minimum value are the same:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>tmp <span class="ot">&lt;-</span> math <span class="sc">%&gt;%</span> <span class="fu">filter</span>(course <span class="sc">==</span> <span class="st">"a"</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>tmp <span class="sc">%&gt;%</span> <span class="fu">count</span>(phobia)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["phobia"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["n"],"name":[2],"type":["int"],"align":["right"]}],"data":[{"1":"6","2":"2"},{"1":"7","2":"2"},{"1":"8","2":"1"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(tmp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    course              phobia   
 Length:5           Min.   :6.0  
 Class :character   1st Qu.:6.0  
 Mode  :character   Median :7.0  
                    Mean   :6.8  
                    3rd Qu.:7.0  
                    Max.   :8.0  </code></pre>
</div>
</div>
<p>The phobia scores from course A are two 6’s, two 7’s and an 8. The median and third quartile are both 7, and the first quartile is the same as the lowest value, 6.</p>
<p>Technique note: I wanted to do two things with the phobia scores from course A: count up how many of each score, and show you what the five-number summary looks like. One pipe won’t do this (the pipe “branches”), so I saved what I needed to use, before it branched, into a data frame <code>tmp</code> and then used <code>tmp</code> twice. Pipes are powerful, but not <em>all</em>-powerful.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" type="a">
<li>Explain briefly why a <span class="math inline">\(t\)</span>-test would not be good for these data. (There are two things that you need to say.)</li>
</ol>
<p>Solution</p>
<p>The easiest way to structure this is to ask yourself first what the <span class="math inline">\(t\)</span>-test needs, and second whether you have it. The <span class="math inline">\(t\)</span>-test assumes (approximately) normal data. The boxplot for group <code>a</code> doesn’t even look symmetric, and the one for group <code>b</code> has an oddly asymmetric box. So I think the normality is in question here, and therefore another test would be better. (This is perhaps a bit glib of an answer, since there are only 5 values in each group, and so they can certainly look non-normal even if they actually are normal, but these values are all integers, so it is perhaps wise to be cautious.) We have the machinery to assess the normality for these, in one shot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(math, <span class="fu">aes</span>(<span class="at">sample =</span> phobia)) <span class="sc">+</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq</span>() <span class="sc">+</span> <span class="fu">stat_qq_line</span>() <span class="sc">+</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>course, <span class="at">ncol =</span> <span class="dv">1</span>, <span class="at">scales =</span> <span class="st">"free"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="mood-median_files/figure-html/mathphobia-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>I don’t know what <em>you</em> make of those, but they both look pretty straight to me (and there are only five observations, so it’s hard to judge). Course <code>b</code> maybe has a “hole” in it (three large values and two small ones). Maybe. I dunno. What I would <em>really</em> be worried about is outliers, and at least we don’t have those. I mentioned in class that the <span class="math inline">\(t\)</span>-tests are robust to non-normality. I ought to have expanded on that a bit: what really makes the <span class="math inline">\(t\)</span>-test still behave itself with non-normality is when you have <em>large</em> samples, that is, when the Central Limit Theorem has had a chance to take hold. (That’s what drives the normality not really being necessary in most cases.) But, even with small samples, exact normality doesn’t matter so much. Here, we have two tiny samples, and so we have to insist a bit more, but only a bit more, on a more-or-less normal shape in each group. (It’s kind of a double jeopardy in that the situation where normality matters most, namely with small samples, is where it’s the hardest to judge, because samples of size 5 even from a normal distribution can look very non-normal.) But, the biggest threats to the <span class="math inline">\(t\)</span>-test are big-time skewness and outliers, and we are not suffering too badly from those.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" type="a">
<li>Run a suitable test to compare the “typical” scores for the two courses. (You can use the version from a package rather than building your own.) What do you conclude?</li>
</ol>
<p>Solution</p>
<p>This is an invite to use <code>smmr</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(smmr)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">median_test</span>(math, phobia, course)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$table
     above
group above below
    a     1     2
    b     2     2

$test
       what     value
1 statistic 0.1944444
2        df 1.0000000
3   P-value 0.6592430</code></pre>
</div>
</div>
<p>We are nowhere near rejecting equal medians; in fact, both courses are very close to 50–50 above and below the overall median.</p>
<p>If you look at the frequency table, you might be confused by something: there were 10 observations, but there are only <span class="math inline">\(1+2+2+2=7\)</span> in the table. This is because three of the observations were equal to the overall median, and had to be thrown away:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>math <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">med =</span> <span class="fu">median</span>(phobia))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["med"],"name":[1],"type":["dbl"],"align":["right"]}],"data":[{"1":"7"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>math <span class="sc">%&gt;%</span> <span class="fu">count</span>(phobia)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["phobia"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["n"],"name":[2],"type":["int"],"align":["right"]}],"data":[{"1":"1","2":"1"},{"1":"2","2":"1"},{"1":"6","2":"2"},{"1":"7","2":"3"},{"1":"8","2":"2"},{"1":"9","2":"1"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>The overall median was 7. Because the actual data were really discrete (the phobia scores could only be whole numbers), we risked losing a lot of our data when we did this test (and we didn’t have much to begin with). The other thing to say is that with small sample sizes, the frequencies in the table have to be <em>very</em> lopsided for you to have a chance of rejecting the null. Something like this is what you’d need:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">6</span>, <span class="dv">6</span>, <span class="dv">6</span>, <span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">9</span>, <span class="dv">10</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">2</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">tibble</span>(x, g)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="fu">median_test</span>(d, x, g)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$table
     above
group above below
    1     0     3
    2     4     0

$test
       what       value
1 statistic 7.000000000
2        df 1.000000000
3   P-value 0.008150972</code></pre>
</div>
</div>
<p>I faked it up so that we had 10 observations, three of which were equal to the overall median. Of the rest, all the small ones were in group 1 and all the large ones were in group 2. This is lopsided enough to reject with, though, because of the small frequencies, there actually was a warning about “chi-squared approximation may be inaccurate”.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</section>
<section id="medical-instructions-1" class="level2" data-number="8.7">
<h2 data-number="8.7" class="anchored" data-anchor-id="medical-instructions-1"><span class="header-section-number">8.7</span> Medical instructions</h2>
<p>Do people understand medical instructions better at certain times of the day? In a study, students in a grade 12 class are randomly divided into two groups, A and B. All students see a video describing how to use an infant forehead thermometer. The students in Group A see the video at 8:30 am, while the students in Group B see the same video at 3:00 pm (on the same day). The next day, all the students are given a test on the material in the video (graded out of 100). The observed scores are in <a href="http://ritsokiguess.site/datafiles/forehead.txt">link</a> (values separated by spaces).</p>
<ol type="a">
<li>Read the data into R and display the (first ten) values.</li>
</ol>
<p>Solution</p>
<p>Separated by spaces, so <code>read_delim</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>my_url <span class="ot">&lt;-</span> <span class="st">"http://ritsokiguess.site/datafiles/forehead.txt"</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>instr <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(my_url, <span class="st">" "</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 18 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: " "
chr (1): group
dbl (1): score

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>instr</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["group"],"name":[1],"type":["chr"],"align":["left"]},{"label":["score"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"A","2":"88"},{"1":"A","2":"89"},{"1":"A","2":"79"},{"1":"A","2":"100"},{"1":"A","2":"98"},{"1":"A","2":"89"},{"1":"A","2":"65"},{"1":"A","2":"94"},{"1":"A","2":"95"},{"1":"A","2":"91"},{"1":"B","2":"87"},{"1":"B","2":"69"},{"1":"B","2":"78"},{"1":"B","2":"79"},{"1":"B","2":"83"},{"1":"B","2":"90"},{"1":"B","2":"85"},{"1":"B","2":"58"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" type="a">
<li>Obtain a suitable plot that will enable you to assess the assumptions for a two-sample <span class="math inline">\(t\)</span>-test.</li>
</ol>
<p>Solution</p>
<p>We need the values in each group to be approximately normally distributed. Side-by-side boxplots will do it:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(instr, <span class="fu">aes</span>(<span class="at">x =</span> group, <span class="at">y =</span> score)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="mood-median_files/figure-html/forehead-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>or, if you like, separate (facetted) normal quantile plots, which I would do this way:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(instr, <span class="fu">aes</span>(<span class="at">sample =</span> score)) <span class="sc">+</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq</span>() <span class="sc">+</span> <span class="fu">stat_qq_line</span>() <span class="sc">+</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>group, <span class="at">ncol =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="mood-median_files/figure-html/forehead-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" type="a">
<li>Why might you have doubts about using a two-sample <span class="math inline">\(t\)</span>-test here?</li>
</ol>
<p>Solution</p>
<p>We are looking for non-normality in at least one of the groups. Here, both groups have an outlier at the low end that would be expected to pull the mean downward. I don’t think there is left-skewness here, since there is no particular evidence of the high-end values being bunched up: the problem in both cases with normality is at the low end. One way or another, I’m expecting you to have noticed the outliers. Extra: last year, when I first drew the normal quantile plots, there was no <code>stat_qq_line</code>, so you had to imagine where the line went if you did it this way. Without the line, these plots look somewhat curved, which would have pointed to left-skewness, but now we see that the lowest observation is too low, and maybe the second-lowest one as well, while the other observations are just fine.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" type="a">
<li>Run Mood’s median test as in class (<em>without</em> using <code>smmr</code>). What do you conclude, in the context of the data? What recommendation would you make about the time of day to see the video? (You might get a warning about “chisquared approximation being incorrect”, which you can ignore here.)</li>
</ol>
<p>Solution</p>
<p>The overall median first:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>instr <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">med =</span> <span class="fu">median</span>(score))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["med"],"name":[1],"type":["dbl"],"align":["right"]}],"data":[{"1":"87.5"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>87.5, which is not equal to any of the data values (they are all integers). This will avoid any issues with values-equal-to-median later.</p>
<p>Then, create and save a table of the value by group and above/below median. You can count either above or below (it comes out equivalently either way):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>tab <span class="ot">&lt;-</span> <span class="fu">with</span>(instr, <span class="fu">table</span>(group, score <span class="sc">&gt;</span> <span class="fl">87.5</span>))</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>tab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     
group FALSE TRUE
    A     2    8
    B     7    1</code></pre>
</div>
</div>
<p>Then, chi-squared test for independence (the null) or association of some kind (the alternative). The <code>correct=F</code> is saying not to do Yates’s correction, so that it would come out the same if you were doing it by hand (“observed minus expected, squared, divided by expected” and all that stuff).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(tab, <span class="at">correct =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in chisq.test(tab, correct = F): Chi-squared approximation may be
incorrect</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  tab
X-squared = 8.1, df = 1, p-value = 0.004427</code></pre>
</div>
</div>
<p>The P-value is 0.0044, which is (much) smaller than 0.05, and therefore you can reject independence and conclude association: that is, whether a student scores above or below the median depends on which group they are in, or, that the median scores are different for the two groups.</p>
<p>The warning is because the expected frequencies are on the small side (if you have done this kind of problem by hand, you might remember something about “expected frequencies less than 5”. This is that.) Here, the P-value is so small that we can afford to have it be inaccurate by a bit and still not affect the conclusion, so I think we are safe.</p>
<p>As for which group is better, well, the easiest way is to go back to your boxplots and see that the median for group A (8:30 am) is substantially higher than for group B (3:00pm). But you can also see it from your frequency table, if you displayed it:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>tab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     
group FALSE TRUE
    A     2    8
    B     7    1</code></pre>
</div>
</div>
<p>Most of the people in the 8:30 am group scored above the median, and most of the people in the 3:00 pm group scored below the median. So the scores at 8:30 am were better overall.</p>
<p>As I write this, it is just after 3:00 pm and I am about to make myself a pot of tea!</p>
<p>Extra: about that <code>correct=F</code> thing. There was a point of view for a long time that when you are dealing with a <span class="math inline">\(2 \times 2\)</span> table, you can get better P-values by, before squaring “observed minus expected”, taking 0.5 away from the absolute value of the difference. This is called Yates’s correction. It is in the same spirit as the “continuity correction” that you might have encountered in the normal approximation to the binomial, where in the binomial you have to have a whole number of successes, but the normal allows fractional values as well. In about the 1960s, the usefulness of Yates’s correction was shot down, for general contingency tables. There is, however, one case where it <em>is</em> useful, and that is the case where the row totals and column totals are <em>fixed</em>.</p>
<p>What do I mean by that? Well, first let’s look at a case where the totals are <em>not</em> all fixed. Consider a survey in which you want to see whether males and females agree or disagree on some burning issue of the day. You collect random samples of, say, 500 males and 500 females, and you count how many of them say Yes or No to your statement.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> You might get results like this:</p>
<pre><code>
Yes  No  Total
Males    197 303   500
Females  343 157   500
Total    540 460  1000
</code></pre>
<p>In this table, the row totals must be 500, because you asked this many males and this many females, and each one must have answered something. The column totals, however, are not fixed: you didn’t know, ahead of time, that 540 people would answer “yes”. That was just the way the data turned out, and if you did another survey with the same design, you’d probably get a different number of people saying “yes”.</p>
<p>For another example, let’s go back to Fisher (yes, <em>that</em> Fisher). A “lady” of his acquaintance claimed to be able, by drinking a cup of tea with milk and sugar in it, whether the milk or the sugar had been added first. Fisher, or, more likely, his housekeeper, prepared 8 cups of tea, 4 with milk first and 4 with sugar first. The lady knew that four of the cups had milk first, and her job was to say which four. The results might have been like this:</p>
<pre><code>
Actual 
Milk first  sugar first  Total
Lady   Milk first        3            1         4
says   sugar first       1            3         4
Total             4            4         8
</code></pre>
<p>This time, all of the row totals and all of the column totals must be 4, regardless of what the lady thinks. Even if she thinks 5 of the cups of tea actually had milk first, she is going to pick 4 of them to say that they have milk first, since she knows there are only 4. In this case, all of the row and column totals are fixed at 4, and the right analysis is called Fisher’s Exact Test, based on the hypergeometric distribution. In a <span class="math inline">\(2\times 2\)</span> table like this one, there is only one “degree of freedom”, since as soon as you specify one of the frequencies, say the number of cups where the lady said milk first and they actually were milk first, you can work out the others. But, leaving that aside, the usual chi-squared analysis is a perfectly good approximation, especially if the frequencies are large, and especially if you use Yates’s correction.</p>
<p>It is clear that Fisher must have been English, since he was able to get a publication out of drinking tea.</p>
<p>How does that apply to Mood’s median test? Well, let’s remind ourselves of the table we had:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>tab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     
group FALSE TRUE
    A     2    8
    B     7    1</code></pre>
</div>
</div>
<p>We know how many students were in each group: 10 in group A and 8 in B. So the row totals are fixed. What about the columns? These are whether each observation was above or below the overall median. There were 18 observations altogether, so there <em>must</em> be 9 above and 9 below.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> So the column totals are fixed as well. All totals fixed, so we should be using Yates’s correction. I didn’t, because I wanted to keep things simple, but I should have done.</p>
<p>R’s <code>chisq.test</code> by default <em>always</em> uses Yates’s correction, and if you don’t want it, you have to say <code>correct=F</code>. Which is why I have been doing so all through.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" type="a">
<li>Run Mood’s median test on these data using my <code>smmr</code> package, and verify that you get the same answer.</li>
</ol>
<p>Solution</p>
<p>Not much to it, since the data is already read in:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(smmr)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">median_test</span>(instr, score, group)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$table
     above
group above below
    A     8     2
    B     1     7

$test
       what       value
1 statistic 8.100000000
2        df 1.000000000
3   P-value 0.004426526</code></pre>
</div>
</div>
<p>Identical, test statistic, degrees of freedom and P-value. The table of frequencies is also the same, just with columns rearranged. (In <code>smmr</code> I counted the number of values below the overall median, whereas in my build-it-yourself I counted the number of values above.)</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</section>
<section id="handspans-revisited-1" class="level2" data-number="8.8">
<h2 data-number="8.8" class="anchored" data-anchor-id="handspans-revisited-1"><span class="header-section-number">8.8</span> Handspans revisited</h2>
<p>Take your right hand, and stretch the fingers out as far as you can. The distance between the tip of your thumb and the tip of your little (pinky) finger is your handspan. The students in a Statistics class at Penn State measured their handspans and also whether they identified as male or female. The data are at <a href="http://ritsokiguess.site/datafiles/handspan.txt">http://ritsokiguess.site/datafiles/handspan.txt</a>, with handspans measured in inches. We want to see whether male students have a larger mean handspan than female students.</p>
<ol type="a">
<li>Read in and display (some of) the data.</li>
</ol>
<p>Solution</p>
<p>Delimited by a single space, so:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>my_url <span class="ot">&lt;-</span> <span class="st">"http://ritsokiguess.site/datafiles/handspan.txt"</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>span <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(my_url, <span class="st">" "</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 190 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: " "
chr (1): sex
dbl (1): handspan

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>span</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["sex"],"name":[1],"type":["chr"],"align":["left"]},{"label":["handspan"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"M","2":"21.50"},{"1":"M","2":"22.50"},{"1":"M","2":"23.50"},{"1":"F","2":"20.00"},{"1":"F","2":"19.00"},{"1":"F","2":"20.50"},{"1":"F","2":"20.50"},{"1":"F","2":"20.25"},{"1":"M","2":"23.00"},{"1":"M","2":"24.50"},{"1":"M","2":"23.00"},{"1":"F","2":"20.00"},{"1":"M","2":"26.00"},{"1":"M","2":"23.00"},{"1":"F","2":"18.00"},{"1":"M","2":"21.50"},{"1":"F","2":"20.50"},{"1":"M","2":"21.50"},{"1":"F","2":"22.00"},{"1":"M","2":"24.50"},{"1":"F","2":"20.00"},{"1":"F","2":"21.50"},{"1":"M","2":"23.50"},{"1":"F","2":"17.00"},{"1":"F","2":"16.00"},{"1":"M","2":"22.00"},{"1":"F","2":"22.00"},{"1":"F","2":"22.00"},{"1":"F","2":"20.00"},{"1":"M","2":"23.50"},{"1":"M","2":"22.00"},{"1":"M","2":"22.00"},{"1":"M","2":"24.50"},{"1":"F","2":"20.00"},{"1":"F","2":"20.00"},{"1":"F","2":"20.00"},{"1":"F","2":"21.70"},{"1":"F","2":"22.00"},{"1":"F","2":"20.00"},{"1":"F","2":"21.00"},{"1":"F","2":"21.00"},{"1":"F","2":"19.00"},{"1":"F","2":"21.00"},{"1":"F","2":"20.25"},{"1":"F","2":"21.00"},{"1":"F","2":"22.00"},{"1":"F","2":"18.00"},{"1":"F","2":"20.00"},{"1":"M","2":"23.00"},{"1":"M","2":"22.50"},{"1":"M","2":"19.50"},{"1":"M","2":"22.50"},{"1":"M","2":"22.00"},{"1":"M","2":"23.00"},{"1":"M","2":"22.50"},{"1":"M","2":"20.50"},{"1":"M","2":"21.50"},{"1":"M","2":"23.00"},{"1":"M","2":"22.50"},{"1":"M","2":"21.50"},{"1":"M","2":"25.00"},{"1":"F","2":"21.00"},{"1":"F","2":"19.00"},{"1":"F","2":"22.50"},{"1":"F","2":"21.00"},{"1":"F","2":"20.00"},{"1":"F","2":"19.00"},{"1":"F","2":"21.00"},{"1":"F","2":"20.50"},{"1":"F","2":"21.00"},{"1":"F","2":"22.00"},{"1":"F","2":"20.00"},{"1":"F","2":"20.00"},{"1":"F","2":"18.00"},{"1":"F","2":"21.00"},{"1":"F","2":"22.50"},{"1":"F","2":"22.50"},{"1":"M","2":"24.00"},{"1":"M","2":"21.50"},{"1":"M","2":"21.50"},{"1":"M","2":"18.00"},{"1":"M","2":"20.00"},{"1":"M","2":"22.00"},{"1":"M","2":"24.00"},{"1":"M","2":"22.00"},{"1":"M","2":"23.00"},{"1":"M","2":"22.00"},{"1":"M","2":"22.00"},{"1":"M","2":"23.00"},{"1":"M","2":"22.50"},{"1":"M","2":"25.50"},{"1":"M","2":"24.00"},{"1":"F","2":"19.00"},{"1":"F","2":"19.00"},{"1":"F","2":"19.00"},{"1":"F","2":"22.50"},{"1":"F","2":"20.00"},{"1":"F","2":"13.00"},{"1":"F","2":"20.00"},{"1":"F","2":"22.50"},{"1":"F","2":"19.50"},{"1":"F","2":"18.50"},{"1":"F","2":"19.00"},{"1":"F","2":"17.50"},{"1":"F","2":"18.00"},{"1":"F","2":"21.00"},{"1":"F","2":"19.50"},{"1":"F","2":"20.00"},{"1":"F","2":"19.00"},{"1":"F","2":"21.50"},{"1":"F","2":"18.00"},{"1":"F","2":"19.00"},{"1":"F","2":"19.50"},{"1":"F","2":"20.00"},{"1":"F","2":"22.50"},{"1":"M","2":"23.50"},{"1":"M","2":"21.00"},{"1":"M","2":"25.50"},{"1":"M","2":"23.00"},{"1":"M","2":"22.50"},{"1":"M","2":"24.00"},{"1":"M","2":"21.50"},{"1":"M","2":"22.00"},{"1":"M","2":"22.50"},{"1":"M","2":"23.00"},{"1":"M","2":"18.50"},{"1":"M","2":"21.00"},{"1":"M","2":"24.00"},{"1":"M","2":"23.50"},{"1":"M","2":"24.50"},{"1":"M","2":"23.00"},{"1":"M","2":"22.00"},{"1":"M","2":"23.00"},{"1":"M","2":"23.00"},{"1":"M","2":"24.00"},{"1":"M","2":"24.50"},{"1":"F","2":"21.00"},{"1":"F","2":"18.00"},{"1":"F","2":"22.00"},{"1":"F","2":"18.50"},{"1":"F","2":"19.00"},{"1":"F","2":"22.00"},{"1":"F","2":"12.50"},{"1":"F","2":"18.00"},{"1":"F","2":"20.50"},{"1":"F","2":"19.00"},{"1":"F","2":"20.00"},{"1":"F","2":"21.00"},{"1":"F","2":"19.00"},{"1":"F","2":"19.00"},{"1":"F","2":"21.00"},{"1":"F","2":"18.50"},{"1":"F","2":"19.00"},{"1":"F","2":"21.50"},{"1":"F","2":"21.50"},{"1":"F","2":"23.00"},{"1":"F","2":"23.25"},{"1":"F","2":"20.00"},{"1":"F","2":"18.80"},{"1":"F","2":"21.00"},{"1":"F","2":"17.00"},{"1":"F","2":"21.00"},{"1":"F","2":"20.00"},{"1":"F","2":"20.50"},{"1":"F","2":"20.00"},{"1":"F","2":"19.50"},{"1":"F","2":"21.00"},{"1":"F","2":"21.00"},{"1":"F","2":"20.00"},{"1":"M","2":"20.50"},{"1":"M","2":"24.00"},{"1":"M","2":"22.00"},{"1":"M","2":"23.00"},{"1":"M","2":"21.00"},{"1":"M","2":"22.50"},{"1":"M","2":"21.50"},{"1":"M","2":"24.50"},{"1":"M","2":"22.00"},{"1":"M","2":"22.00"},{"1":"M","2":"21.00"},{"1":"M","2":"23.00"},{"1":"M","2":"22.50"},{"1":"M","2":"24.00"},{"1":"M","2":"22.50"},{"1":"M","2":"23.00"},{"1":"M","2":"23.00"},{"1":"M","2":"23.00"},{"1":"M","2":"21.50"},{"1":"M","2":"19.00"},{"1":"M","2":"21.50"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" type="a">
<li>Make a suitable (facetted) normal quantile plot of the data. (Bear in mind what is supposed to have a normal distribution.)</li>
</ol>
<p>Solution</p>
<p>Here, we need <em>each</em> group to be approximately normal, so make normal quantile plots of handspan, facetted by sex:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(span, <span class="fu">aes</span>(<span class="at">sample=</span>handspan)) <span class="sc">+</span> <span class="fu">stat_qq</span>() <span class="sc">+</span> <span class="fu">stat_qq_line</span>() <span class="sc">+</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">facet_wrap</span>(<span class="sc">~</span>sex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="mood-median_files/figure-html/handspan2-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" type="a">
<li>Discuss briefly whether you might prefer to use Mood’s median test to compare the handspans of the male and female students, compared to a two-sample <span class="math inline">\(t\)</span>-test.</li>
</ol>
<p>Solution</p>
<p>A two-sample <span class="math inline">\(t\)</span>-test assumes that each of the two samples comes from a (approximately) normal distribution (“the data are normal” is not precise enough). The female values, on the left, definitely have some outliers at the low end (or a long lower tail), so these are definitely not normal. The male values (on the right) are slightly skewed to the left, or there are some mild outliers at the low end, or, if you prefer, these are approximately normal. (You need discussion of each of the males and females, or of why looking at one group is enough.) Because the males are not close enough to normal (or, because neither group is close enough to normal), we would prefer to use Mood’s median test. (Say this.) You do yourself a favour by making it clear that you know that <em>both</em> groups have to be normal enough; if one is good but the other is not, that is not enough.</p>
<p>The other relevant issue is sample size. The best answer discusses that as well, even though you have a lot to think about already. This data set has 190 observations in it, so the samples must be pretty big:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>span <span class="sc">%&gt;%</span> <span class="fu">count</span>(sex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["sex"],"name":[1],"type":["chr"],"align":["left"]},{"label":["n"],"name":[2],"type":["int"],"align":["right"]}],"data":[{"1":"F","2":"103"},{"1":"M","2":"87"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>With these sample sizes, we can expect a lot of help from the central limit theorem. The apparent outliers in the males won’t be a problem, and maybe we could even get away with those outliers in the females.</p>
<p>Extra: you could also think about bootstrapped sampling distributions of the sample mean here. The one we are most concerned about is the females; if it turns out that they are all right, then the males must be all right too, since the plot for them is showing less non-normality (or, without the double negative, is closer to being normal). So let’s do the females:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>span <span class="sc">%&gt;%</span> </span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sex <span class="sc">==</span> <span class="st">"F"</span>) <span class="ot">-&gt;</span> females </span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(<span class="at">sim =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">my_sample =</span> <span class="fu">list</span>(<span class="fu">sample</span>(females<span class="sc">$</span>handspan, <span class="at">replace =</span> <span class="cn">TRUE</span>))) <span class="sc">%&gt;%</span> </span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">my_mean =</span> <span class="fu">mean</span>(my_sample)) <span class="sc">%&gt;%</span> </span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">sample =</span> my_mean)) <span class="sc">+</span> <span class="fu">stat_qq</span>() <span class="sc">+</span> <span class="fu">stat_qq_line</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="mood-median_files/figure-html/handspan2-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>My take is that the sampling distribution of the sample mean for the females is normal enough, therefore the one for the males is also normal enough, therefore the two-sample <span class="math inline">\(t\)</span>-test is actually fine.</p>
<p>The reason that this one is close to normal is different from the other one, though. In the other question, we had milder non-normality but a smaller sample; in this one, the data distribution is less normal, but we had a much larger sample size to compensate.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" type="a">
<li>Run Mood’s median test. What do you conclude from the test, in the context of the data?</li>
</ol>
<p>Solution</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(smmr)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">median_test</span>(span, handspan, sex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$table
     above
group above below
    F    17    82
    M    65    11

$test
       what       value
1 statistic 8.06725e+01
2        df 1.00000e+00
3   P-value 2.66404e-19</code></pre>
</div>
</div>
<p>The P-value of <span class="math inline">\(2.66 \times 10^{-19}\)</span> is extremely small, so we can conclude that males and females have different median handspans. Remember that we are now comparing medians, and that this test is <em>two</em>-sided.</p>
<p>You can stop here, or you can go on and note that most of the males have a handspan bigger than the median, and most of the females have a handspan smaller than the median, so that males have on average a larger handspan. But you have to make the case that males have a larger handspan; you cannot just assert this from the P-value.</p>
<p>A more formal way to do this is to make the same observation as above, then note that this is “on the correct side” (for males to have a larger handspan), and thus that you can halve the P-value, and conclude that males’ handspans are indeed larger in terms of median.</p>
<p>Extra: you are probably expecting a confidence interval now for the difference in medians. I haven’t talked about that in lecture, because the ideas are a bit trickier than they were for the confidence interval for the sign test. The sign test could be used for testing any median, so we could try a bunch of medians and see whether each one was rejected or not. The problem with Mood’s median test is that it only tests that the medians are <em>the same</em>. If you could easily test that the difference in medians was 3, say, you would know whether 3 was inside or outside the confidence interval for the difference in medians.</p>
<p>What were the actual sample medians, anyway?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>span <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(sex) <span class="sc">%&gt;%</span> </span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summarize</span>(<span class="at">med =</span> <span class="fu">median</span>(handspan))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["sex"],"name":[1],"type":["chr"],"align":["left"]},{"label":["med"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"F","2":"20.0"},{"1":"M","2":"22.5"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>Here’s an idea: if we shift all the female handspans up by 2.5 inches, the medians would be the same:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>span <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">x =</span> <span class="fu">ifelse</span>(sex<span class="sc">==</span><span class="st">"F"</span>, handspan<span class="fl">+2.5</span>, handspan)) <span class="ot">-&gt;</span> d</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>d</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["sex"],"name":[1],"type":["chr"],"align":["left"]},{"label":["handspan"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["x"],"name":[3],"type":["dbl"],"align":["right"]}],"data":[{"1":"M","2":"21.50","3":"21.50"},{"1":"M","2":"22.50","3":"22.50"},{"1":"M","2":"23.50","3":"23.50"},{"1":"F","2":"20.00","3":"22.50"},{"1":"F","2":"19.00","3":"21.50"},{"1":"F","2":"20.50","3":"23.00"},{"1":"F","2":"20.50","3":"23.00"},{"1":"F","2":"20.25","3":"22.75"},{"1":"M","2":"23.00","3":"23.00"},{"1":"M","2":"24.50","3":"24.50"},{"1":"M","2":"23.00","3":"23.00"},{"1":"F","2":"20.00","3":"22.50"},{"1":"M","2":"26.00","3":"26.00"},{"1":"M","2":"23.00","3":"23.00"},{"1":"F","2":"18.00","3":"20.50"},{"1":"M","2":"21.50","3":"21.50"},{"1":"F","2":"20.50","3":"23.00"},{"1":"M","2":"21.50","3":"21.50"},{"1":"F","2":"22.00","3":"24.50"},{"1":"M","2":"24.50","3":"24.50"},{"1":"F","2":"20.00","3":"22.50"},{"1":"F","2":"21.50","3":"24.00"},{"1":"M","2":"23.50","3":"23.50"},{"1":"F","2":"17.00","3":"19.50"},{"1":"F","2":"16.00","3":"18.50"},{"1":"M","2":"22.00","3":"22.00"},{"1":"F","2":"22.00","3":"24.50"},{"1":"F","2":"22.00","3":"24.50"},{"1":"F","2":"20.00","3":"22.50"},{"1":"M","2":"23.50","3":"23.50"},{"1":"M","2":"22.00","3":"22.00"},{"1":"M","2":"22.00","3":"22.00"},{"1":"M","2":"24.50","3":"24.50"},{"1":"F","2":"20.00","3":"22.50"},{"1":"F","2":"20.00","3":"22.50"},{"1":"F","2":"20.00","3":"22.50"},{"1":"F","2":"21.70","3":"24.20"},{"1":"F","2":"22.00","3":"24.50"},{"1":"F","2":"20.00","3":"22.50"},{"1":"F","2":"21.00","3":"23.50"},{"1":"F","2":"21.00","3":"23.50"},{"1":"F","2":"19.00","3":"21.50"},{"1":"F","2":"21.00","3":"23.50"},{"1":"F","2":"20.25","3":"22.75"},{"1":"F","2":"21.00","3":"23.50"},{"1":"F","2":"22.00","3":"24.50"},{"1":"F","2":"18.00","3":"20.50"},{"1":"F","2":"20.00","3":"22.50"},{"1":"M","2":"23.00","3":"23.00"},{"1":"M","2":"22.50","3":"22.50"},{"1":"M","2":"19.50","3":"19.50"},{"1":"M","2":"22.50","3":"22.50"},{"1":"M","2":"22.00","3":"22.00"},{"1":"M","2":"23.00","3":"23.00"},{"1":"M","2":"22.50","3":"22.50"},{"1":"M","2":"20.50","3":"20.50"},{"1":"M","2":"21.50","3":"21.50"},{"1":"M","2":"23.00","3":"23.00"},{"1":"M","2":"22.50","3":"22.50"},{"1":"M","2":"21.50","3":"21.50"},{"1":"M","2":"25.00","3":"25.00"},{"1":"F","2":"21.00","3":"23.50"},{"1":"F","2":"19.00","3":"21.50"},{"1":"F","2":"22.50","3":"25.00"},{"1":"F","2":"21.00","3":"23.50"},{"1":"F","2":"20.00","3":"22.50"},{"1":"F","2":"19.00","3":"21.50"},{"1":"F","2":"21.00","3":"23.50"},{"1":"F","2":"20.50","3":"23.00"},{"1":"F","2":"21.00","3":"23.50"},{"1":"F","2":"22.00","3":"24.50"},{"1":"F","2":"20.00","3":"22.50"},{"1":"F","2":"20.00","3":"22.50"},{"1":"F","2":"18.00","3":"20.50"},{"1":"F","2":"21.00","3":"23.50"},{"1":"F","2":"22.50","3":"25.00"},{"1":"F","2":"22.50","3":"25.00"},{"1":"M","2":"24.00","3":"24.00"},{"1":"M","2":"21.50","3":"21.50"},{"1":"M","2":"21.50","3":"21.50"},{"1":"M","2":"18.00","3":"18.00"},{"1":"M","2":"20.00","3":"20.00"},{"1":"M","2":"22.00","3":"22.00"},{"1":"M","2":"24.00","3":"24.00"},{"1":"M","2":"22.00","3":"22.00"},{"1":"M","2":"23.00","3":"23.00"},{"1":"M","2":"22.00","3":"22.00"},{"1":"M","2":"22.00","3":"22.00"},{"1":"M","2":"23.00","3":"23.00"},{"1":"M","2":"22.50","3":"22.50"},{"1":"M","2":"25.50","3":"25.50"},{"1":"M","2":"24.00","3":"24.00"},{"1":"F","2":"19.00","3":"21.50"},{"1":"F","2":"19.00","3":"21.50"},{"1":"F","2":"19.00","3":"21.50"},{"1":"F","2":"22.50","3":"25.00"},{"1":"F","2":"20.00","3":"22.50"},{"1":"F","2":"13.00","3":"15.50"},{"1":"F","2":"20.00","3":"22.50"},{"1":"F","2":"22.50","3":"25.00"},{"1":"F","2":"19.50","3":"22.00"},{"1":"F","2":"18.50","3":"21.00"},{"1":"F","2":"19.00","3":"21.50"},{"1":"F","2":"17.50","3":"20.00"},{"1":"F","2":"18.00","3":"20.50"},{"1":"F","2":"21.00","3":"23.50"},{"1":"F","2":"19.50","3":"22.00"},{"1":"F","2":"20.00","3":"22.50"},{"1":"F","2":"19.00","3":"21.50"},{"1":"F","2":"21.50","3":"24.00"},{"1":"F","2":"18.00","3":"20.50"},{"1":"F","2":"19.00","3":"21.50"},{"1":"F","2":"19.50","3":"22.00"},{"1":"F","2":"20.00","3":"22.50"},{"1":"F","2":"22.50","3":"25.00"},{"1":"M","2":"23.50","3":"23.50"},{"1":"M","2":"21.00","3":"21.00"},{"1":"M","2":"25.50","3":"25.50"},{"1":"M","2":"23.00","3":"23.00"},{"1":"M","2":"22.50","3":"22.50"},{"1":"M","2":"24.00","3":"24.00"},{"1":"M","2":"21.50","3":"21.50"},{"1":"M","2":"22.00","3":"22.00"},{"1":"M","2":"22.50","3":"22.50"},{"1":"M","2":"23.00","3":"23.00"},{"1":"M","2":"18.50","3":"18.50"},{"1":"M","2":"21.00","3":"21.00"},{"1":"M","2":"24.00","3":"24.00"},{"1":"M","2":"23.50","3":"23.50"},{"1":"M","2":"24.50","3":"24.50"},{"1":"M","2":"23.00","3":"23.00"},{"1":"M","2":"22.00","3":"22.00"},{"1":"M","2":"23.00","3":"23.00"},{"1":"M","2":"23.00","3":"23.00"},{"1":"M","2":"24.00","3":"24.00"},{"1":"M","2":"24.50","3":"24.50"},{"1":"F","2":"21.00","3":"23.50"},{"1":"F","2":"18.00","3":"20.50"},{"1":"F","2":"22.00","3":"24.50"},{"1":"F","2":"18.50","3":"21.00"},{"1":"F","2":"19.00","3":"21.50"},{"1":"F","2":"22.00","3":"24.50"},{"1":"F","2":"12.50","3":"15.00"},{"1":"F","2":"18.00","3":"20.50"},{"1":"F","2":"20.50","3":"23.00"},{"1":"F","2":"19.00","3":"21.50"},{"1":"F","2":"20.00","3":"22.50"},{"1":"F","2":"21.00","3":"23.50"},{"1":"F","2":"19.00","3":"21.50"},{"1":"F","2":"19.00","3":"21.50"},{"1":"F","2":"21.00","3":"23.50"},{"1":"F","2":"18.50","3":"21.00"},{"1":"F","2":"19.00","3":"21.50"},{"1":"F","2":"21.50","3":"24.00"},{"1":"F","2":"21.50","3":"24.00"},{"1":"F","2":"23.00","3":"25.50"},{"1":"F","2":"23.25","3":"25.75"},{"1":"F","2":"20.00","3":"22.50"},{"1":"F","2":"18.80","3":"21.30"},{"1":"F","2":"21.00","3":"23.50"},{"1":"F","2":"17.00","3":"19.50"},{"1":"F","2":"21.00","3":"23.50"},{"1":"F","2":"20.00","3":"22.50"},{"1":"F","2":"20.50","3":"23.00"},{"1":"F","2":"20.00","3":"22.50"},{"1":"F","2":"19.50","3":"22.00"},{"1":"F","2":"21.00","3":"23.50"},{"1":"F","2":"21.00","3":"23.50"},{"1":"F","2":"20.00","3":"22.50"},{"1":"M","2":"20.50","3":"20.50"},{"1":"M","2":"24.00","3":"24.00"},{"1":"M","2":"22.00","3":"22.00"},{"1":"M","2":"23.00","3":"23.00"},{"1":"M","2":"21.00","3":"21.00"},{"1":"M","2":"22.50","3":"22.50"},{"1":"M","2":"21.50","3":"21.50"},{"1":"M","2":"24.50","3":"24.50"},{"1":"M","2":"22.00","3":"22.00"},{"1":"M","2":"22.00","3":"22.00"},{"1":"M","2":"21.00","3":"21.00"},{"1":"M","2":"23.00","3":"23.00"},{"1":"M","2":"22.50","3":"22.50"},{"1":"M","2":"24.00","3":"24.00"},{"1":"M","2":"22.50","3":"22.50"},{"1":"M","2":"23.00","3":"23.00"},{"1":"M","2":"23.00","3":"23.00"},{"1":"M","2":"23.00","3":"23.00"},{"1":"M","2":"21.50","3":"21.50"},{"1":"M","2":"19.00","3":"19.00"},{"1":"M","2":"21.50","3":"21.50"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>Dataframe <code>d</code> has a new column <code>x</code> that is the handspan plus 2.5 inches for females, and the unchanged handspan for males. So the median of <code>x</code> should be the same for males and females:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>d <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(sex) <span class="sc">%&gt;%</span> </span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summarize</span>(<span class="at">med_x =</span> <span class="fu">median</span>(x))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["sex"],"name":[1],"type":["chr"],"align":["left"]},{"label":["med_x"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"F","2":"22.5"},{"1":"M","2":"22.5"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>and also the medians of <code>x</code> cannot possibly be significantly different:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median_test</span>(d, x, sex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$table
     above
group above below
    F    46    36
    M    41    35

$test
       what      value
1 statistic 0.07369901
2        df 1.00000000
3   P-value 0.78602526</code></pre>
</div>
</div>
<p>Quite a lot of the values of <code>x</code> are exactly equal to the overall median (and are discarded), so the P-value is not exactly 1 as you would expect. But it is definitely not significant, and so a difference of 2.5 inches smaller for females is going to be in a confidence interval for the difference in medians.</p>
<p>The strategy now is to try shifting the female handspans by different amounts, run Mood’s median test for each one, and see which shifts are not rejected. These are the ones for which that difference in medians would be in the confidence interval. Before we get to that, though, I want to simplify the procedure we have, so that it is easier to run it lots of times. First, let’s get just the P-value out of the median test:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>d<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">median_test</span>(d, x, sex)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>d<span class="fl">.1</span> <span class="sc">%&gt;%</span> <span class="fu">pluck</span>(<span class="st">"test"</span>, <span class="st">"value"</span>, <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7860253</code></pre>
</div>
</div>
<p>That’s the P-value. <code>pluck</code> pulls individual things out of bigger things. The variable I called <code>d.1</code> has two things in it. The one called <code>table</code> has the numbers of data values above and below the overall median; the one called <code>test</code> has the test statistic and P-value in it. <code>test</code> is a dataframe; inside <em>that</em> is a column called <code>what</code> and a column called <code>value</code> with the number we want in it, and we want the third thing in that (the other two are the chi-squared test statistic and its degrees of freedom). Hence the <code>pluck</code> statement got the right thing.</p>
<p>Let’s think strategy: we want to shift the female handspans by a bunch of different amounts, run the test on each one, and get the P-value each time. When you’re running a big for-each like this, you want the thing you do each time to be as simple as possible. So let’s write a function that takes the shift as input, works out the new <code>x</code>, runs the test, and returns the P-value. We have all the ingredients, so it’s a matter of putting them together:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>shift_pval <span class="ot">&lt;-</span> <span class="cf">function</span>(shift) {</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>  span <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">x =</span> <span class="fu">ifelse</span>(sex <span class="sc">==</span> <span class="st">"F"</span>, handspan <span class="sc">+</span> shift, handspan)) <span class="ot">-&gt;</span> d</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>  d<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">median_test</span>(d, x, sex)</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>  d<span class="fl">.1</span> <span class="sc">%&gt;%</span> <span class="fu">pluck</span>(<span class="st">"test"</span>, <span class="st">"value"</span>, <span class="dv">3</span>)</span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In the function, the <code>shift</code> is input. The first line computes the handspans shifted by the input amount, whatever it is; the second line runs the median test on the shifted data; the last line pulls out, and returns, the P-value.</p>
<p>I am being a little sloppy here (but R is letting me get away with it): the function is also using a dataframe called <code>span</code>, which is the one we read in from the file earlier. That <em>was not input to the function</em>, so, if you have experience with other programming languages, you might be wondering whether that is “in the scope” of inside the function: that is, whether R will know about it. R does; anything the function needs that is not part of the input, it will take from your workspace. This is, you might imagine, dangerous; if the input to your function is called, say, <code>x</code>, you might easily have an <code>x</code> lying around in your workspace from some other analysis that has nothing to do with the <code>x</code> you want as the input to your function. The safe way to do it, and what I should have done, is to have <code>span</code> be input to my function as well. However, that clutters up the discussion below, so we’ll leave things as I did them here.</p>
<p>Let’s test this on a shift of 2.5 inches, and on the original data (a shift of zero):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shift_pval</span>(<span class="fl">2.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7860253</code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shift_pval</span>(<span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.66404e-19</code></pre>
</div>
</div>
<p>Those are the same P-values we got before, so good.</p>
<p>Now, let’s get a bunch of shifts, say from 0 to 5 in steps of 0.5:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(<span class="at">shift =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">5</span>, <span class="fl">0.5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["shift"],"name":[1],"type":["dbl"],"align":["right"]}],"data":[{"1":"0.0"},{"1":"0.5"},{"1":"1.0"},{"1":"1.5"},{"1":"2.0"},{"1":"2.5"},{"1":"3.0"},{"1":"3.5"},{"1":"4.0"},{"1":"4.5"},{"1":"5.0"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>work out the P-value for each one, rowwise:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(<span class="at">shift =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">5</span>, <span class="fl">0.5</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">p_value =</span> <span class="fu">shift_pval</span>(shift))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["shift"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["p_value"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"0.0","2":"2.664040e-19"},{"1":"0.5","2":"7.383053e-15"},{"1":"1.0","2":"6.407439e-09"},{"1":"1.5","2":"5.463857e-05"},{"1":"2.0","2":"5.288111e-02"},{"1":"2.5","2":"7.860253e-01"},{"1":"3.0","2":"5.152925e-03"},{"1":"3.5","2":"1.127859e-05"},{"1":"4.0","2":"1.885053e-09"},{"1":"4.5","2":"1.841319e-14"},{"1":"5.0","2":"1.609545e-18"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>and finally decide whether each shift is inside or outside the CI (because I am too lazy to figure out the scientific notation):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(<span class="at">shift =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">5</span>, <span class="fl">0.5</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">p_value =</span> <span class="fu">shift_pval</span>(shift)) <span class="sc">%&gt;%</span> </span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">where =</span> <span class="fu">ifelse</span>(p_value<span class="sc">&lt;</span><span class="fl">0.05</span>, <span class="st">"outside"</span>, <span class="st">"inside"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["shift"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["p_value"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["where"],"name":[3],"type":["chr"],"align":["left"]}],"data":[{"1":"0.0","2":"2.664040e-19","3":"outside"},{"1":"0.5","2":"7.383053e-15","3":"outside"},{"1":"1.0","2":"6.407439e-09","3":"outside"},{"1":"1.5","2":"5.463857e-05","3":"outside"},{"1":"2.0","2":"5.288111e-02","3":"inside"},{"1":"2.5","2":"7.860253e-01","3":"inside"},{"1":"3.0","2":"5.152925e-03","3":"outside"},{"1":"3.5","2":"1.127859e-05","3":"outside"},{"1":"4.0","2":"1.885053e-09","3":"outside"},{"1":"4.5","2":"1.841319e-14","3":"outside"},{"1":"5.0","2":"1.609545e-18","3":"outside"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>The confidence interval goes from 2 inches to 2.5 inches on this scale. I checked and it goes up to 3 really, except that 3 itself is outside the interval. So let’s call it 2 to 3 inches. This means that the median female handspan is between 2 and 3 inches <em>smaller</em> than the median male handspan, because we had to shift the female handspans up by that much to make them not significantly different.</p>
<p>You, of course, would do just the last pipeline; I showed you the steps so you could see what was going on.</p>
<p>The final observation is that this interval is a long way from containing zero, because the P-value was so tiny.</p>
<p>Let’s see how the <span class="math inline">\(t\)</span>-interval looks in comparison (two-sided, because we want the confidence interval):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(handspan<span class="sc">~</span>sex, <span class="at">data =</span> span)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  handspan by sex
t = -10.871, df = 187.92, p-value &lt; 2.2e-16
alternative hypothesis: true difference in means between group F and group M is not equal to 0
95 percent confidence interval:
 -3.001496 -2.079466
sample estimates:
mean in group F mean in group M 
       20.01699        22.55747 </code></pre>
</div>
</div>
<p>Almost exactly the same (except that F is before M). So it made no difference at all whether we did a <span class="math inline">\(t\)</span>-test or a Mood’s median test, as the bootstrapped sampling distribution suggested.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>That is, before looking at the data. This is Latin. It’s also the place that the Bayesian “prior distribution” comes from. The “posterior distribution” comes from the Latin <em>a posteriori</em>, which means <em>afterwards</em>, that is, after you have looked at the data.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>That is, before looking at the data. This is Latin. It’s also the place that the Bayesian “prior distribution” comes from. The “posterior distribution” comes from the Latin <em>a posteriori</em>, which means <em>afterwards</em>, that is, after you have looked at the data.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>The two groups have very different spreads, but that is not a problem as long as we remember to do the Welch-Satterthwaite test that does not assume equal spreads. This is the default in R, so we are good, at least with that.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>There <em>was</em>, in the <code>chisq.test</code> inside <code>median_test</code>, but in <code>smmr</code> I didn’t pass that warning back to the outside world.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>To simplify things, we’ll assume that everyone gave a Yes or a No answer, though you could add a column like “No answer” if you wanted to make it more realistic.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Except in the case of the previous problem, where there were multiple observations equal to the overall median. Which we ignore for the moment.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./sign.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">The sign test</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./matched-pairs-sign.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Matched pairs t and sign test</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>