<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Problems and Solutions in Applied Statistics (2nd ed) - 6&nbsp; One-sample inference</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./two-sample-inference.html" rel="next">
<link href="./working-with-dataframes.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<link href="site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="site_libs/pagedtable-1.1/js/pagedtable.js"></script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./one-sample-inference.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">One-sample inference</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Problems and Solutions in Applied Statistics (2nd ed)</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./getting_used.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Getting used to R and R Studio</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./reading-in.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Reading in data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./making-graphs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Drawing graphs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-summaries.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data exploration</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./working-with-dataframes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Working with dataframes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./one-sample-inference.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">One-sample inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./two-sample-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Two-sample inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Power and sample size</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sign.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">The sign test</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mood-median.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Mood median test</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./matched-pairs-sign.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Matched pairs t and sign test</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./normal-quantile.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Normal quantile plots</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./analysis-of-variance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Analysis of variance</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./reports.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Writing reports</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./coding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Learning to code</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dandruff.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Treating dandruff</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tidying-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Tidying data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./simple-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Simple regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multiple-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Multiple regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression-categorical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Regression with categorical variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dates-and-times.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Dates and times</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Functions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./vector-matrix.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Vector and matrix algebra</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bootstrap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">The Bootstrap</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stan.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Bayesian Statistics with Stan</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression-revisited.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Regression revisited</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistic-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Logistic regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ordinal-response.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Logistic regression with ordinal response</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nominal-response.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Logistic regression with nominal response</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./survival-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Survival analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anova-revisited.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Analysis of variance revisited</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ancova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Analysis of covariance</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./manova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Multivariate analysis of variance</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./repeated-measures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Repeated measures</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./discriminant-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Discriminant analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cluster.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Hierarchical cluster analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./kmeans-cluster.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">K-means cluster analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./maps.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Drawing maps with Leaflet</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mds.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Multidimensional Scaling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Principal Components</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./fa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Factor Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./loglin.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Frequency table analysis</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#hunter-gatherers-in-australia" id="toc-hunter-gatherers-in-australia" class="nav-link active" data-scroll-target="#hunter-gatherers-in-australia"><span class="header-section-number">6.1</span> Hunter-gatherers in Australia</a></li>
  <li><a href="#buses-to-boulder" id="toc-buses-to-boulder" class="nav-link" data-scroll-target="#buses-to-boulder"><span class="header-section-number">6.2</span> Buses to Boulder</a></li>
  <li><a href="#length-of-gestation-in-north-carolina" id="toc-length-of-gestation-in-north-carolina" class="nav-link" data-scroll-target="#length-of-gestation-in-north-carolina"><span class="header-section-number">6.3</span> Length of gestation in North Carolina</a></li>
  <li><a href="#inferring-ice-break-up-in-nenana" id="toc-inferring-ice-break-up-in-nenana" class="nav-link" data-scroll-target="#inferring-ice-break-up-in-nenana"><span class="header-section-number">6.4</span> Inferring ice break-up in Nenana</a></li>
  <li><a href="#diameters-of-trees" id="toc-diameters-of-trees" class="nav-link" data-scroll-target="#diameters-of-trees"><span class="header-section-number">6.5</span> Diameters of trees</a></li>
  <li><a href="#one-sample-cholesterol" id="toc-one-sample-cholesterol" class="nav-link" data-scroll-target="#one-sample-cholesterol"><span class="header-section-number">6.6</span> One-sample cholesterol</a></li>
  <li><a href="#hunter-gatherers-in-australia-1" id="toc-hunter-gatherers-in-australia-1" class="nav-link" data-scroll-target="#hunter-gatherers-in-australia-1"><span class="header-section-number">6.7</span> Hunter-gatherers in Australia</a></li>
  <li><a href="#buses-to-boulder-1" id="toc-buses-to-boulder-1" class="nav-link" data-scroll-target="#buses-to-boulder-1"><span class="header-section-number">6.8</span> Buses to Boulder</a></li>
  <li><a href="#length-of-gestation-in-north-carolina-1" id="toc-length-of-gestation-in-north-carolina-1" class="nav-link" data-scroll-target="#length-of-gestation-in-north-carolina-1"><span class="header-section-number">6.9</span> Length of gestation in North Carolina</a></li>
  <li><a href="#inferring-ice-break-up-in-nenana-1" id="toc-inferring-ice-break-up-in-nenana-1" class="nav-link" data-scroll-target="#inferring-ice-break-up-in-nenana-1"><span class="header-section-number">6.10</span> Inferring ice break-up in Nenana</a></li>
  <li><a href="#diameters-of-trees-1" id="toc-diameters-of-trees-1" class="nav-link" data-scroll-target="#diameters-of-trees-1"><span class="header-section-number">6.11</span> Diameters of trees</a></li>
  <li><a href="#one-sample-cholesterol-1" id="toc-one-sample-cholesterol-1" class="nav-link" data-scroll-target="#one-sample-cholesterol-1"><span class="header-section-number">6.12</span> One-sample cholesterol</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">One-sample inference</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="hunter-gatherers-in-australia" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="hunter-gatherers-in-australia"><span class="header-section-number">6.1</span> Hunter-gatherers in Australia</h2>
<p>A hunter-gatherer society is one where people get their food by hunting, fishing or foraging rather than by agriculture or by raising animals. Such societies tend to move from place to place. Anthropologists have studied hunter-gatherer societies in forest ecosystems across the world. The average population density of these societies is 7.38 people per 100 km<span class="math inline">\(^2\)</span>. Hunter-gatherer societies on different continents might have different population densities, possibly because of large-scale ecological constraints (such as resource availability), or because of other factors, possibly social and/or historic, determining population density.</p>
<p>Some hunter-gatherer societies in Australia were studied, and the population density per 100 km<span class="math inline">\(^2\)</span> recorded for each. The data are in <a href="http://ritsokiguess.site/datafiles/hg.txt">http://ritsokiguess.site/datafiles/hg.txt</a>.</p>
<ol type="a">
<li><p>Read the data into R. Do you have the correct variables? How many hunter-gatherer societies in Australia were studied? Explain briefly.</p></li>
<li><p>The question of interest is whether these Australian hunter-gatherer societies are like the rest of the world in terms of mean population density. State suitable null and alternative hypotheses. <em>Define any symbols you use</em>: that is, if you use a symbol, you also have to say what it means.</p></li>
<li><p>Test your hypotheses using a suitable test. What do you conclude, in the context of the data?</p></li>
<li><p>Do you have any doubts about the validity of your test? Explain briefly, using a suitable graph to support your explanation.</p></li>
</ol>
</section>
<section id="buses-to-boulder" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="buses-to-boulder"><span class="header-section-number">6.2</span> Buses to Boulder</h2>
<p>A bus line operates a route from Denver to Boulder (these places are in Colorado). The schedule says that the journey time should be 60 minutes. 11 randomly chosen journey times were recorded, and these are in the file <a href="http://ritsokiguess.site/datafiles/buses.txt">link</a>, with journey times shown in minutes.</p>
<ol type="a">
<li><p>Read the data into R, and display the data frame that you read in.</p></li>
<li><p>Run a suitable test to see whether there is evidence that the mean journey time differs from 60 minutes. What do you conclude? (I want a conclusion that says something about journey times of buses.)</p></li>
<li><p>Give a 95% confidence interval for the mean journey time. (No R code is needed here.)</p></li>
<li><p>Do you draw consistent conclusions from your test and confidence interval? Explain briefly.</p></li>
<li><p>Draw a boxplot of the journey times. Do you see a reason to doubt the test that you did above?</p></li>
</ol>
</section>
<section id="length-of-gestation-in-north-carolina" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="length-of-gestation-in-north-carolina"><span class="header-section-number">6.3</span> Length of gestation in North Carolina</h2>
<p>The data in file <a href="http://ritsokiguess.site/datafiles/ncbirths2.csv">link</a> are about 500 randomly chosen births of babies in North Carolina. There is a lot of information: not just the weight at birth of the baby, but whether the baby was born prematurely, the ages of the parents, whether the parents are married, how long (in weeks) the pregnancy lasted (this is called the “gestation”) and so on. We have seen these data before.</p>
<ol type="a">
<li><p>Read in the data from the file into R, bearing in mind what type of file it is.</p></li>
<li><p>Find a 95% confidence interval for the mean birth weight of all babies born in North Carolina (of which these babies are a sample). At the end, you should state what the confidence interval is. Giving some output is necessary, but <em>not</em> enough by itself.</p></li>
<li><p>Birth weights of babies born in the United States have a mean of 7.3 pounds. Is there any evidence that babies born in North Carolina are less heavy on average? State appropriate hypotheses, do your test, obtain a P-value and state your conclusion, in terms of the original data.</p></li>
<li><p>The theory behind the <span class="math inline">\(t\)</span>-test says that the distribution of birth weights should be (approximately) normally distributed. Obtain a histogram of the birth weights. Does it look approximately normal? Comment briefly. (You’ll have to pick a number of bins for your histogram first. I don’t mind very much what you pick, as long as it’s not obviously too many or too few bins.)</p></li>
</ol>
</section>
<section id="inferring-ice-break-up-in-nenana" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="inferring-ice-break-up-in-nenana"><span class="header-section-number">6.4</span> Inferring ice break-up in Nenana</h2>
<p>Nenana, Alaska, is about 50 miles west of Fairbanks. Every spring, there is a contest in Nenana. A wooden tripod is placed on the frozen river, and people try to guess the exact minute when the ice melts enough for the tripod to fall through the ice. The contest started in 1917 as an amusement for railway workers, and has taken place every year since. Now, hundreds of thousands of people enter their guesses on the Internet and the prize for the winner can be as much as $300,000.</p>
<p>Because so much money is at stake, and because the exact same tripod is placed at the exact same spot on the ice every year, the data are consistent and accurate. The data are in <a href="http://ritsokiguess.site/datafiles/nenana.txt">link</a>.</p>
<p>Yes, we saw these data before.</p>
<ol type="a">
<li><p>Read the data into R, as before, or use the data frame that you read in before. Note that the values are separated by <em>tabs</em> rather than spaces, so you’ll need an appropriate <code>read_</code> to read it in.</p></li>
<li><p>Obtain a 90% confidence interval for the mean <code>JulianDate</code>. What interval do you get? Looking back at your histogram, do you have any doubts about the validity of what you have just done?</p></li>
<li><p>An old-timer in Nenana strokes his grey beard and says “When I were young, I remember the tripod used to fall into the water around May 10”. In a non-leap year, May 10 is Julian day 130. Test the null hypothesis that the mean <code>JulianDay</code> is 130, against the alternative that it is less. What do you conclude? What practical implication does that have (assuming that the old-timer has a good memory)?</p></li>
<li><p>Plot <code>JulianDate</code> against <code>Year</code> on a scatterplot. What recent trends, if any, do you see? Comment briefly. (You did this before, but I have some extra comments on the graph this time, so feel free to just read this part.)</p></li>
</ol>
</section>
<section id="diameters-of-trees" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="diameters-of-trees"><span class="header-section-number">6.5</span> Diameters of trees</h2>
<p>The Wade Tract in Thomas County, Georgia, is an old-growth forest of longleaf pine trees. It has survived in a relatively undisturbed state since before settlements of the area by Europeans. For each tree in the tract, researchers measured the diameter at breast height. This is a standard measure in forestry: it is defined as the diameter of the tree at 4.5 feet above the ground.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> They are interested in the mean diameter at breast height of the trees in this tract. These values are in <a href="http://ritsokiguess.site/datafiles/treediameter.csv">http://ritsokiguess.site/datafiles/treediameter.csv</a>. The diameters are measured in centimetres. The easiest way to get the URL is to <em>right</em>-click on the blue text and select Copy URL. (If you copy and paste the actual text you might end up with extra spaces, especially if the printed URL goes over two lines.)</p>
<ol type="a">
<li><p>Read in and display (some of) the data.</p></li>
<li><p>Make a suitable plot of your dataframe.</p></li>
<li><p>Obtain a 95% confidence interval for the mean diameter.</p></li>
<li><p>Based on what you have seen so far, would you expect to reject a null hypothesis that the population mean diameter (of all longleaf pines like these) is 35 cm? Explain briefly. Then, carry out the test (against a two-sided alternative) and explain briefly whether you were right.</p></li>
<li><p>Would you expect 35 cm to be in a <em>99%</em> confidence interval for the mean diameter? Explain briefly, and then see if you were right.</p></li>
</ol>
</section>
<section id="one-sample-cholesterol" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="one-sample-cholesterol"><span class="header-section-number">6.6</span> One-sample cholesterol</h2>
<p>The data set <a href="http://ritsokiguess.site/datafiles/cholest.csv">here</a> contains cholesterol measurements for heart attack patients (at several different times) as well as for a group of control patients. We will focus on the control patients in this question.</p>
<ol type="a">
<li><p>Read in and display (some of) the data.</p></li>
<li><p>Make a suitable plot of the cholesterol levels of the control patients, and comment briefly on the shape of the distribution.</p></li>
<li><p>It is recommended that people in good health, such as the Control patients here, keep their cholesterol level below 200. Is there evidence that the mean cholesterol level of the population of people of which the Control patients are a sample is less than 200? Show that you understand the process, and state your conclusion in the context of the data.</p></li>
<li><p>What values could the population mean cholesterol level take? You might need to get some more output to determine this.</p></li>
<li><p>Explain briefly why you would be reasonably happy to trust the <span class="math inline">\(t\)</span> procedures in this question. (There are two points you need to make.)</p></li>
</ol>
<p>My solutions follow:</p>
</section>
<section id="hunter-gatherers-in-australia-1" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="hunter-gatherers-in-australia-1"><span class="header-section-number">6.7</span> Hunter-gatherers in Australia</h2>
<p>A hunter-gatherer society is one where people get their food by hunting, fishing or foraging rather than by agriculture or by raising animals. Such societies tend to move from place to place. Anthropologists have studied hunter-gatherer societies in forest ecosystems across the world. The average population density of these societies is 7.38 people per 100 km<span class="math inline">\(^2\)</span>. Hunter-gatherer societies on different continents might have different population densities, possibly because of large-scale ecological constraints (such as resource availability), or because of other factors, possibly social and/or historic, determining population density.</p>
<p>Some hunter-gatherer societies in Australia were studied, and the population density per 100 km<span class="math inline">\(^2\)</span> recorded for each. The data are in <a href="http://ritsokiguess.site/datafiles/hg.txt">http://ritsokiguess.site/datafiles/hg.txt</a>.</p>
<ol type="a">
<li>Read the data into R. Do you have the correct variables? How many hunter-gatherer societies in Australia were studied? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>The data values are separated by (single) spaces, so <code>read_delim</code> is the thing:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>url<span class="ot">=</span><span class="st">"http://ritsokiguess.site/datafiles/hg.txt"</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>societies<span class="ot">=</span><span class="fu">read_delim</span>(url,<span class="st">" "</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 13 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: " "
chr (1): name
dbl (1): density

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<p>I like to put the URL in a variable first, because if I don’t, the <code>read_delim</code> line can be rather long. But if you want to do it in one step, that’s fine, as long as it’s clear that you are doing the right thing.</p>
<p>Let’s look at the data frame:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>societies</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["name"],"name":[1],"type":["chr"],"align":["left"]},{"label":["density"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"jeidji","2":"17.00"},{"1":"kuku","2":"50.00"},{"1":"mamu","2":"45.00"},{"1":"ngatjan","2":"59.80"},{"1":"undanbi","2":"21.74"},{"1":"jinibarra","2":"16.00"},{"1":"ualaria","2":"9.00"},{"1":"barkindji","2":"15.43"},{"1":"wongaibon","2":"5.12"},{"1":"jaralde","2":"40.00"},{"1":"tjapwurong","2":"35.00"},{"1":"tasmanians","2":"13.35"},{"1":"badjalang","2":"13.40"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>I have the name of each society and its population density, as promised (so that is correct). There were 13 societies that were studied. For me, they were all displayed. For you, you’ll probably see only the first ten, and you’ll have to click Next to see the last three.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" type="a">
<li>The question of interest is whether these Australian hunter-gatherer societies are like the rest of the world in terms of mean population density. State suitable null and alternative hypotheses. <em>Define any symbols you use</em>: that is, if you use a symbol, you also have to say what it means.</li>
</ol>
<p>Solution</p>
<p>The mean for the world as a whole (“average”, as stated earlier) is 7.38. Let <span class="math inline">\(\mu\)</span> denote the population mean for Australia (of which these societies are a sample). Then our hypotheses are: <span class="math display">\[ H_0: \mu=7.38\]</span> and <span class="math display">\[ H_a: \mu \ne 7.38.\]</span> There is no reason for a one-sided alternative here, since all we are interested in is whether Australia is different from the rest of the world. <em>Expect to lose a point</em> if you use the symbol <span class="math inline">\(\mu\)</span> without saying what it means.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" type="a">
<li>Test your hypotheses using a suitable test. What do you conclude, in the context of the data?</li>
</ol>
<p>Solution</p>
<p>A <span class="math inline">\(t\)</span>-test, since we are testing a mean:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(societies<span class="sc">$</span>density,<span class="at">mu=</span><span class="fl">7.38</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  societies$density
t = 3.8627, df = 12, p-value = 0.002257
alternative hypothesis: true mean is not equal to 7.38
95 percent confidence interval:
 15.59244 36.84449
sample estimates:
mean of x 
 26.21846 </code></pre>
</div>
</div>
<p>The P-value is 0.0023, less than the usual <span class="math inline">\(\alpha\)</span> of 0.05, so we <em>reject</em> the null hypothesis and conclude that the mean population density is not equal to 7.38. That is to say, Australia is different from the rest of the world in this sense.</p>
<p>As you know, “reject the null hypothesis” is only part of the answer, so gets only part of the marks.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" type="a">
<li>Do you have any doubts about the validity of your test? Explain briefly, using a suitable graph to support your explanation.</li>
</ol>
<p>Solution</p>
<p>The assumption behind the <span class="math inline">\(t\)</span>-test is that the data are approximately normal. We can assess that in several ways, but the simplest (which is perfectly acceptable at this point) is a histogram. You’ll need to pick a suitable number of bins. This one comes from Sturges’ rule:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(societies,<span class="fu">aes</span>(<span class="at">x=</span>density))<span class="sc">+</span><span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="one-sample-inference_files/figure-html/schnagg-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Your conclusion might depend on how many bins you chose for your histogram. Here’s 8 bins (which is really too many with only 13 observations, but it actually shows the shape well):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(societies,<span class="fu">aes</span>(<span class="at">x=</span>density))<span class="sc">+</span><span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="one-sample-inference_files/figure-html/fuos-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>or you can get a number of bins from one of the built-in functions, such as:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>mybins<span class="ot">=</span><span class="fu">nclass.FD</span>(societies<span class="sc">$</span>density)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>mybins</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
</div>
<p>This one is small. The interquartile range is large and <span class="math inline">\(n\)</span> is small, so the binwidth will be large and therefore the number of bins will be small.</p>
<p>Other choices: a one-group boxplot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(societies,<span class="fu">aes</span>(<span class="at">x=</span><span class="dv">1</span>,<span class="at">y=</span>density))<span class="sc">+</span><span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="one-sample-inference_files/figure-html/hotz-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This isn’t the best for assessing normality as such, but it will tell you about lack of symmetry and outliers, which are the most important threats to the <span class="math inline">\(t\)</span>-test, so it’s fine here. Or, a normal quantile plot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(societies,<span class="fu">aes</span>(<span class="at">sample=</span>density))<span class="sc">+</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stat_qq</span>()<span class="sc">+</span><span class="fu">stat_qq_line</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="one-sample-inference_files/figure-html/narten-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This is actually the best way to assess normality, but I’m not expecting you to use this plot here, because we may not have gotten to it in class yet. (If you have read ahead and successfully use the plot, it’s fine.)</p>
<p>After you have drawn your chosen plot (you need <em>one</em> plot), you need to say something about normality and thus whether you have any doubts about the validity of your <span class="math inline">\(t\)</span>-test. This will depend on the graph you drew: if you think your graph is symmetric and outlier-free, you should have no doubts about your <span class="math inline">\(t\)</span>-test; if you think it has something wrong with it, you should say what it is and express your doubts. My guess is that you will think this distribution is skewed to the right. Most of my plots are saying that.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<p>On the website where I got these data, they were using the data as an example for another test, precisely <em>because</em> they thought the distribution was right-skewed. Later on, we’ll learn about the sign test for the median, which I think is actually a better test here.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</section>
<section id="buses-to-boulder-1" class="level2" data-number="6.8">
<h2 data-number="6.8" class="anchored" data-anchor-id="buses-to-boulder-1"><span class="header-section-number">6.8</span> Buses to Boulder</h2>
<p>A bus line operates a route from Denver to Boulder (these places are in Colorado). The schedule says that the journey time should be 60 minutes. 11 randomly chosen journey times were recorded, and these are in the file <a href="http://ritsokiguess.site/datafiles/buses.txt">link</a>, with journey times shown in minutes.</p>
<ol type="a">
<li>Read the data into R, and display the data frame that you read in.</li>
</ol>
<p>Solution</p>
<p>Since you can read the data directly from the URL, do that (if you are online) rather than having to copy and paste and save, and then find the file you saved. Also, there is only one column, so you can pretend that there were multiple columns, separated by whatever you like. It’s least typing to pretend that they were separated by commas like a <code>.csv</code> file:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>my_url <span class="ot">&lt;-</span> <span class="st">"http://ritsokiguess.site/datafiles/buses.txt"</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>journey.times <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(my_url)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 11 Columns: 1
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (1): minutes

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>journey.times</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["minutes"],"name":[1],"type":["dbl"],"align":["right"]}],"data":[{"1":"58"},{"1":"61"},{"1":"69"},{"1":"62"},{"1":"81"},{"1":"54"},{"1":"72"},{"1":"71"},{"1":"53"},{"1":"54"},{"1":"66"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>Using <code>read_delim</code> with any delimiter (such as <code>" "</code>) will also work, and is thus also good.</p>
<p>Variable names in R can have a dot (or an underscore, but not a space) in them. I have grown accustomed to using dots to separate words. This works in R but not other languages, but is seen by some as old-fashioned, with underscores being the modern way.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> You can also use what is called “camel case” by starting each “word” after the first with an uppercase letter like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>journeyTimes <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(my_url)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You have to get the capitalization and punctuation right when you use your variables, no matter what they’re called. In any of the cases above, there is no variable called <code>journeytimes</code>. As Jenny Bryan (in <a href="http://www.stat.ubc.ca/~jenny/STAT545A/block01_basicsWorkspaceWorkingDirProject.html">link</a>) puts it, boldface in original: Implicit contract with the computer / scripting language: Computer will do tedious computation for you. In return, you will be completely precise in your instructions. Typos matter. Case matters. <strong>Get better at typing.</strong></p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" type="a">
<li>Run a suitable test to see whether there is evidence that the mean journey time differs from 60 minutes. What do you conclude? (I want a conclusion that says something about journey times of buses.)</li>
</ol>
<p>Solution</p>
<p><code>t.test</code> doesn’t take a <code>data=</code> to say which data frame to use. Wrap it in a <code>with</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(journey.times, <span class="fu">t.test</span>(minutes, <span class="at">mu =</span> <span class="dv">60</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  minutes
t = 1.382, df = 10, p-value = 0.1971
alternative hypothesis: true mean is not equal to 60
95 percent confidence interval:
 57.71775 69.73680
sample estimates:
mean of x 
 63.72727 </code></pre>
</div>
</div>
<p>We are testing that the mean journey time is 60 minutes, against the two-sided alternative (default) that the mean is not equal to 60 minutes. The P-value, 0.1971, is a lot bigger than the usual <span class="math inline">\(\alpha\)</span> of 0.05, so we cannot reject the null hypothesis. That is, there is no evidence that the mean journey time differs from 60 minutes.</p>
<p>As you remember, we have not proved that the mean journey time <em>is</em> 60 minutes, which is what “accepting the null hypothesis” would be. We have only failed to reject it, in a shoulder-shrugging kind of way: “the mean journey time <em>could</em> be 60 minutes”. The other acceptable word is “retain”; when you say “we retain the null hypothesis”, you imply something like “we act as if the mean is 60 minutes, at least until we find something better.”</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" type="a">
<li>Give a 95% confidence interval for the mean journey time. (No R code is needed here.)</li>
</ol>
<p>Solution</p>
<p>Just read it off from the output: 57.72 to 69.74 minutes.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" type="a">
<li>Do you draw consistent conclusions from your test and confidence interval? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>The test said that we should not reject a mean of 60 minutes. The confidence interval says that 60 minutes is inside the interval of plausible values for the population mean, which is another way of saying the same thing. (If we had rejected 60 as a mean, 60 would have been <em>outside</em> the confidence interval.)</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" type="a">
<li>Draw a boxplot of the journey times. Do you see a reason to doubt the test that you did above?</li>
</ol>
<p>Solution</p>
<p>The grouping variable is a “nothing” as in the Ken and Thomas question (part (d)):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(journey.times, <span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">1</span>, <span class="at">y =</span> minutes)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="one-sample-inference_files/figure-html/brixham-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The assumption behind the <span class="math inline">\(t\)</span>-test is that the population from which the data come has a normal distribution: ie.&nbsp;symmetric with no outliers. A small sample (here we have 11 values) even from a normal distribution might look quite non-normal (as in Assignment 0 from last week), so I am not hugely concerned by this boxplot. However, it’s perfectly all right to say that this distribution is skewed, and therefore we should doubt the <span class="math inline">\(t\)</span>-test, because the upper whisker is longer than the lower one. In fact, the topmost value is very nearly an outlier:<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(journey.times, <span class="fu">aes</span>(<span class="at">x =</span> minutes)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="one-sample-inference_files/figure-html/babbacombe-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>and there might be skewness as well, so maybe I should have been concerned.</p>
<p>I would be looking for some intelligent comment on the boxplot: what it looks like vs.&nbsp;what it ought to look like. I don’t so much mind what that comment is, as long as it’s intelligent enough.</p>
<p>Perhaps I should draw a normal quantile plot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(journey.times, <span class="fu">aes</span>(<span class="at">sample =</span> minutes)) <span class="sc">+</span> <span class="fu">stat_qq</span>() <span class="sc">+</span> <span class="fu">stat_qq_line</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="one-sample-inference_files/figure-html/boulder-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The normal quantile plot is saying that the problem is actually at the <em>bottom</em> of the distribution: the lowest value is not low enough, but the highest value is actually <em>not</em> too high. So this one seems to be on the edge between OK and being right-skewed (too bunched up at the bottom). My take is that with this small sample this is not too bad. But you are free to disagree.</p>
<p>If you don’t like the normality, you’d use a <em>sign test</em> and test that the <em>median</em> is not 60 minutes, which you would (at my guess) utterly fail to reject:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(smmr)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sign_test</span>(journey.times, minutes, <span class="dv">60</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$above_below
below above 
    4     7 

$p_values
  alternative   p_value
1       lower 0.8867187
2       upper 0.2744141
3   two-sided 0.5488281</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ci_median</span>(journey.times, minutes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 54.00195 71.99023</code></pre>
</div>
</div>
<p>and so we do. The median could easily be 60 minutes.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</section>
<section id="length-of-gestation-in-north-carolina-1" class="level2" data-number="6.9">
<h2 data-number="6.9" class="anchored" data-anchor-id="length-of-gestation-in-north-carolina-1"><span class="header-section-number">6.9</span> Length of gestation in North Carolina</h2>
<p>The data in file <a href="http://ritsokiguess.site/datafiles/ncbirths.csv">link</a> are about 500 randomly chosen births of babies in North Carolina. There is a lot of information: not just the weight at birth of the baby, but whether the baby was born prematurely, the ages of the parents, whether the parents are married, how long (in weeks) the pregnancy lasted (this is called the “gestation”) and so on. We have seen these data before.</p>
<ol type="a">
<li>Read in the data from the file into R, bearing in mind what type of file it is.</li>
</ol>
<p>Solution</p>
<p>This is a <code>.csv</code> file (it came from a spreadsheet), so it needs reading in accordingly. Work directly from the URL (rather than downloading the file):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>myurl <span class="ot">&lt;-</span> <span class="st">"http://ritsokiguess.site/datafiles/ncbirths2.csv"</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>bw <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(myurl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 500 Columns: 10
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (10): father_age, mother_age, weeks_gestation, pre_natal_visits, marital...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" type="a">
<li>Find a 95% confidence interval for the mean birth weight of all babies born in North Carolina (of which these babies are a sample). At the end, you should state what the confidence interval is. Giving some output is necessary, but <em>not</em> enough by itself.</li>
</ol>
<p>Solution</p>
<p>This:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(bw<span class="sc">$</span>weight_pounds)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  bw$weight_pounds
t = 104.94, df = 499, p-value &lt; 2.2e-16
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 6.936407 7.201093
sample estimates:
mean of x 
  7.06875 </code></pre>
</div>
</div>
<p>or (the same, but remember to match your brackets):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(bw, <span class="fu">t.test</span>(weight_pounds))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  weight_pounds
t = 104.94, df = 499, p-value &lt; 2.2e-16
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 6.936407 7.201093
sample estimates:
mean of x 
  7.06875 </code></pre>
</div>
</div>
<p>The confidence interval goes from 6.94 to 7.20 pounds.</p>
<p>There is an annoyance about <code>t.test</code>. Sometimes you can use <code>data=</code> with it, and sometimes not. When we do a two-sample <span class="math inline">\(t\)</span>-test later, there is a “model formula” with a squiggle in it, and there we can use <code>data=</code>, but here not, so you have to use the dollar sign or the <code>with</code> to say which data frame to get things from. The distinction seems to be that <em>if you are using a model formula</em>, you can use <code>data=</code>, and if not, not.</p>
<p>This is one of those things that is a consequence of R’s history. The original <code>t.test</code> was without the model formula and thus without the <code>data=</code>, but the model formula got “retro-fitted” to it later. Since the model formula comes from things like regression, where <code>data=</code> is legit, that had to be retro-fitted as well. Or, at least, that’s my understanding.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" type="a">
<li>Birth weights of babies born in the United States have a mean of 7.3 pounds. Is there any evidence that babies born in North Carolina are less heavy on average? State appropriate hypotheses, do your test, obtain a P-value and state your conclusion, in terms of the original data.</li>
</ol>
<p>Solution</p>
<p>Let <span class="math inline">\(\mu\)</span> be the population mean (the mean weight of all babies born in North Carolina). Null hypothesis is <span class="math inline">\(H_0: \mu=7.3\)</span> pounds, and the alternative is that the mean is less: <span class="math inline">\(H_a: \mu&lt;7.3\)</span> pounds.</p>
<p>Note that I defined <span class="math inline">\(\mu\)</span> first before I used it.</p>
<p>This is a one-sided alternative, which we need to feed into <code>t.test</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(bw<span class="sc">$</span>weight_pounds, <span class="at">mu =</span> <span class="fl">7.3</span>, <span class="at">alternative =</span> <span class="st">"less"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  bw$weight_pounds
t = -3.4331, df = 499, p-value = 0.0003232
alternative hypothesis: true mean is less than 7.3
95 percent confidence interval:
     -Inf 7.179752
sample estimates:
mean of x 
  7.06875 </code></pre>
</div>
</div>
<p>Or with <code>with</code>. If you see what I mean.</p>
<p>The P-value is 0.0003, which is <em>less</em> than any <span class="math inline">\(\alpha\)</span> we might have chosen: we <em>reject</em> the null hypothesis in favour of the alternative, and thus we conclude that the mean birth weight of babies in North Carolina is indeed less than 7.3 pounds.</p>
<p>“Reject the null hypothesis” is <em>not</em> a complete answer. You need to say something about what rejecting the null hypothesis means <em>in this case</em>: that is, you must make a statement about birth weights of babies.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" type="a">
<li>The theory behind the <span class="math inline">\(t\)</span>-test says that the distribution of birth weights should be (approximately) normally distributed. Obtain a histogram of the birth weights. Does it look approximately normal? Comment briefly. (You’ll have to pick a number of bins for your histogram first. I don’t mind very much what you pick, as long as it’s not obviously too many or too few bins.)</li>
</ol>
<p>Solution</p>
<p>We did this before (and discussed the number of bins before), so I’ll just reproduce my 10-bin histogram (which is what I preferred, but this is a matter of taste):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(bw, <span class="fu">aes</span>(<span class="at">x =</span> weight_pounds)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="one-sample-inference_files/figure-html/ncbirths-inf-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>So, we were assessing normality. What about that?</p>
<p>It is mostly normal-looking, but I am suspicious about those <em>very</em> low birth weights, the ones below about 4 pounds. There are too many of those, as I see it.</p>
<p>If you think this is approximately normal, you need to make some comment along the lines of “the shape is approximately symmetric with no outliers”. I think my first answer is better, but this answer is worth something, since it is a not completely unreasonable interpretation of the histogram.</p>
<p>A normal quantile plot is better for assessing normality than a histogram is, but I won’t make you do one until we have seen the idea in class. Here’s the normal quantile plot for these data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(bw, <span class="fu">aes</span>(<span class="at">sample =</span> weight_pounds)) <span class="sc">+</span> <span class="fu">stat_qq</span>() <span class="sc">+</span> <span class="fu">stat_qq_line</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="one-sample-inference_files/figure-html/ncbirths-inf-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This is rather striking: the lowest birthweights (the ones below 5 pounds or so) are <em>way</em> too low for a normal distribution to apply. The top end is fine (except perhaps for that one very heavy baby), but there are too many low birthweights for a normal distribution to be believable. Note how much clearer this story is than on the histogram.</p>
<p>Having said that, the <span class="math inline">\(t\)</span>-test, especially with a sample size as big as this (500), behaves <em>very</em> well when the data are somewhat non-normal (because it takes advantage of the Central Limit Theorem: that is, it’s the <em>sampling distribution of the sample mean</em> whose shape matters). So, even though the data are definitely not normal, I wouldn’t be too worried about our test.</p>
<p>This perhaps gives some insight as to why Freedman-Diaconis said we should use so many bins for our histogram. We have a lot of low-end outliers, so that the IQR is actually <em>small</em> compared to the overall spread of the data (as measured, say, by the SD or the range) and so FD thinks we need a lot of bins to describe the shape. Sturges is based on data being approximately normal, so it will tend to produce a small number of bins for data that have outliers.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</section>
<section id="inferring-ice-break-up-in-nenana-1" class="level2" data-number="6.10">
<h2 data-number="6.10" class="anchored" data-anchor-id="inferring-ice-break-up-in-nenana-1"><span class="header-section-number">6.10</span> Inferring ice break-up in Nenana</h2>
<p>Nenana, Alaska, is about 50 miles west of Fairbanks. Every spring, there is a contest in Nenana. A wooden tripod is placed on the frozen river, and people try to guess the exact minute when the ice melts enough for the tripod to fall through the ice. The contest started in 1917 as an amusement for railway workers, and has taken place every year since. Now, hundreds of thousands of people enter their guesses on the Internet and the prize for the winner can be as much as $300,000.</p>
<p>Because so much money is at stake, and because the exact same tripod is placed at the exact same spot on the ice every year, the data are consistent and accurate. The data are in <a href="http://ritsokiguess.site/datafiles/nenana.txt">link</a>.</p>
<p>Yes, we saw these data before.</p>
<ol type="a">
<li>Read the data into R, as before, or use the data frame that you read in before. Note that the values are separated by <em>tabs</em> rather than spaces, so you’ll need an appropriate <code>read_</code> to read it in.</li>
</ol>
<p>Solution</p>
<p>These are “tab-separated values”, so <code>read_tsv</code> is the thing, as for the Australian athletes:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>myurl <span class="ot">&lt;-</span> <span class="st">"http://ritsokiguess.site/datafiles/nenana.txt"</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>nenana <span class="ot">&lt;-</span> <span class="fu">read_tsv</span>(myurl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 87 Columns: 3
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
chr (1): Date&amp;Time
dbl (2): Year, JulianDate

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<p>Use whatever name you like for the data frame. One that is different from any of the column headers is smart; then it is clear whether you mean the whole data frame or one of its columns. <code>ice</code> or <code>melt</code> or anything like that would also be good.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" type="a">
<li>Obtain a 90% confidence interval for the mean <code>JulianDate</code>. What interval do you get? Looking back at your histogram, do you have any doubts about the validity of what you have just done?</li>
</ol>
<p>Solution</p>
<p>This is a matter of using <code>t.test</code> and pulling out the interval. Since we are looking for a non-standard interval, we have to remember <code>conf.level</code> as the way to get the confidence level that we want. I’m going with <code>with</code> this time, though the dollar-sign thing is equally as good:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(nenana, <span class="fu">t.test</span>(JulianDate, <span class="at">conf.level =</span> <span class="fl">0.90</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  JulianDate
t = 197.41, df = 86, p-value &lt; 2.2e-16
alternative hypothesis: true mean is not equal to 0
90 percent confidence interval:
 124.4869 126.6018
sample estimates:
mean of x 
 125.5443 </code></pre>
</div>
</div>
<p>Between 124.5 and 126.6 days into the year. Converting that into something we can understand (because I want to), there are <span class="math inline">\(31+28+31+30=120\)</span> days in January through April (in a non-leap year), so this says that the mean breakup date is between about May 4 and May 6.</p>
<p>The <span class="math inline">\(t\)</span>-test is based on an assumption of data coming from a normal distribution. The histogram we made earlier looks pretty much normal, so there are no doubts about normality and thus no doubts about the validity of what we have done, on the evidence we have seen so far. (I have some doubts on different grounds, based on another of the plots we did earlier, which I’ll explain later, but all I’m expecting you to do is to look at the histogram and say “Yep, that’s normal enough”. Bear in mind that the sample size is 87, which is large enough for the Central Limit Theorem to be pretty helpful, so that we don’t need the data to be more than “approximately normal” for the sampling distribution of the sample mean to be very close to <span class="math inline">\(t\)</span> with the right df.)</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" type="a">
<li>An old-timer in Nenana strokes his grey beard and says “When I were young, I remember the tripod used to fall into the water around May 10”. In a non-leap year, May 10 is Julian day 130. Test the null hypothesis that the mean <code>JulianDay</code> is 130, against the alternative that it is less. What do you conclude? What practical implication does that have (assuming that the old-timer has a good memory)?</li>
</ol>
<p>Solution</p>
<p>The test is <code>t.test</code> again, but this time we have to specify a null mean and a direction of alternative:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(nenana, <span class="fu">t.test</span>(JulianDate, <span class="at">mu =</span> <span class="dv">130</span>, <span class="at">alternative =</span> <span class="st">"less"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  JulianDate
t = -7.0063, df = 86, p-value = 2.575e-10
alternative hypothesis: true mean is less than 130
95 percent confidence interval:
     -Inf 126.6018
sample estimates:
mean of x 
 125.5443 </code></pre>
</div>
</div>
<p>For a test, look first at the P-value, which is 0.0000000002575: that is to say, the P-value is very small, definitely smaller than 0.05 (or any other <span class="math inline">\(\alpha\)</span> you might have chosen). So we <em>reject</em> the null hypothesis, and conclude that the mean <code>JulianDate</code> is actually <em>less</em> than 130.</p>
<p>Now, this is the date on which the ice breaks up on average, and we have concluded that it is <em>earlier</em> than it used to be, since we are assuming the old-timer’s memory is correct.</p>
<p>This is evidence in favour of global warming; a small piece of evidence, to be sure, but the ice is melting earlier than it used to all over the Arctic, so it’s not just in Nenana that it is happening. You don’t need to get to the “global warming” part, but I <em>do</em> want you to observe that the ice is breaking up earlier than it used to.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" type="a">
<li>Plot <code>JulianDate</code> against <code>Year</code> on a scatterplot. What recent trends, if any, do you see? Comment briefly. (You did this before, but I have some extra comments on the graph this time, so feel free to just read this part.)</li>
</ol>
<p>Solution</p>
<p>I liked the <code>ggplot</code> with a smooth trend on it:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(nenana, <span class="fu">aes</span>(<span class="at">x =</span> Year, <span class="at">y =</span> JulianDate)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_smooth</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using method = 'loess' and formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="one-sample-inference_files/figure-html/nenana-inf-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>There was something obvious to see: after about 1960, there is a clear downward trend: the ice is breaking up earlier on average every year. Even though there is a lot of variability, the overall trend, viewed this way, is clear (and consistent with the test we did earlier). Note that the old-timer’s value of 130 is the kind of <code>JulianDate</code> we would typically observe around 1920, which would make the old-timer over 90 years old.</p>
<p>All right, why did I say I had some doubts earlier? Well, because of this downward trend, the mean is not actually the same all the way through, so it doesn’t make all that much sense to estimate it, which is what we were doing earlier by doing a confidence interval or a hypothesis test. What would actually make more sense is to estimate the mean <code>JulianDate</code> <em>for a particular year</em>. This could be done by a regression: predict <code>JulianDate</code> from <code>Year</code>, and then get a “confidence interval for the mean response” (as you would have seen in B27 or will see in C67). The trend isn’t really linear, but is not that far off. I can modify the previous picture to give you an idea. Putting in <code>method="lm"</code> fits a line; as we see later, <code>lm</code> does regressions in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(nenana, <span class="fu">aes</span>(<span class="at">x =</span> Year, <span class="at">y =</span> JulianDate)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="one-sample-inference_files/figure-html/nenana-inf-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Compare the confidence interval for the mean <code>JulianDate</code> in 1920: 126 to 131 (the shaded area on the graph), with 2000: 121 to 125. A change of about 5 days over 80 years. And with the recent trend that we saw above, it’s probably changing faster than that now. Sobering indeed.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</section>
<section id="diameters-of-trees-1" class="level2" data-number="6.11">
<h2 data-number="6.11" class="anchored" data-anchor-id="diameters-of-trees-1"><span class="header-section-number">6.11</span> Diameters of trees</h2>
<p>The Wade Tract in Thomas County, Georgia, is an old-growth forest of longleaf pine trees. It has survived in a relatively undisturbed state since before settlements of the area by Europeans. For each tree in the tract, researchers measured the diameter at breast height. This is a standard measure in forestry: it is defined as the diameter of the tree at 4.5 feet above the ground.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> They are interested in the mean diameter at breast height of the trees in this tract. These values are in <a href="http://ritsokiguess.site/datafiles/treediameter.csv">http://ritsokiguess.site/datafiles/treediameter.csv</a>. The diameters are measured in centimetres. The easiest way to get the URL is to <em>right</em>-click on the blue text and select Copy URL. (If you copy and paste the actual text you might end up with extra spaces, especially if the printed URL goes over two lines.)</p>
<ol type="a">
<li>Read in and display (some of) the data.</li>
</ol>
<p>Solution</p>
<p>The obvious way is this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>my_url <span class="ot">&lt;-</span> <span class="st">"http://ritsokiguess.site/datafiles/treediameter.csv"</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>trees <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(my_url)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 40 Columns: 1
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (1): diameter

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>trees</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["diameter"],"name":[1],"type":["dbl"],"align":["right"]}],"data":[{"1":"10.5"},{"1":"13.3"},{"1":"26.0"},{"1":"18.3"},{"1":"52.2"},{"1":"9.2"},{"1":"26.1"},{"1":"17.6"},{"1":"40.5"},{"1":"31.8"},{"1":"47.2"},{"1":"11.4"},{"1":"2.7"},{"1":"69.3"},{"1":"44.4"},{"1":"16.9"},{"1":"35.7"},{"1":"5.4"},{"1":"44.2"},{"1":"2.2"},{"1":"4.3"},{"1":"7.8"},{"1":"38.1"},{"1":"2.2"},{"1":"11.4"},{"1":"51.5"},{"1":"4.9"},{"1":"39.7"},{"1":"32.6"},{"1":"51.8"},{"1":"43.6"},{"1":"2.3"},{"1":"44.6"},{"1":"31.5"},{"1":"40.3"},{"1":"22.3"},{"1":"43.3"},{"1":"37.5"},{"1":"29.1"},{"1":"27.9"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>Call the data frame what you like, though it is better to use a name that tells you what the dataframe contains (rather than something like <code>mydata</code>).</p>
<p>Extra 1: there is only one column, so you can pretend the columns are separated by anything at all. Thus you could use this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>my_url <span class="ot">&lt;-</span> <span class="st">"http://ritsokiguess.site/datafiles/treediameter.csv"</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>trees <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(my_url, <span class="st">" "</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 40 Columns: 1
── Column specification ────────────────────────────────────────────────────────
Delimiter: " "
dbl (1): diameter

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>trees</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["diameter"],"name":[1],"type":["dbl"],"align":["right"]}],"data":[{"1":"10.5"},{"1":"13.3"},{"1":"26.0"},{"1":"18.3"},{"1":"52.2"},{"1":"9.2"},{"1":"26.1"},{"1":"17.6"},{"1":"40.5"},{"1":"31.8"},{"1":"47.2"},{"1":"11.4"},{"1":"2.7"},{"1":"69.3"},{"1":"44.4"},{"1":"16.9"},{"1":"35.7"},{"1":"5.4"},{"1":"44.2"},{"1":"2.2"},{"1":"4.3"},{"1":"7.8"},{"1":"38.1"},{"1":"2.2"},{"1":"11.4"},{"1":"51.5"},{"1":"4.9"},{"1":"39.7"},{"1":"32.6"},{"1":"51.8"},{"1":"43.6"},{"1":"2.3"},{"1":"44.6"},{"1":"31.5"},{"1":"40.3"},{"1":"22.3"},{"1":"43.3"},{"1":"37.5"},{"1":"29.1"},{"1":"27.9"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>or even this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>my_url <span class="ot">&lt;-</span> <span class="st">"http://ritsokiguess.site/datafiles/treediameter.csv"</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>trees <span class="ot">&lt;-</span> <span class="fu">read_table</span>(my_url)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
── Column specification ────────────────────────────────────────────────────────
cols(
  diameter = col_double()
)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>trees</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["diameter"],"name":[1],"type":["dbl"],"align":["right"]}],"data":[{"1":"10.5"},{"1":"13.3"},{"1":"26.0"},{"1":"18.3"},{"1":"52.2"},{"1":"9.2"},{"1":"26.1"},{"1":"17.6"},{"1":"40.5"},{"1":"31.8"},{"1":"47.2"},{"1":"11.4"},{"1":"2.7"},{"1":"69.3"},{"1":"44.4"},{"1":"16.9"},{"1":"35.7"},{"1":"5.4"},{"1":"44.2"},{"1":"2.2"},{"1":"4.3"},{"1":"7.8"},{"1":"38.1"},{"1":"2.2"},{"1":"11.4"},{"1":"51.5"},{"1":"4.9"},{"1":"39.7"},{"1":"32.6"},{"1":"51.8"},{"1":"43.6"},{"1":"2.3"},{"1":"44.6"},{"1":"31.5"},{"1":"40.3"},{"1":"22.3"},{"1":"43.3"},{"1":"37.5"},{"1":"29.1"},{"1":"27.9"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>Extra 2: you might be wondering how they measure the diameter without doing something like drilling a hole through the tree. They don’t actually measure the diameter at all. What they measure is the <em>circumference</em> of the tree, which is easy enough to do with a tape measure. Longleaf pines are usually near circular, so you get the diameter by taking the circumference and dividing by <span class="math inline">\(\pi\)</span>. <a href="https://www.portlandoregon.gov/trees/article/424017">This City of Portland website</a> shows you how it’s done.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" type="a">
<li>Make a suitable plot of your dataframe.</li>
</ol>
<p>Solution</p>
<p>One quantitative variable, so a histogram. Choose a sensible number of bins. There are 40 observations, so a number of bins up to about 10 is good. Sturges’ rule says 6 since <span class="math inline">\(2^6=64\)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(trees, <span class="fu">aes</span>(<span class="at">x=</span>diameter)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="one-sample-inference_files/figure-html/trees-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Extra 1: comments come later, but you might care to note (if only for yourself) that the distribution is a little skewed to the right, or, perhaps better, has <em>no</em> left tail at all. You might even observe that diameters cannot be less than 0 (they are measurements), and so you might expect a skew away from the limit.</p>
<p>After you’ve looked at the <span class="math inline">\(t\)</span> procedures for these data, we’ll get back to the shape.</p>
<p>Extra 2: later we look at a more precise tool for assessing normality, the normal quantile plot, which looks like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(trees, <span class="fu">aes</span>(<span class="at">sample=</span>diameter)) <span class="sc">+</span> <span class="fu">stat_qq</span>() <span class="sc">+</span> <span class="fu">stat_qq_line</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="one-sample-inference_files/figure-html/trees-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>If the data come from a normal distribution, the points should follow the straight line, at least approximately. Here, most of the points do, except for the points on the left, which veer away upwards from the line: that is, the highest values, on the right, are about right for a normal distribution, but the lowest values, on the left, <em>don’t go down low enough</em>.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> Thus, the problem with normality is not the long tail on the right, but the short one on the left. It is hard to get this kind of insight from the histogram, but at the moment, it’s the best we have.</p>
<p>The big problems, for things like <span class="math inline">\(t\)</span>-tests that depend on means, is stuff like outliers, or long tails, with extreme values that might distort the mean. Having short tails, as the left tail here, will make the distribution look non-normal but won’t cause any problems for the <span class="math inline">\(t\)</span>-tests.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" type="a">
<li>Obtain a 95% confidence interval for the mean diameter.</li>
</ol>
<p>Solution</p>
<p>This is <code>t.test</code>, but with <code>conf.level</code> to get the interval (and then you ignore the P-value):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(trees, <span class="fu">t.test</span>(diameter))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  diameter
t = 9.748, df = 39, p-value = 5.245e-12
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 21.6274 32.9526
sample estimates:
mean of x 
    27.29 </code></pre>
</div>
</div>
<p>The mean diameter of a longleaf pine (like the ones in this tract) is between 21.6 and 33.0 centimetres.</p>
<p>If you prefer, do it this way:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(trees<span class="sc">$</span>diameter)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  trees$diameter
t = 9.748, df = 39, p-value = 5.245e-12
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 21.6274 32.9526
sample estimates:
mean of x 
    27.29 </code></pre>
</div>
</div>
<p>You need to <em>state the answer</em> and <em>round it off suitably</em>. The actual diameters in the data have one decimal place, so you can give the same accuracy for the CI, or <em>at most</em> two decimals (so 21.63 to 32.95 cm would also be OK).<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a> Giving an answer with more decimals is something you cannot possibly justify. Worse even than giving too many decimals is not writing out the interval at all. <em>Never</em> make your reader find something in output. If they want it, tell them what it is.</p>
<p>Thus, here (if this were being graded), one mark for the output, one more for saying what the interval is, and the third if you give the interval with a sensible number of decimals.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" type="a">
<li>Based on what you have seen so far, would you expect to reject a null hypothesis that the population mean diameter (of all longleaf pines like these) is 35 cm? Explain briefly. Then, carry out the test (against a two-sided alternative) and explain briefly whether you were right.</li>
</ol>
<p>Solution</p>
<p>The logic is that “plausible” values for the population mean, ones you believe, are inside the interval, and implausible ones that you don’t believe are outside. Remember that the interval is your best answer to “what is the population mean”, and 35 is outside the interval so you don’t think the population mean is 35, and thus you would reject it.</p>
<p>Are we right? Take out the <code>conf.level</code> and put in a <code>mu</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(trees, <span class="fu">t.test</span>(diameter, <span class="at">mu =</span> <span class="dv">35</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  diameter
t = -2.754, df = 39, p-value = 0.008895
alternative hypothesis: true mean is not equal to 35
95 percent confidence interval:
 21.6274 32.9526
sample estimates:
mean of x 
    27.29 </code></pre>
</div>
</div>
<p>The P-value is less than our <span class="math inline">\(\alpha\)</span> of 0.05, so we would indeed reject a mean of 35 cm (in favour of the mean being different from 35).</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" type="a">
<li>Would you expect 35 cm to be in a <em>99%</em> confidence interval for the mean diameter? Explain briefly, and then see if you were right.</li>
</ol>
<p>Solution</p>
<p>The P-value is less than 0.01 (as well as being less than 0.05), so, in the same way that 35 was outside the 95% interval, it should be outside the 99% CI also. Maybe not by much, though, since the P-value is only just less than 0.01:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(trees, <span class="fu">t.test</span>(diameter, <span class="at">conf.level =</span> <span class="fl">0.99</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  diameter
t = 9.748, df = 39, p-value = 5.245e-12
alternative hypothesis: true mean is not equal to 0
99 percent confidence interval:
 19.70909 34.87091
sample estimates:
mean of x 
    27.29 </code></pre>
</div>
</div>
<p>Indeed so, outside, but only just.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</section>
<section id="one-sample-cholesterol-1" class="level2" data-number="6.12">
<h2 data-number="6.12" class="anchored" data-anchor-id="one-sample-cholesterol-1"><span class="header-section-number">6.12</span> One-sample cholesterol</h2>
<p>The data set <a href="http://ritsokiguess.site/datafiles/cholest.csv">here</a> contains cholesterol measurements for heart attack patients (at several different times) as well as for a group of control patients. We will focus on the control patients in this question.</p>
<ol type="a">
<li>Read in and display (some of) the data.</li>
</ol>
<p>Solution</p>
<p>This is (as you might guess) a <code>.csv</code>, so:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>my_url <span class="ot">&lt;-</span> <span class="st">"http://ritsokiguess.site/datafiles/cholest.csv"</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>cholest <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(my_url)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 30 Columns: 4
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (4): 2-Day, 4-Day, 14-Day, control

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>cholest</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["2-Day"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["4-Day"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["14-Day"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["control"],"name":[4],"type":["dbl"],"align":["right"]}],"data":[{"1":"270","2":"218","3":"156","4":"196"},{"1":"236","2":"234","3":"NA","4":"232"},{"1":"210","2":"214","3":"242","4":"200"},{"1":"142","2":"116","3":"NA","4":"242"},{"1":"280","2":"200","3":"NA","4":"206"},{"1":"272","2":"276","3":"256","4":"178"},{"1":"160","2":"146","3":"142","4":"184"},{"1":"220","2":"182","3":"216","4":"198"},{"1":"226","2":"238","3":"248","4":"160"},{"1":"242","2":"288","3":"NA","4":"182"},{"1":"186","2":"190","3":"168","4":"182"},{"1":"266","2":"236","3":"236","4":"198"},{"1":"206","2":"244","3":"NA","4":"182"},{"1":"318","2":"258","3":"200","4":"238"},{"1":"294","2":"240","3":"264","4":"198"},{"1":"282","2":"294","3":"NA","4":"188"},{"1":"234","2":"220","3":"264","4":"166"},{"1":"224","2":"200","3":"NA","4":"204"},{"1":"276","2":"220","3":"188","4":"182"},{"1":"282","2":"186","3":"182","4":"178"},{"1":"360","2":"352","3":"294","4":"212"},{"1":"310","2":"202","3":"214","4":"164"},{"1":"280","2":"218","3":"NA","4":"230"},{"1":"278","2":"248","3":"198","4":"186"},{"1":"288","2":"278","3":"NA","4":"162"},{"1":"288","2":"248","3":"256","4":"182"},{"1":"244","2":"270","3":"280","4":"218"},{"1":"236","2":"242","3":"204","4":"170"},{"1":"NA","2":"NA","3":"NA","4":"200"},{"1":"NA","2":"NA","3":"NA","4":"176"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>Note for yourself that there are 30 observations (and some missing ones), and a column called that is the one we’ll be working with.</p>
<p>Extra: the 2-day, 4-day and 14-day columns need to be referred to with funny “backticks” around their names, because a column name cannot contain a <code>-</code> or start with a number. This is not a problem here, since we won’t be using those columns, but if we wanted to, this would not work:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>cholest <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">xbar =</span> <span class="fu">mean</span>(<span class="dv">2</span><span class="sc">-</span>Day))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in `summarize()`:
ℹ In argument: `xbar = mean(2 - Day)`.
Caused by error in `h()`:
! error in evaluating the argument 'x' in selecting a method for function 'mean': object 'Day' not found</code></pre>
</div>
</div>
<p>because it is looking for a column called <code>Day</code>, which doesn’t exist. The meaning of <code>2-Day</code> is “take the column called <code>Day</code> and subtract it from 2”. To make this work, we have to supply the backticks ourselves:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>cholest <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">xbar =</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">2-Day</span><span class="st">`</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["xbar"],"name":[1],"type":["dbl"],"align":["right"]}],"data":[{"1":"253.9286"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>This column also has missing values (at the bottom), so here I’ve asked to remove the missing values<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a> before working out the mean. Otherwise the mean is, unhelpfully, missing as well.</p>
<p>You might imagine that dealing with column names like this would get annoying. There is a package called <code>janitor</code> that has a function called <code>clean_names</code> to save you the trouble. Install it first, then load it:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>and then pipe your dataframe into <code>clean_names</code> and see what happens:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>cholest <span class="sc">%&gt;%</span> <span class="fu">clean_names</span>() <span class="ot">-&gt;</span> cholest1</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>cholest1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["x2_day"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["x4_day"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["x14_day"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["control"],"name":[4],"type":["dbl"],"align":["right"]}],"data":[{"1":"270","2":"218","3":"156","4":"196"},{"1":"236","2":"234","3":"NA","4":"232"},{"1":"210","2":"214","3":"242","4":"200"},{"1":"142","2":"116","3":"NA","4":"242"},{"1":"280","2":"200","3":"NA","4":"206"},{"1":"272","2":"276","3":"256","4":"178"},{"1":"160","2":"146","3":"142","4":"184"},{"1":"220","2":"182","3":"216","4":"198"},{"1":"226","2":"238","3":"248","4":"160"},{"1":"242","2":"288","3":"NA","4":"182"},{"1":"186","2":"190","3":"168","4":"182"},{"1":"266","2":"236","3":"236","4":"198"},{"1":"206","2":"244","3":"NA","4":"182"},{"1":"318","2":"258","3":"200","4":"238"},{"1":"294","2":"240","3":"264","4":"198"},{"1":"282","2":"294","3":"NA","4":"188"},{"1":"234","2":"220","3":"264","4":"166"},{"1":"224","2":"200","3":"NA","4":"204"},{"1":"276","2":"220","3":"188","4":"182"},{"1":"282","2":"186","3":"182","4":"178"},{"1":"360","2":"352","3":"294","4":"212"},{"1":"310","2":"202","3":"214","4":"164"},{"1":"280","2":"218","3":"NA","4":"230"},{"1":"278","2":"248","3":"198","4":"186"},{"1":"288","2":"278","3":"NA","4":"162"},{"1":"288","2":"248","3":"256","4":"182"},{"1":"244","2":"270","3":"280","4":"218"},{"1":"236","2":"242","3":"204","4":"170"},{"1":"NA","2":"NA","3":"NA","4":"200"},{"1":"NA","2":"NA","3":"NA","4":"176"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>These are all legit column names; the <code>-</code> has been replaced by an underscore, and each of the first three column names has gained an <code>x</code> on the front so that it no longer starts with a number. This then works:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>cholest1 <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">xbar =</span> <span class="fu">mean</span>(x2_day, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["xbar"],"name":[1],"type":["dbl"],"align":["right"]}],"data":[{"1":"253.9286"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" type="a">
<li>Make a suitable plot of the cholesterol levels of the control patients, and comment briefly on the shape of the distribution.</li>
</ol>
<p>Solution</p>
<p>There is one quantitative variable, so a histogram, as ever:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(cholest, <span class="fu">aes</span>(<span class="at">x=</span>control)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="one-sample-inference_files/figure-html/luprands-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Pick a number of bins that shows the shape reasonably well. Too many or too few won’t. (Sturges’ rule says 6, since there are 30 observations and <span class="math inline">\(2^5=32\)</span>.) Seven bins also works, but by the time you get to 8 bins or more, you are starting to lose a clear picture of the shape. Four bins is, likewise, about as low as you can go before getting too crude a picture.</p>
<p>Choosing one of these numbers of bins will make it clear that the distribution is somewhat skewed to the right.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" type="a">
<li>It is recommended that people in good health, such as the Control patients here, keep their cholesterol level below 200. Is there evidence that the mean cholesterol level of the population of people of which the Control patients are a sample is less than 200? Show that you understand the process, and state your conclusion in the context of the data.</li>
</ol>
<p>Solution</p>
<p>The word “evidence” means to do a hypothesis test and get a P-value. Choose an <span class="math inline">\(\alpha\)</span> first, such as 0.05.</p>
<p>Testing a mean implies a one-sample <span class="math inline">\(t\)</span>-test. We are trying to prove that the mean is less than 200, so that’s our alternative: <span class="math inline">\(H_a: \mu &lt; 200\)</span>, and therefore the null is that the mean is equal to 200: <span class="math inline">\(H_0: \mu = 200\)</span>. (You might think it makes more logical sense to have <span class="math inline">\(H_0: \mu \ge 200\)</span>, which is also fine. As long as the null hypothesis has an equals in it in a logical place, you are good.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(cholest, <span class="fu">t.test</span>(control, <span class="at">mu=</span><span class="dv">200</span>, <span class="at">alternative =</span> <span class="st">"less"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  control
t = -1.6866, df = 29, p-value = 0.05121
alternative hypothesis: true mean is less than 200
95 percent confidence interval:
     -Inf 200.0512
sample estimates:
mean of x 
 193.1333 </code></pre>
</div>
</div>
<p>This is also good:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(cholest<span class="sc">$</span>control, <span class="at">mu=</span><span class="dv">200</span>, <span class="at">alternative =</span> <span class="st">"less"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  cholest$control
t = -1.6866, df = 29, p-value = 0.05121
alternative hypothesis: true mean is less than 200
95 percent confidence interval:
     -Inf 200.0512
sample estimates:
mean of x 
 193.1333 </code></pre>
</div>
</div>
<p>I like the first version better because a lot of what we do later involves giving a data frame, and then working with things in that data frame. This is more like that.</p>
<p>This test is <em>one</em>-sided because we are looking for evidence of <em>less</em>; if the mean is actually <em>more</em> than 200, we don’t care about that. For a one-sided test, R requires you to say which side you are testing.</p>
<p>The P-value is not (quite) less than 0.05, so we cannot quite reject the null. Therefore, there is no evidence that the mean cholesterol level (of the people of which the control group are a sample) is less than 200. Or, this mean is not significantly less than 200. Or, we conclude that this mean is equal to 200. Or, we conclude that this mean could be 200. Any of those.</p>
<p>If you chose a different <span class="math inline">\(\alpha\)</span>, draw the right conclusion for the <span class="math inline">\(\alpha\)</span> you chose. For example, with <span class="math inline">\(\alpha=0.10\)</span>, we <em>do</em> have evidence that the mean is less than 200. Being consistent is more important than getting the same answer as me.</p>
<p>Writing out all the steps correctly shows that you understand the process. Anything less doesn’t.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" type="a">
<li>What values could the population mean cholesterol level take? You might need to get some more output to determine this.</li>
</ol>
<p>Solution</p>
<p>This is <em>not</em> quoting the sample mean, giving that as your answer, and then stopping. The sample mean should, we hope, be somewhere the population mean, but it is almost certainly not the same as the population mean, because there is variability due to random sampling. (This is perhaps the most important thing in all of Statistics: recognizing that variability exists and dealing with it.)</p>
<p>With that in mind, the question means to get a range of values that the population mean could be: that is to say, a confidence interval. The one that came out of the previous output is one-sided, to go with the one-sided test, but confidence intervals for us are two-sided, so we have to run the test again, but two-sided, to get it. To do that, take out the “alternative”, thus (you can also take out the null mean, since a confidence interval has no null hypothesis):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(cholest, <span class="fu">t.test</span>(control))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  control
t = 47.436, df = 29, p-value &lt; 2.2e-16
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 184.8064 201.4603
sample estimates:
mean of x 
 193.1333 </code></pre>
</div>
</div>
<p>With 95% confidence, the population mean cholesterol level is between 184.8 and 201.5.</p>
<p><em>You need to state the interval, and you also need to round off the decimal places to something sensible.</em> This is because in your statistical life, you are providing results to someone else <em>in a manner that they can read and understand.</em> They do not have time to go searching in some output, or to fish through some excessive number of decimal places. If that’s what you give them, they will ask you to rewrite your report, wasting everybody’s time when you could have done it right the first time.</p>
<p>How many decimal places is a good number? Look back at your data. In this case, the cholesterol values are whole numbers (zero decimal places). A confidence interval is talking about a mean. In this case, we have a sample size of 30, which is between 10 and 100, so we can justify one extra decimal place beyond the data, here one decimal altogether, or two <em>at the absolute outside</em>. (Two is more justifiable if the sample size is bigger than 100.) See, for example, <a href="https://www2.southeastern.edu/Academics/Faculty/dgurney/Math241/StatTopics/SciNot.htm">this</a>, in particular the piece at the bottom.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" type="a">
<li>Explain briefly why you would be reasonably happy to trust the <span class="math inline">\(t\)</span> procedures in this question. (There are two points you need to make.)</li>
</ol>
<p>Solution</p>
<p>The first thing is to look back at the graph you made earlier. This was skewed to the right (“moderately” or “somewhat” or however you described it). This would seem to say that the <span class="math inline">\(t\)</span> procedures were not very trustworthy, since the population distribution doesn’t look very normal in shape.</p>
<p>However, the second thing is to look at the sample size. We have the central limit theorem, which says (for us) that the larger the sample is, the less the normality matters, when it comes to estimating the mean. Here, the sample size is 30, which, for the central limit theorem, is large enough to overcome moderate non-normality in the data.</p>
<p>My take, which I was trying to guide you towards, is that our non-normality was not too bad, and so our sample size is large enough to trust the <span class="math inline">\(t\)</span> procedures we used.</p>
<p>Extra 1: What matters is the tradeoff between sample size and the extent of the non-normality. If your data is less normal, you need a larger sample size to overcome it. Even a sample size of 500 might not be enough if your distribution is very skewed, or if you have extreme outliers.</p>
<p>The place <span class="math inline">\(n=30\)</span> comes from is back from the days when we only ever used printed tables. In most textbooks, if you printed the <span class="math inline">\(t\)</span>-table on one page in a decent-sized font, you’d get to about 29 df before running out of space. Then they would say “<span class="math inline">\(\infty\)</span> df” and put the normal-distribution <span class="math inline">\(z\)</span> numbers in. If the df you needed was bigger than what you had in the table, you used this last line: that is, you called the sample “large”. Try it in your stats textbooks: I bet the df go up to 30, then you get a few more, then the <span class="math inline">\(z\)</span> numbers.</p>
<p>Extra 2: By now you are probably thinking that this is very subjective, and so it is. What actually matters is the shape of the thing called the <em>sampling distribution of the sample mean</em>. That is to say, what kind of sample means you might get in repeated samples from your population. The problem is that you don’t know what the population looks like.<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a> But we can fake it up, in a couple of ways: we can play what-if and pretend we know what the population looks like (to get some understanding for “populations like that”), or we can use a technique called the “bootstrap” that will tell us what kind of sample means we might get from the population that <em>our</em> sample came from (this seems like magic and, indeed, is).</p>
<p>The moral of the story is that the central limit theorem is more powerful than you think.</p>
<p>To illustrate my first idea, let’s pretend the population looks like this, with a flat top:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="one-sample-inference_files/figure-html/brunhopter-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Only values between 0 and 1 are possible, and each of those is equally likely. Not very normal in shape. So let’s take some random samples of size <em>three</em>, not in any sense a large sample, from this “uniform” population, and see what kind of sample means we get. This technique is called <strong>simulation</strong>: rather than working out the answer by math, we’re letting the computer approximate the answer for us. Here’s one simulated sample:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>u <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">3</span>)</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>u</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9475841 0.1245953 0.2277288</code></pre>
</div>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(u)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4333027</code></pre>
</div>
</div>
<p>and here’s the same thing 1000 times, including a histogram of the sample means:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(<span class="at">sim =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">my_sample =</span> <span class="fu">list</span>(<span class="fu">runif</span>(<span class="dv">3</span>))) <span class="sc">%&gt;%</span> </span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">my_mean =</span> <span class="fu">mean</span>(my_sample)) <span class="sc">%&gt;%</span> </span>
<span id="cb85-5"><a href="#cb85-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> my_mean)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">12</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="one-sample-inference_files/figure-html/toeber-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This is our computer-generated assessment of what the sampling distribution of the sample mean looks like. Isn’t this looking like a normal distribution?</p>
<p>Let’s take a moment to realize what this is saying. If the population looks like the flat-topped uniform distribution, the central limit theorem kicks in for a sample of size <em>three</em>, and thus if your population looks like this, <span class="math inline">\(t\)</span> procedures will be perfectly good for <span class="math inline">\(n=3\)</span> or bigger, <em>even though the population isn’t normal</em>.</p>
<p>Thus, when you’re thinking about whether to use a <span class="math inline">\(t\)</span>-test or something else (that we’ll learn about later), the distribution shape matters, <em>but so does the sample size</em>.</p>
<p>I should say a little about my code. I’m not expecting you to figure out details now (we see the ideas properly in simulating power of tests), but in words, one line at a time:</p>
<ul>
<li>generate 1000 (“many”) samples each of 3 observations from a uniform distribution</li>
<li>for each sample, work out the mean of it</li>
<li>turn those sample means into a data frame with a column called <code>value</code></li>
<li>make a histogram of those.</li>
</ul>
<p>Now, the central limit theorem doesn’t always work as nicely as this, but maybe a sample size of 30 is large enough to overcome the skewness that we had:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(cholest, <span class="fu">aes</span>(<span class="at">x=</span>control)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="one-sample-inference_files/figure-html/schauffhusen-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>That brings us to my second idea above.</p>
<p>The sample that we had is in some sense an “estimate of the population”. To think about the sampling distribution of the sample mean, we need more estimates of the population. How might we get those? The curious answer is to <em>sample from the sample</em>. This is the idea behind the <em>bootstrap</em>. (This is what Lecture 3c is about.) The name comes from the expression “pulling yourself up by your own bootstraps”, meaning “to begin an enterprise or recover from a setback without any outside help” (from <a href="https://www.yourdictionary.com/pull-oneself-up-by-one-s-bootstraps">here</a>), something that should be difficult or impossible. How is it possible to understand a sampling distribution with only one sample?</p>
<p>We have to be a bit careful. Taking a sample from the sample would give us the original sample back. So, instead, we sample <em>with replacement</em>, so that each bootstrap sample is different:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(cholest<span class="sc">$</span>control)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 160 162 164 166 170 176 178 178 182 182 182 182 182 184 186 188 196 198 198
[20] 198 200 200 204 206 212 218 230 232 238 242</code></pre>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">sample</span>(cholest<span class="sc">$</span>control, <span class="at">replace=</span><span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 164 166 166 166 166 176 178 178 182 182 182 182 182 188 198 198 198 200 200
[20] 200 200 204 206 206 218 218 230 232 232 242</code></pre>
</div>
</div>
<p>A bootstrap sample contains repeats of the original data values, and misses some of the others. Here, the original data had values 160 and 162 that are missing in the bootstrap sample; the original data had one value 166, but the bootstrap sample has <em>four</em>! I sorted the data and the bootstrap sample to make this clearer; you will not need to sort. This is a perfectly good bootstrap sample:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(cholest<span class="sc">$</span>control, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 242 232 198 160 242 182 182 182 198 162 212 198 242 204 242 242 170 198 182
[20] 206 232 170 218 188 166 178 164 160 218 196</code></pre>
</div>
</div>
<p>So now we know what to do: take lots of bootstrap samples, work out the mean of each, plot the means, and see how normal it looks. The only new idea here is the sampling with replacement:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(<span class="at">sim =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">my_sample =</span> <span class="fu">list</span>(<span class="fu">sample</span>(cholest<span class="sc">$</span>control, <span class="at">replace =</span> <span class="cn">TRUE</span>))) <span class="sc">%&gt;%</span> </span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">my_mean =</span> <span class="fu">mean</span>(my_sample)) <span class="sc">%&gt;%</span> </span>
<span id="cb93-5"><a href="#cb93-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> my_mean)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">12</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="one-sample-inference_files/figure-html/schuomarchers-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>That looks pretty normal, not obviously skewed, and so the <span class="math inline">\(t\)</span> procedures we used will be reliable enough.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>The height of a typical human breast off the ground. Men have a breast too, you know.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>The normal quantile plot is rather interesting: it says that the uppermost values are approximately normal, but the <em>smallest</em> eight or so values are too bunched up to be normal. That is, normality fails not because of the long tail on the right, but the bunching on the left. Still right-skewed, though.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>In some languages, a dot is used to concatenate bits of text, or as a way of calling a method on an object. But in R, a dot has no special meaning, and is used in function names like <code>t.test</code>. Or <code>p.value</code>.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Whether you think it is or not may depend on how many bins you have on your histogram. With 5 bins it looks like an outlier, but with 6 it does not. Try it and see.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>The height of a typical human breast off the ground. Men have a breast too, you know.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>They cannot go down far enough, because they can’t go below zero.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>One more decimal place than the data is the maximum you give in a CI.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>In R, missing values are labelled <code>NA</code>, and <code>rm</code> is Unix/C shorthand for <em>remove</em>.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>If you did, all your problems would be over.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./working-with-dataframes.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Working with dataframes</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./two-sample-inference.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Two-sample inference</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>