<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Problems and Solutions in Applied Statistics (2nd ed) - 20&nbsp; Regression with categorical variables</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./dates-and-times.html" rel="next">
<link href="./multiple-regression.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<link href="site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="site_libs/pagedtable-1.1/js/pagedtable.js"></script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./regression-categorical.html"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Regression with categorical variables</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Problems and Solutions in Applied Statistics (2nd ed)</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./getting_used.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Getting used to R and R Studio</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./reading-in.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Reading in data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./making-graphs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Drawing graphs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-summaries.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data exploration</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./working-with-dataframes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Working with dataframes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./one-sample-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">One-sample inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./two-sample-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Two-sample inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Power and sample size</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sign.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">The sign test</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mood-median.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Mood median test</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./matched-pairs-sign.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Matched pairs t and sign test</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./normal-quantile.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Normal quantile plots</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./analysis-of-variance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Analysis of variance</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./reports.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Writing reports</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./coding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Learning to code</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dandruff.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Treating dandruff</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tidying-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Tidying data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./simple-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Simple regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multiple-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Multiple regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression-categorical.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Regression with categorical variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dates-and-times.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Dates and times</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Functions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./vector-matrix.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Vector and matrix algebra</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bootstrap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">The Bootstrap</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stan.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Bayesian Statistics with Stan</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression-revisited.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Regression revisited</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistic-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Logistic regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ordinal-response.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Logistic regression with ordinal response</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nominal-response.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Logistic regression with nominal response</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./survival-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Survival analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./anova-revisited.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Analysis of variance revisited</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ancova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Analysis of covariance</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./manova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Multivariate analysis of variance</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./repeated-measures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Repeated measures</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./discriminant-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Discriminant analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cluster.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Hierarchical cluster analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./kmeans-cluster.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">K-means cluster analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./maps.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Drawing maps with Leaflet</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mds.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Multidimensional Scaling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Principal Components</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./fa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Factor Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./loglin.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Frequency table analysis</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#crickets-revisited" id="toc-crickets-revisited" class="nav-link active" data-scroll-target="#crickets-revisited"><span class="header-section-number">20.1</span> Crickets revisited</a></li>
  <li><a href="#pulse-rates-and-marching" id="toc-pulse-rates-and-marching" class="nav-link" data-scroll-target="#pulse-rates-and-marching"><span class="header-section-number">20.2</span> Pulse rates and marching</a></li>
  <li><a href="#crickets-revisited-1" id="toc-crickets-revisited-1" class="nav-link" data-scroll-target="#crickets-revisited-1"><span class="header-section-number">20.3</span> Crickets revisited</a></li>
  <li><a href="#pulse-rates-and-marching-1" id="toc-pulse-rates-and-marching-1" class="nav-link" data-scroll-target="#pulse-rates-and-marching-1"><span class="header-section-number">20.4</span> Pulse rates and marching</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Regression with categorical variables</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="crickets-revisited" class="level2" data-number="20.1">
<h2 data-number="20.1" class="anchored" data-anchor-id="crickets-revisited"><span class="header-section-number">20.1</span> Crickets revisited</h2>
<p>This is a continuation of the crickets problem that you may have seen before (minus the data tidying).</p>
<p>Male tree crickets produce “mating songs” by rubbing their wings together to produce a chirping sound. It is hypothesized that female tree crickets identify males of the correct species by how fast (in chirps per second) the male’s mating song is. This is called the “pulse rate”. Some data for two species of crickets are in <a href="http://ritsokiguess.site/datafiles/crickets2.csv">link</a> as a CSV file. The columns are species (text), temperature, and pulse rate (numbers). This is the tidied version of the data set that the previous version of this question had you create. The research question is whether males of the different species have different average pulse rates. It is also of interest to see whether temperature has an effect, and if so, what.</p>
<ol type="a">
<li><p>Read the data into R and display what you have.</p></li>
<li><p>Do a two-sample <span class="math inline">\(t\)</span>-test to see whether the mean pulse rates differ between species. What do you conclude?</p></li>
<li><p>Can you do that two-sample <span class="math inline">\(t\)</span>-test as a regression?</p></li>
<li><p>The analysis in the last part did not use temperature, however. Is it possible that temperature also has an effect? To assess this, draw a scatterplot of pulse rate against temperature, with the points distinguished, somehow, by the species they are from.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p></li>
<li><p>What does the plot tell you that the <span class="math inline">\(t\)</span>-test doesn’t? How would you describe differences in pulse rates between species now?</p></li>
<li><p>Fit a regression predicting pulse rate from species and temperature. Compare the P-value for species in this regression to the one from the <span class="math inline">\(t\)</span>-test. What does that tell you?</p></li>
<li><p>Make suitable residual plots for the regression <code>pulse.1</code>.</p></li>
</ol>
</section>
<section id="pulse-rates-and-marching" class="level2" data-number="20.2">
<h2 data-number="20.2" class="anchored" data-anchor-id="pulse-rates-and-marching"><span class="header-section-number">20.2</span> Pulse rates and marching</h2>
<p>Forty students, some male and some female, measured their resting pulse rates. Then they marched in place for one minute and measured their pulse rate again. Our aim is to use regression to predict the pulse rate after the marching from the pulse rate before, and to see whether that is different for males and females. The data set is in <a href="http://ritsokiguess.site/datafiles/pulsemarch.csv">http://ritsokiguess.site/datafiles/pulsemarch.csv</a>.</p>
<ol type="a">
<li><p>Read in and display (some of) the data.</p></li>
<li><p>Make a suitable graph using all three variables, adding appropriate regression line(s) to the plot.</p></li>
<li><p>Explain briefly but carefully how any effects of pulse rate before on pulse rate after, and also of sex on pulse rate after, show up on your plot. (If either explanatory variable has no effect, explain how you know.)</p></li>
<li><p>Run a regression predicting pulse rate after from the other two variables. Display the output.</p></li>
<li><p>Looking at your graph, does the significance (or lack of) of each of your two explanatory variables surprise you? Explain briefly.</p></li>
<li><p>What does the numerical value of the Estimate for <code>Sex</code> in your regression output mean, in the context of this data set? Explain briefly.</p></li>
</ol>
<p>My solutions follow:</p>
</section>
<section id="crickets-revisited-1" class="level2" data-number="20.3">
<h2 data-number="20.3" class="anchored" data-anchor-id="crickets-revisited-1"><span class="header-section-number">20.3</span> Crickets revisited</h2>
<p>This is a continuation of the crickets problem that you may have seen before (minus the data tidying).</p>
<p>Male tree crickets produce “mating songs” by rubbing their wings together to produce a chirping sound. It is hypothesized that female tree crickets identify males of the correct species by how fast (in chirps per second) the male’s mating song is. This is called the “pulse rate”. Some data for two species of crickets are in <a href="http://ritsokiguess.site/datafiles/crickets2.csv">link</a> as a CSV file. The columns are species (text), temperature, and pulse rate (numbers). This is the tidied version of the data set that the previous version of this question had you create. The research question is whether males of the different species have different average pulse rates. It is also of interest to see whether temperature has an effect, and if so, what.</p>
<ol type="a">
<li>Read the data into R and display what you have.</li>
</ol>
<p>Solution</p>
<p>Nothing terribly surprising here:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>my_url <span class="ot">&lt;-</span> <span class="st">"http://ritsokiguess.site/datafiles/crickets2.csv"</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>crickets <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(my_url)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 31 Columns: 3
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): species
dbl (2): temperature, pulse_rate

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>crickets</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["species"],"name":[1],"type":["chr"],"align":["left"]},{"label":["temperature"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["pulse_rate"],"name":[3],"type":["dbl"],"align":["right"]}],"data":[{"1":"exclamationis","2":"20.8","3":"67.9"},{"1":"exclamationis","2":"20.8","3":"65.1"},{"1":"exclamationis","2":"24.0","3":"77.3"},{"1":"exclamationis","2":"24.0","3":"78.7"},{"1":"exclamationis","2":"24.0","3":"79.4"},{"1":"exclamationis","2":"24.0","3":"80.4"},{"1":"exclamationis","2":"26.2","3":"85.8"},{"1":"exclamationis","2":"26.2","3":"86.6"},{"1":"exclamationis","2":"26.2","3":"87.5"},{"1":"exclamationis","2":"26.2","3":"89.1"},{"1":"exclamationis","2":"28.4","3":"98.6"},{"1":"exclamationis","2":"29.0","3":"100.8"},{"1":"exclamationis","2":"30.4","3":"99.3"},{"1":"exclamationis","2":"30.4","3":"101.7"},{"1":"niveus","2":"17.2","3":"44.3"},{"1":"niveus","2":"18.3","3":"47.2"},{"1":"niveus","2":"18.3","3":"47.6"},{"1":"niveus","2":"18.3","3":"49.6"},{"1":"niveus","2":"18.9","3":"50.3"},{"1":"niveus","2":"18.9","3":"51.8"},{"1":"niveus","2":"20.4","3":"60.0"},{"1":"niveus","2":"21.0","3":"58.5"},{"1":"niveus","2":"21.0","3":"58.9"},{"1":"niveus","2":"22.1","3":"60.7"},{"1":"niveus","2":"23.5","3":"69.8"},{"1":"niveus","2":"24.2","3":"70.9"},{"1":"niveus","2":"25.9","3":"76.2"},{"1":"niveus","2":"26.5","3":"76.1"},{"1":"niveus","2":"26.5","3":"77.0"},{"1":"niveus","2":"26.5","3":"77.7"},{"1":"niveus","2":"28.6","3":"84.7"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>31 crickets, which is what I remember. What species are there?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>crickets <span class="sc">%&gt;%</span> <span class="fu">count</span>(species)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["species"],"name":[1],"type":["chr"],"align":["left"]},{"label":["n"],"name":[2],"type":["int"],"align":["right"]}],"data":[{"1":"exclamationis","2":"14"},{"1":"niveus","2":"17"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>That looks good. We proceed.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" type="a">
<li>Do a two-sample <span class="math inline">\(t\)</span>-test to see whether the mean pulse rates differ between species. What do you conclude?</li>
</ol>
<p>Solution</p>
<p>Drag your mind way back to this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(pulse_rate <span class="sc">~</span> species, <span class="at">data =</span> crickets)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  pulse_rate by species
t = 5.2236, df = 28.719, p-value = 1.401e-05
alternative hypothesis: true difference in means between group exclamationis and group niveus is not equal to 0
95 percent confidence interval:
 14.08583 32.22677
sample estimates:
mean in group exclamationis        mean in group niveus 
                   85.58571                    62.42941 </code></pre>
</div>
</div>
<p>There is strong evidence of a difference in means (a P-value around 0.00001), and the confidence interval says that the mean chirp rate is higher for <em>exclamationis</em>. That is, not just for the crickets that were observed here, but for <em>all</em> crickets of these two species.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" type="a">
<li>Can you do that two-sample <span class="math inline">\(t\)</span>-test as a regression?</li>
</ol>
<p>Solution</p>
<p>Hang onto the “pulse rate depends on species” idea and try that in <code>lm</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>pulse<span class="fl">.0</span> <span class="ot">&lt;-</span> <span class="fu">lm</span>(pulse_rate <span class="sc">~</span> species, <span class="at">data =</span> crickets)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pulse<span class="fl">.0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = pulse_rate ~ species, data = crickets)

Residuals:
    Min      1Q  Median      3Q     Max 
-20.486  -9.458  -1.729  13.342  22.271 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     85.586      3.316  25.807  &lt; 2e-16 ***
speciesniveus  -23.156      4.478  -5.171 1.58e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 12.41 on 29 degrees of freedom
Multiple R-squared:  0.4797,    Adjusted R-squared:  0.4617 
F-statistic: 26.74 on 1 and 29 DF,  p-value: 1.579e-05</code></pre>
</div>
</div>
<p>I had to use “model 0” for this since I already have a <code>pulse.1</code> below and I didn’t want to go down and renumber everything.</p>
<p>Look along the <code>speciesniveus</code> line. Ignoring the fact that it is negative, the <span class="math inline">\(t\)</span>-statistic is almost the same as before (5.17 vs.<br>
5.22) and so is the P-value (<span class="math inline">\(1.4 \times 10^{-5}\)</span> vs.&nbsp;<span class="math inline">\(1.6 \times 10^{-5}\)</span>).</p>
<p>Why aren’t they exactly the same? Regression is assuming equal variances everywhere (that is, within the two <code>species</code>), and before, we did the Welch-Satterthwaite test that does not assume equal variances. What if we do the pooled <span class="math inline">\(t\)</span>-test instead?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(pulse_rate <span class="sc">~</span> species, <span class="at">data =</span> crickets, <span class="at">var.equal =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  pulse_rate by species
t = 5.1706, df = 29, p-value = 1.579e-05
alternative hypothesis: true difference in means between group exclamationis and group niveus is not equal to 0
95 percent confidence interval:
 13.99690 32.31571
sample estimates:
mean in group exclamationis        mean in group niveus 
                   85.58571                    62.42941 </code></pre>
</div>
</div>
<p>Now the regression and the <span class="math inline">\(t\)</span>-test <em>do</em> give exactly the same answers. We’ll think about that equal-spreads assumption again later.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" type="a">
<li>The analysis in the last part did not use temperature, however. Is it possible that temperature also has an effect? To assess this, draw a scatterplot of pulse rate against temperature, with the points distinguished, somehow, by the species they are from.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></li>
</ol>
<p>Solution</p>
<p>One of the wonderful things about <code>ggplot</code> is that doing the obvious thing works:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(crickets, <span class="fu">aes</span>(<span class="at">x =</span> temperature, <span class="at">y =</span> pulse_rate, <span class="at">colour =</span> species)) <span class="sc">+</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="regression-categorical_files/figure-html/crickets-b-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" type="a">
<li>What does the plot tell you that the <span class="math inline">\(t\)</span>-test doesn’t? How would you describe differences in pulse rates between species now?</li>
</ol>
<p>Solution</p>
<p>The plot tells you that (for both species) as temperature goes up, pulse rate goes up as well. <em>Allowing for that</em>, the difference in pulse rates between the two species is even clearer than it was before. To see an example, pick a temperature, and note that the mean pulse rate at that temperature seems to be at least 10 higher for <em>exclamationis</em>, with a high degree of consistency. The <span class="math inline">\(t\)</span>-test mixed up all the pulse rates at all the different temperatures. Even though the conclusion was clear enough, it could be clearer if we incorporated temperature into the analysis. There was also a potential source of unfairness in that the <em>exclamationis</em> crickets tended to be observed at higher temperatures than <em>niveus</em> crickets; since pulse rates increase with temperature, the apparent difference in pulse rates between the species might have been explainable by one species being observed mainly in higher temperatures. This was <em>utterly invisible</em> to us when we did the <span class="math inline">\(t\)</span>-test, but it shows the importance of accounting for all the relevant variables when you do your analysis.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> If the species had been observed at opposite temperatures, we might have concluded<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> that <em>niveus</em> have the higher pulse rates on average. I come back to this later when I discuss the confidence interval for species difference that comes out of the regression model with temperature.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="6" type="a">
<li>Fit a regression predicting pulse rate from species and temperature. Compare the P-value for species in this regression to the one from the <span class="math inline">\(t\)</span>-test. What does that tell you?</li>
</ol>
<p>Solution</p>
<p>This is actually a so-called “analysis of covariance model”, which properly belongs in D29, but it’s really just a regression:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>pulse<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">lm</span>(pulse_rate <span class="sc">~</span> species <span class="sc">+</span> temperature, <span class="at">data =</span> crickets)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pulse<span class="fl">.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = pulse_rate ~ species + temperature, data = crickets)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.0128 -1.1296 -0.3912  0.9650  3.7800 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    -7.21091    2.55094  -2.827  0.00858 ** 
speciesniveus -10.06529    0.73526 -13.689 6.27e-14 ***
temperature     3.60275    0.09729  37.032  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.786 on 28 degrees of freedom
Multiple R-squared:  0.9896,    Adjusted R-squared:  0.9888 
F-statistic:  1331 on 2 and 28 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The P-value for species is now <span class="math inline">\(6.27\times 10^{-14}\)</span> or 0.00000000000006, which is even less than the P-value of 0.00001 that came out of the <span class="math inline">\(t\)</span>-test. That is to say, when you know temperature, you can be even more sure of your conclusion that there is a difference between the species.</p>
<p>The R-squared for this regression is almost 99%, which says that if you know both temperature and species, you can predict the pulse rate almost exactly.</p>
<p>In the regression output, the slope for species is about <span class="math inline">\(-10\)</span>. It is labelled <code>speciesniveus</code>. Since species is categorical, <code>lm</code> uses the first category, <em>exclamationis</em>, as the baseline and expresses each other species relative to that. Since the slope is about <span class="math inline">\(-10\)</span>, it says that at any given temperature, the mean pulse rate for <em>niveus</em> is about 10 less than for <em>exclamationis</em>. This is pretty much what the scatterplot told us.</p>
<p>We can go a little further here:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(pulse<span class="fl">.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   2.5 %    97.5 %
(Intercept)   -12.436265 -1.985547
speciesniveus -11.571408 -8.559175
temperature     3.403467  3.802038</code></pre>
</div>
</div>
<p>The second line says that the pulse rate for <em>niveus</em> is between about 8.5 and 11.5 less than for <em>exclamationis</em>, at any given temperature (comparing the two species at the same temperature as each other, but that temperature could be anything). This is a lot shorter than the CI that came out of the <span class="math inline">\(t\)</span>-test, that went from 14 to 32. This is because we are now accounting for temperature, which also makes a difference. (In the <span class="math inline">\(t\)</span>-test, the temperatures were all mixed up). What we also see is that the <span class="math inline">\(t\)</span>-interval is shifted up compared to the one from the regression. This is because the <span class="math inline">\(t\)</span>-interval conflates<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> two things: the <em>exclamationis</em> crickets do have a higher pulse rate, but they were also observed at higher temperatures, which makes it look as if their pulse rates are more higher<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> than they really are, when you account for temperature.</p>
<p>This particular model constrains the slope with temperature to be the same for both species (just the intercepts differ). If you want to allow the slopes to differ between species, you add an interaction between temperature and species:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>pulse<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">lm</span>(pulse_rate <span class="sc">~</span> species <span class="sc">*</span> temperature, <span class="at">data =</span> crickets)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pulse<span class="fl">.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = pulse_rate ~ species * temperature, data = crickets)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.7031 -1.3417 -0.1235  0.8100  3.6330 

Coefficients:
                          Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)               -11.0408     4.1515  -2.659    0.013 *  
speciesniveus              -4.3484     4.9617  -0.876    0.389    
temperature                 3.7514     0.1601  23.429   &lt;2e-16 ***
speciesniveus:temperature  -0.2340     0.2009  -1.165    0.254    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.775 on 27 degrees of freedom
Multiple R-squared:  0.9901,    Adjusted R-squared:  0.989 
F-statistic: 898.9 on 3 and 27 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>To see whether adding the interaction term added anything to the prediction,<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a> compare the model with and without using <code>anova</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(pulse<span class="fl">.1</span>, pulse<span class="fl">.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Res.Df"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["RSS"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Df"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["Sum of Sq"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["F"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["Pr(>F)"],"name":[6],"type":["dbl"],"align":["right"]}],"data":[{"1":"28","2":"89.34987","3":"NA","4":"NA","5":"NA","6":"NA","_rn_":"1"},{"1":"27","2":"85.07409","3":"1","4":"4.275779","5":"1.357006","6":"0.2542464","_rn_":"2"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>There’s no significant improvement by adding the interaction, so there’s no evidence that having different slopes for each species is necessary. This is the same interpretation as any <code>anova</code> for comparing two regressions: the two models are not significantly different in fit, so go with the simpler one, that is, the one without the interaction.</p>
<p>Note that <code>anova</code> gave the same P-value as did the <span class="math inline">\(t\)</span>-test for the slope coefficient for the interaction in <code>summary</code>, 0.254 in both cases. This is because there were only two species and therefore only one slope coefficient was required to distinguish them. If there had been three species, we would have had to look at the <code>anova</code> output to hunt for a difference among species, since there would have been two slope coefficients, each with its own P-value.<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a></p>
<p>If you haven’t seen interactions before, don’t worry about this. The idea behind it is that we are testing whether we needed lines with different slopes and we concluded that we don’t. Don’t worry so much about the mechanism behind <code>pulse.2</code>; just worry about how it somehow provides a way of modelling two different slopes, one for each species, which we can then test to see whether it helps.</p>
<p>The upshot is that we do not need different slopes; the model <code>pulse.1</code> with the same slope for each species describes what is going on.</p>
<p><code>ggplot</code> makes it almost laughably easy to add regression lines for each species to our plot, thus:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(crickets, <span class="fu">aes</span>(<span class="at">x =</span> temperature, <span class="at">y =</span> pulse_rate, <span class="at">colour =</span> species)) <span class="sc">+</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="regression-categorical_files/figure-html/crickets-b-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The lines are almost exactly parallel, so having the same slope for each species makes perfect sense.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="7" type="a">
<li>Make suitable residual plots for the regression <code>pulse.1</code>.</li>
</ol>
<p>Solution</p>
<p>First, the plot of residuals against fitted values (after all, it <em>is</em> a regression):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pulse<span class="fl">.1</span>, <span class="fu">aes</span>(<span class="at">x =</span> .fitted, <span class="at">y =</span> .resid)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="regression-categorical_files/figure-html/crickets-b-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This looks nice and random.</p>
<p>Now, we plot the residuals against the explanatory variables. There are two, temperature and species, but the latter is categorical. We’ll have some extra issues around species, but before we get to that, we have to remember that the data and the output from the regression are in different places when we plot them. There are different ways to get around that. Perhaps the simplest is to use <code>pulse.1</code> as our “default” data frame and then get <code>temperature</code> from the right place:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pulse<span class="fl">.1</span>, <span class="fu">aes</span>(<span class="at">x =</span> crickets<span class="sc">$</span>temperature, <span class="at">y =</span> .resid)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="regression-categorical_files/figure-html/crickets-b-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>I don’t see anything untoward there.</p>
<p>Species. We want to compare the residuals for the two species, which is categorical. Since the residuals are quantitative, this suggests a boxplot. Remembering to get species from the right place again, that goes like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pulse<span class="fl">.1</span>, <span class="fu">aes</span>(<span class="at">x =</span> crickets<span class="sc">$</span>species, <span class="at">y =</span> .resid)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="regression-categorical_files/figure-html/crickets-b-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>For the residuals, the median should be zero within each group, and the two groups should be approximately normal with mean 0 and about the same spread. Same spread looks OK, since the boxes are almost exactly the same height, but the normality is not quite there, since both distributions are a little bit skewed to the right. That would also explain why the median residual in each group is a little bit less than zero, because the mathematics requires the overall <em>mean</em> residual to be zero, and the right-skewness would make the mean higher than the median.</p>
<p>Is that non-normality really problematic? Well, I could look at the normal quantile plot of all the residuals together:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pulse<span class="fl">.1</span>, <span class="fu">aes</span>(<span class="at">sample =</span> .resid)) <span class="sc">+</span> <span class="fu">stat_qq</span>() <span class="sc">+</span> <span class="fu">stat_qq_line</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="regression-categorical_files/figure-html/crickets-b-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>There’s a little weirdness at the top, and a tiny indication of a curve (that would suggest a little right-skewedness), but not really much to worry about. If that third-highest residual were a bit lower (say, 3 rather than 3.5) and maybe if the lowest residual was a bit lower, I don’t think we’d have anything to complain about at all.</p>
<p>So, I’m not worried.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</section>
<section id="pulse-rates-and-marching-1" class="level2" data-number="20.4">
<h2 data-number="20.4" class="anchored" data-anchor-id="pulse-rates-and-marching-1"><span class="header-section-number">20.4</span> Pulse rates and marching</h2>
<p>Forty students, some male and some female, measured their resting pulse rates. Then they marched in place for one minute and measured their pulse rate again. Our aim is to use regression to predict the pulse rate after the marching from the pulse rate before, and to see whether that is different for males and females. The data set is in <a href="http://ritsokiguess.site/datafiles/pulsemarch.csv">http://ritsokiguess.site/datafiles/pulsemarch.csv</a>.</p>
<ol type="a">
<li>Read in and display (some of) the data.</li>
</ol>
<p>Solution</p>
<p>As usual:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>my_url <span class="ot">&lt;-</span> <span class="st">"http://ritsokiguess.site/datafiles/pulsemarch.csv"</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>march <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(my_url)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 40 Columns: 3
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): Sex
dbl (2): Before, After

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>march</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["Sex"],"name":[1],"type":["chr"],"align":["left"]},{"label":["Before"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["After"],"name":[3],"type":["dbl"],"align":["right"]}],"data":[{"1":"Female","2":"72","3":"84"},{"1":"Male","2":"60","3":"72"},{"1":"Female","2":"68","3":"80"},{"1":"Male","2":"70","3":"72"},{"1":"Male","2":"68","3":"80"},{"1":"Male","2":"61","3":"75"},{"1":"Male","2":"80","3":"84"},{"1":"Male","2":"72","3":"76"},{"1":"Female","2":"64","3":"80"},{"1":"Female","2":"62","3":"92"},{"1":"Male","2":"60","3":"76"},{"1":"Female","2":"96","3":"100"},{"1":"Female","2":"64","3":"72"},{"1":"Female","2":"76","3":"88"},{"1":"Male","2":"55","3":"64"},{"1":"Male","2":"60","3":"68"},{"1":"Female","2":"46","3":"64"},{"1":"Female","2":"56","3":"64"},{"1":"Male","2":"88","3":"100"},{"1":"Male","2":"80","3":"88"},{"1":"Male","2":"66","3":"68"},{"1":"Female","2":"80","3":"104"},{"1":"Male","2":"68","3":"80"},{"1":"Male","2":"80","3":"88"},{"1":"Male","2":"76","3":"84"},{"1":"Female","2":"70","3":"80"},{"1":"Male","2":"59","3":"80"},{"1":"Male","2":"68","3":"76"},{"1":"Female","2":"64","3":"68"},{"1":"Male","2":"74","3":"84"},{"1":"Male","2":"84","3":"88"},{"1":"Male","2":"72","3":"80"},{"1":"Male","2":"60","3":"72"},{"1":"Male","2":"75","3":"88"},{"1":"Male","2":"76","3":"72"},{"1":"Female","2":"76","3":"96"},{"1":"Female","2":"64","3":"68"},{"1":"Female","2":"64","3":"68"},{"1":"Male","2":"60","3":"60"},{"1":"Female","2":"76","3":"104"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" type="a">
<li>Make a suitable graph using all three variables, adding appropriate regression line(s) to the plot.</li>
</ol>
<p>Solution</p>
<p>Two quantitative and one categorical says scatterplot, with colour distinguishing the categories (two here). <code>geom_smooth</code> adds a regression line to the plot for each <code>Sex</code>, which is what we want. I used <code>se=F</code> to remove the grey envelopes from the plot (because I thought they confused the issue):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(march, <span class="fu">aes</span>(<span class="at">x=</span>Before, <span class="at">y=</span>After, <span class="at">colour=</span>Sex)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se=</span>F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="regression-categorical_files/figure-html/fus-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Having only one regression line is not so good because that only shows that pulse rate after goes up with pulse rate before, but not if and how the sexes differ.</p>
<p>Extra: I took a shortcut of the process here, to make the question shorter. In practice, what you’d do is to put smooth trends on the plot first:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(march, <span class="fu">aes</span>(<span class="at">x=</span>Before, <span class="at">y=</span>After, <span class="at">colour=</span>Sex)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_smooth</span>(<span class="at">se=</span>F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using method = 'loess' and formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="regression-categorical_files/figure-html/hearter-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The red trend looks curved, but if you look carefully, pretty much all of<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a> the evidence for the curve comes from that point on the right with pulse rate before over 90 and pulse rate after around 100. If it weren’t for that, the red trend would be pretty close to linear. As you’ll recall, a decision about the kind of trend based on <em>one</em> observation is a pretty flimsy decision.</p>
<p><em>Then</em>, having seen that the trends are not obviously curved, you would draw the plot with the straight lines. (Fitting separate <em>curves</em> is a whole different story that I didn’t want to get into.)</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" type="a">
<li>Explain briefly but carefully how any effects of pulse rate before on pulse rate after, and also of sex on pulse rate after, show up on your plot. (If either explanatory variable has no effect, explain how you know.)</li>
</ol>
<p>Solution</p>
<p>There is an upward trend, so if the pulse rate before is higher, so is the pulse rate after. This is true for both males and females. (Or, holding <code>Sex</code> fixed, that is, comparing two people of the same sex.)</p>
<p>The red line is always above the blue line, so at any given <code>Before</code> pulse rate, the <code>After</code> pulse rate for a female is predicted to be higher than that for a male.</p>
<p>Note that you have to be careful: when talking about the effect of each explanatory variable, you have to <em>hold the other one constant</em> (in general, hold all the other ones constant). If you can word that in a way that makes sense in the context of the data you are looking at, so much the better.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" type="a">
<li>Run a regression predicting pulse rate after from the other two variables. Display the output.</li>
</ol>
<p>Solution</p>
<p>Thus:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>march<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">lm</span>(After<span class="sc">~</span>Before<span class="sc">+</span>Sex, <span class="at">data=</span>march)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(march<span class="fl">.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = After ~ Before + Sex, data = march)

Residuals:
     Min       1Q   Median       3Q      Max 
-11.8653  -4.6319  -0.4271   3.3856  16.0047 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  19.8003     7.9217   2.499   0.0170 *  
Before        0.9064     0.1127   8.046  1.2e-09 ***
SexMale      -4.8191     2.2358  -2.155   0.0377 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.918 on 37 degrees of freedom
Multiple R-squared:  0.6468,    Adjusted R-squared:  0.6277 
F-statistic: 33.87 on 2 and 37 DF,  p-value: 4.355e-09</code></pre>
</div>
</div>
<p>Extra: if you want “all the other variables except the response” as explanatory, there is also this shortcut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>march<span class="fl">.1</span>a <span class="ot">&lt;-</span> <span class="fu">lm</span>(After<span class="sc">~</span>., <span class="at">data=</span>march)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(march<span class="fl">.1</span>a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = After ~ ., data = march)

Residuals:
     Min       1Q   Median       3Q      Max 
-11.8653  -4.6319  -0.4271   3.3856  16.0047 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  19.8003     7.9217   2.499   0.0170 *  
SexMale      -4.8191     2.2358  -2.155   0.0377 *  
Before        0.9064     0.1127   8.046  1.2e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.918 on 37 degrees of freedom
Multiple R-squared:  0.6468,    Adjusted R-squared:  0.6277 
F-statistic: 33.87 on 2 and 37 DF,  p-value: 4.355e-09</code></pre>
</div>
</div>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" type="a">
<li>Looking at your graph, does the significance (or lack of) of each of your two explanatory variables surprise you? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>We noted a clear upward trend before, for both sexes, so there is no surprise that the <code>Before</code> pulse rate is significant.</p>
<p>The red dots (females) on the graph seemed to be on average above the blue ones (males), at least for similar before pulse rates. (This is not completely convincing, so you are entitled to be surprised also; note that the P-value, while significant, is not <em>that</em> small).</p>
<p>Extra: comparing the <em>lines</em> is less convincing, because how do we get a feel for whether these lines are more different than chance? One deceiving way to (fail to) get a feel for this is to re-draw our plot but with the grey envelopes:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(march, <span class="fu">aes</span>(<span class="at">x=</span>Before, <span class="at">y=</span>After, <span class="at">colour=</span>Sex)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="regression-categorical_files/figure-html/buttin-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The grey envelopes overlap substantially, which would make you think the lines are <em>not</em> significantly different. But, this is not the right way to compare the lines. It is a similar problem to that of comparing two <em>means</em> (that we would normally do with a two-sample test of some kind) by working out the two <em>one</em>-sample confidence intervals, and seeing whether they overlap. If they <em>do not</em>, then you can be sure that the means differ, but if they do overlap, then you cannot say anything about whether the means differ: maybe they do, maybe they don’t. This one is analogous; the grey envelopes overlap, so maybe the lines differ, maybe they don’t. Looking at the grey envelopes in this case gives you <em>no</em> insight about whether males and females differ.</p>
<p><a href="https://www.cscu.cornell.edu/news/statnews/stnews73.pdf">Here</a> is a short discussion of this issue (in the context of comparing two means).</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="6" type="a">
<li>What does the numerical value of the Estimate for <code>Sex</code> in your regression output mean, in the context of this data set? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>The estimate is labelled <code>SexMale</code>, and its value is <span class="math inline">\(-4.8\)</span>.</p>
<p><code>Sex</code> is a categorical variable, so it has a baseline category, which is the first one, <code>Female</code>. The Estimate <code>SexMale</code> shows how males compare to the baseline (females), at a fixed <code>Before</code> pulse rate. This value is <span class="math inline">\(-4.8\)</span>, so, at any <code>Before</code> pulse rate, the male <code>After</code> pulse rate is predicted to be 4.8 <em>less</em> than the female one.</p>
<p>I think you have to mention the value <span class="math inline">\(-4.8\)</span>, so that you can talk intelligently about what it means for these data.</p>
<p>Extra: the implication of our model is that the predicted difference is the <em>same</em> all the way along. You might have your doubts about that; you might think the lines are closer together on the left and further apart on the right. Another way to think about this is whether the lines are <em>parallel</em>: that is, whether they have the same slope. I’m inclined to think they do; the data points are fairly scattered, and I think the slopes would have to be a lot more different to be significantly different. But you don’t have to take my word for it: we can test this by adding an <strong>interaction term</strong> to the model. You might have seen this in ANOVA, where you are assessing the effect of one factor at different levels of the other. This is more or less the same idea. Note the <code>*</code> rather than the <code>+</code> in the model formula:<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>march<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">lm</span>(After<span class="sc">~</span>Before<span class="sc">*</span>Sex, <span class="at">data=</span>march)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(march<span class="fl">.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = After ~ Before * Sex, data = march)

Residuals:
     Min       1Q   Median       3Q      Max 
-11.2831  -4.3638  -0.3965   3.4077  16.6188 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     13.4390    11.1416   1.206    0.236    
Before           0.9991     0.1604   6.230 3.43e-07 ***
SexMale          7.9470    15.8095   0.503    0.618    
Before:SexMale  -0.1846     0.2263  -0.816    0.420    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.949 on 36 degrees of freedom
Multiple R-squared:  0.6532,    Adjusted R-squared:  0.6243 
F-statistic:  22.6 on 3 and 36 DF,  p-value: 2.11e-08</code></pre>
</div>
</div>
<p>The <code>Before:SexMale</code> term tests the interaction, and you see it is nowhere near significant. There is no justification for having lines with different slopes for males and females.</p>
<p>We were lucky here in that <code>Sex</code> has only two levels, so looking at the <code>summary</code> gave us what we wanted. If we had had an <code>Other</code> category for <code>Sex</code>, for people who don’t identify with either male or female, there would be two Estimates in the <code>summary</code> table, one comparing Male with Female, and one comparing Other with Female.<a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a> But maybe the significant difference is Male vs.&nbsp;Other, and we would never see it.</p>
<p>To look for <em>any</em> effect of a categorical variable, the right way is to use <code>drop1</code>, to see which variables, including categorical ones, can be removed as a whole, thus:<a href="#fn12" class="footnote-ref" id="fnref12" role="doc-noteref"><sup>12</sup></a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">drop1</span>(march<span class="fl">.2</span>, <span class="at">test=</span><span class="st">"F"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Df"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["Sum of Sq"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["RSS"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["AIC"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["F value"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["Pr(>F)"],"name":[6],"type":["dbl"],"align":["right"]}],"data":[{"1":"NA","2":"NA","3":"1738.512","4":"158.8762","5":"NA","6":"NA","_rn_":"<none>"},{"1":"1","2":"32.13734","3":"1770.649","4":"157.6089","5":"0.6654795","6":"0.4199971","_rn_":"Before:Sex"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>This <em>only</em> lists things that can be removed, in this case the interaction. It is not significant, so out it comes (resulting in our model <code>march.1</code>):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">drop1</span>(march<span class="fl">.1</span>, <span class="at">test=</span><span class="st">"F"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Df"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["Sum of Sq"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["RSS"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["AIC"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["F value"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["Pr(>F)"],"name":[6],"type":["dbl"],"align":["right"]}],"data":[{"1":"NA","2":"NA","3":"1770.649","4":"157.6089","5":"NA","6":"NA","_rn_":"<none>"},{"1":"1","2":"3097.976","3":"4868.625","4":"196.0675","5":"64.736188","6":"1.203225e-09","_rn_":"Before"},{"1":"1","2":"222.337","3":"1992.986","4":"160.3404","5":"4.646017","6":"3.770029e-02","_rn_":"Sex"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>Both remaining explanatory variables are significant, so we need to keep them both.</p>
<p>Our categorical explanatory variable has only two levels, so <code>drop1</code> and <code>summary</code> give the exact same P-values.</p>
<p>Extra 2:</p>
<p>Let’s go back and look at our data set again:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>march</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["Sex"],"name":[1],"type":["chr"],"align":["left"]},{"label":["Before"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["After"],"name":[3],"type":["dbl"],"align":["right"]}],"data":[{"1":"Female","2":"72","3":"84"},{"1":"Male","2":"60","3":"72"},{"1":"Female","2":"68","3":"80"},{"1":"Male","2":"70","3":"72"},{"1":"Male","2":"68","3":"80"},{"1":"Male","2":"61","3":"75"},{"1":"Male","2":"80","3":"84"},{"1":"Male","2":"72","3":"76"},{"1":"Female","2":"64","3":"80"},{"1":"Female","2":"62","3":"92"},{"1":"Male","2":"60","3":"76"},{"1":"Female","2":"96","3":"100"},{"1":"Female","2":"64","3":"72"},{"1":"Female","2":"76","3":"88"},{"1":"Male","2":"55","3":"64"},{"1":"Male","2":"60","3":"68"},{"1":"Female","2":"46","3":"64"},{"1":"Female","2":"56","3":"64"},{"1":"Male","2":"88","3":"100"},{"1":"Male","2":"80","3":"88"},{"1":"Male","2":"66","3":"68"},{"1":"Female","2":"80","3":"104"},{"1":"Male","2":"68","3":"80"},{"1":"Male","2":"80","3":"88"},{"1":"Male","2":"76","3":"84"},{"1":"Female","2":"70","3":"80"},{"1":"Male","2":"59","3":"80"},{"1":"Male","2":"68","3":"76"},{"1":"Female","2":"64","3":"68"},{"1":"Male","2":"74","3":"84"},{"1":"Male","2":"84","3":"88"},{"1":"Male","2":"72","3":"80"},{"1":"Male","2":"60","3":"72"},{"1":"Male","2":"75","3":"88"},{"1":"Male","2":"76","3":"72"},{"1":"Female","2":"76","3":"96"},{"1":"Female","2":"64","3":"68"},{"1":"Female","2":"64","3":"68"},{"1":"Male","2":"60","3":"60"},{"1":"Female","2":"76","3":"104"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>You might have been thinking, when we started, that these are before and after measurements <em>on the same people</em>, and so what we have here is matched pairs. So we do, but it’s not the kind of matched pairs we are accustomed to. Let’s begin by taking differences, getting rid of the <code>Before</code> and <code>After</code> columns, and see what we have left:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>march <span class="sc">%&gt;%</span> </span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(<span class="at">difference=</span>After<span class="sc">-</span>Before) <span class="sc">%&gt;%</span> </span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(<span class="sc">-</span>After, <span class="sc">-</span>Before) <span class="ot">-&gt;</span> march_paired</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>march_paired</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["Sex"],"name":[1],"type":["chr"],"align":["left"]},{"label":["difference"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"Female","2":"12"},{"1":"Male","2":"12"},{"1":"Female","2":"12"},{"1":"Male","2":"2"},{"1":"Male","2":"12"},{"1":"Male","2":"14"},{"1":"Male","2":"4"},{"1":"Male","2":"4"},{"1":"Female","2":"16"},{"1":"Female","2":"30"},{"1":"Male","2":"16"},{"1":"Female","2":"4"},{"1":"Female","2":"8"},{"1":"Female","2":"12"},{"1":"Male","2":"9"},{"1":"Male","2":"8"},{"1":"Female","2":"18"},{"1":"Female","2":"8"},{"1":"Male","2":"12"},{"1":"Male","2":"8"},{"1":"Male","2":"2"},{"1":"Female","2":"24"},{"1":"Male","2":"12"},{"1":"Male","2":"8"},{"1":"Male","2":"8"},{"1":"Female","2":"10"},{"1":"Male","2":"21"},{"1":"Male","2":"8"},{"1":"Female","2":"4"},{"1":"Male","2":"10"},{"1":"Male","2":"4"},{"1":"Male","2":"8"},{"1":"Male","2":"12"},{"1":"Male","2":"13"},{"1":"Male","2":"-4"},{"1":"Female","2":"20"},{"1":"Female","2":"4"},{"1":"Female","2":"4"},{"1":"Male","2":"0"},{"1":"Female","2":"28"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>In matched pairs, we are used to having <em>one</em> column of differences, and we test that for a mean or median of zero, to express no difference between before and after (or whatever it was). But now, we have an extra column <code>Sex</code>. We are not interested here in whether the differences average out to zero;<a href="#fn13" class="footnote-ref" id="fnref13" role="doc-noteref"><sup>13</sup></a> we care more about whether the differences differ (!) between males and females. That is to say, we have a two-sample matched pairs test!</p>
<p>At this point, your head ought to be hurting!</p>
<p>However, at this point what we are saying is that <em>if</em> you believe that the difference is a good way to summarize the effect of the exercise, then we have one measurement for each person, independent because different people’s measurements will be independent. It doesn’t matter where they came from. We have measurements on two groups, so some kind of two-sample test will be good. Which kind? Let’s look at a graph, a good one now being a boxplot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(march_paired, <span class="fu">aes</span>(<span class="at">x=</span>Sex, <span class="at">y=</span>difference)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="regression-categorical_files/figure-html/fridingen-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Or, if you like, a facetted normal quantile plot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(march_paired, <span class="fu">aes</span>(<span class="at">sample=</span>difference)) <span class="sc">+</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stat_qq</span>() <span class="sc">+</span> <span class="fu">stat_qq_line</span>() <span class="sc">+</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="fu">facet_wrap</span>(<span class="sc">~</span>Sex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="regression-categorical_files/figure-html/brugg-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>It seems to me that these are normal enough for a <span class="math inline">\(t\)</span>-test, given the sample sizes (feel free to disagree):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>march_paired <span class="sc">%&gt;%</span> <span class="fu">count</span>(Sex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["Sex"],"name":[1],"type":["chr"],"align":["left"]},{"label":["n"],"name":[2],"type":["int"],"align":["right"]}],"data":[{"1":"Female","2":"16"},{"1":"Male","2":"24"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>The spreads look a bit different, so I think I would prefer the Welch test here:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(difference<span class="sc">~</span>Sex, <span class="at">data=</span>march_paired)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  difference by Sex
t = 2.0307, df = 23.296, p-value = 0.05386
alternative hypothesis: true difference in means between group Female and group Male is not equal to 0
95 percent confidence interval:
 -0.08848652  9.92181986
sample estimates:
mean in group Female   mean in group Male 
           13.375000             8.458333 </code></pre>
</div>
</div>
<p>This time, there is not quite a significant difference between males and females. (The P-value is just the other side of 0.05.) Though the conclusion is different, the P-values are fairly similar.</p>
<p>Which test is better? I think treating it as matched pairs is assuming that the differences after minus before are the things to be looking at. This assumes that the after measurements are the before measurement plus a something that depends on treatment, but <em>not</em> on the before measurement. This would fail, for example, if all the after measurements are two times the before ones (so that the difference would be bigger if the before score was bigger). The regression approach is more flexible, because <em>any</em> linear relationship is taken care of. A matched-pairs model of this kind is a special case of the regression model but with the slope set to be 1. In our regression, the slope is less than 1, but not by much.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>This was the actual reason I thought of this question originally: I wanted you to do this.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>This was the actual reason I thought of this question originally: I wanted you to do this.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>And it shows the value of looking at relevant plots.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Mistakenly.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>Mixes up.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>This is actually grammatically correct.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>Though it’s hard to imagine being able to improve on an R-squared of 99%.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>This wouldn’t have told us about the overall effect of species.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>My mind just jumped to a former German soccer player by the name of Klaus Allofs.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p>To be precise, the * means “the main effects and the interaction together”; if you want to talk about just the interaction term, you denote it by <code>:</code>; note the <code>Before:SexMale</code> term in the summary table.<a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn11"><p>Female is the baseline, so everything gets compared with that, whether you like it or not.<a href="#fnref11" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn12"><p>The <code>test</code> piece says to do an <span class="math inline">\(F\)</span>-test, which is different from without the quotes, which would mean not to do any tests, <code>F</code> without quotes meaning <code>FALSE</code>.<a href="#fnref12" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn13"><p>I think it’s a given that pulse rates will be higher after exercise than before.<a href="#fnref13" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./multiple-regression.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Multiple regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./dates-and-times.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Dates and times</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>