---
title: "speech"
---

Do you think that northern Ontario begins at say, Barrie? Let me tell you about where we went camping. (Draw map in the air including Barrie, Sudbury, Timmins, Chapleau, and where we were.)

Salutation

My friend Slawek and his wife Zheniya like to go off-the-grid camping, and every so often they like to take me along with them. Slawek has a Landrover Discovery, and he wanted to show off what it could do, as well as to show off the beauty and tranquillity of the North. 

On Friday, we met at his house and went shopping, coming back with a truly incomprehensible quantity of food and water, all of which had to be packed, some into a giant cooler, along with the camping gear and all our other stuff, into the Landrover. This took some time, and it was about 9 pm before we set off, for our first night’s motel… in Sudbury. We got there about 2 am (!) and somehow managed to get about 8 hours’ sleep before needing to check out in the morning.

Our destination was still a long way off, and the last bit, north from Chapleau, was on a gravel road. There was a provincial park near where we were going, but my friends prefer to camp on crown land, which means that you can camp where you like, but the facilities you get are *zero*. To get to our camping spot, we turned off the gravel road, went several kilometres on another road that was two tire tracks with grass down the middle, and then turned off *that* to reach a large flat area that would be our home for the next week. There was enough time and daylight to set up our tents and a screenhouse (for shelter from bugs), and to cook and eat dinner. 

(distribute photos at this point)

There was a trail from our camping spot down to a lake. At the end of the trail, there was a small rowboat left for anyone to use, with paddles. (This is apparently quite common in this part of the world; people might borrow it to go fishing). We paddled (by which I mean Slawek and Zheniya paddled and I observed) to an island in the middle of the lake and hung out there for a bit.

We did visit the nearby provincial park a couple of times: once to hang out at the beach (for my friends to swim and for me to wade in up to about *here*). The water was kinda cold because it was early in the season yet. The other time, we rented a boat and went for a tour of the biggish lake after which the provincial park was named. (Most of the photos were taken on or of lakes, because that’s where the best views are to be had.) Provincial parks like this have nice campsites on beaches at the edge of the lake, and we visited a couple of these.

I mentioned that Slawek had a Landrover and wanted to show what it could do. We turned off the road onto a random trail that led to a lake. It was very bumpy, with improbable bends, rocks, muddy patches, standing water and all. But the the Landrover, and Slawek’s driving, got us through it and back (even though he had to stop a couple of times and work out how to get through some parts). At the end, he was very excited to have conquered it, and I was very relieved to have made it back in one piece.

On another day, another found boat, and another paddle to an island in the middle of a lake. It was mostly perfect weather, with the exception of maybe being a bit *too* hot, and when you are camping, there is nowhere to escape the heat.

We also never did really escape the bugs, mosquitoes and blackflies. I had to juggle the clothes I brought (for much less warm weather) and find some not-too-hot long sleeves and long pants in a vain attempt to keep from getting bitten. We thus decided to leave a day earlier and take two days to get back. Our packing up was slowed by being watched by a bear (that fortunately responded to being chased off). We were aiming for Timmins as our first night’s stop, but there was bad air quality there (we found out later what it was) and we stopped instead in a rather ramshackle motel in Chapleau instead. I realized that being away from people was nice for a change, but I felt more comfortable being in a town instead. 

The next day, heading towards Timmins, the sky was orange, and though the sun was shining, it seemed misty, just as we experienced a few days later in Toronto. Eventually, though, we did escape it, and stopped off at a couple of other provincial parks to go swimming or wading. The camping at these provincial parks, though, seemed positively luxurious compared to our experience: washrooms! running water! a store for supplies!

After many hours of travelling, I was back home. It was an enjoyable getaway that felt much longer than its nine days, and completely different from my usual routine, but it was also good to be home, and, somehow, good to be back in the city.

bullet points:

- air map
- intro to friends and Landrover
- Friday and packing and late arrival in Sudbury
- destination
- photos
- found boat #1
- Provincial park, beach and boat
- Off roading
- Found boat #2
- Bugs
- Journey home-Chapleau not Timmins
- Ride through Forest fires and provincial parks
- Home and reflection
