<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Problems and Solutions in Applied Statistics (2nd ed) - 5&nbsp; Two-sample inference</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./power.html" rel="next">
<link href="./one-sample-inference.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<link href="site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="site_libs/pagedtable-1.1/js/pagedtable.js"></script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./two-sample-inference.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Two-sample inference</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Problems and Solutions in Applied Statistics (2nd ed)</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./getting_used.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Getting used to R and R Studio</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./reading-in.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Reading in data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-summaries.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data exploration</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./one-sample-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">One-sample inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./two-sample-inference.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Two-sample inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./power.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Power and sample size</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sign.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">The sign test</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mood-median.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Mood median test</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./matched-pairs-sign.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Matched pairs t and sign test</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./normal-quantile.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Normal quantile plots</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./analysis-of-variance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Analysis of variance</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./reports.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Writing reports</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./coding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Learning to code</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dandruff.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Treating dandruff</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tidying-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Tidying data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./simple-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Simple regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multiple-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Multiple regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression-categorical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Regression with categorical variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dates-and-times.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Dates and times</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Functions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./vector-matrix.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Vector and matrix algebra</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bootstrap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">The Bootstrap</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stan.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Bayesian Statistics with Stan</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistic-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Logistic regression</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#children-and-electronic-devices" id="toc-children-and-electronic-devices" class="nav-link active" data-scroll-target="#children-and-electronic-devices"><span class="header-section-number">5.1</span> Children and electronic devices</a></li>
  <li><a href="#parking-close-to-the-curb" id="toc-parking-close-to-the-curb" class="nav-link" data-scroll-target="#parking-close-to-the-curb"><span class="header-section-number">5.2</span> Parking close to the curb</a></li>
  <li><a href="#bell-peppers-and-too-much-water" id="toc-bell-peppers-and-too-much-water" class="nav-link" data-scroll-target="#bell-peppers-and-too-much-water"><span class="header-section-number">5.3</span> Bell peppers and too much water</a></li>
  <li><a href="#exercise-and-anxiety-and-bullying-mice" id="toc-exercise-and-anxiety-and-bullying-mice" class="nav-link" data-scroll-target="#exercise-and-anxiety-and-bullying-mice"><span class="header-section-number">5.4</span> Exercise and anxiety and bullying mice</a></li>
  <li><a href="#diet-and-growth-in-boys" id="toc-diet-and-growth-in-boys" class="nav-link" data-scroll-target="#diet-and-growth-in-boys"><span class="header-section-number">5.5</span> Diet and growth in boys</a></li>
  <li><a href="#handspans-of-males-and-females" id="toc-handspans-of-males-and-females" class="nav-link" data-scroll-target="#handspans-of-males-and-females"><span class="header-section-number">5.6</span> Handspans of males and females</a></li>
  <li><a href="#the-anchoring-effect-australia-vs-us" id="toc-the-anchoring-effect-australia-vs-us" class="nav-link" data-scroll-target="#the-anchoring-effect-australia-vs-us"><span class="header-section-number">5.7</span> The anchoring effect: Australia vs US</a></li>
  <li><a href="#children-and-electronic-devices-1" id="toc-children-and-electronic-devices-1" class="nav-link" data-scroll-target="#children-and-electronic-devices-1"><span class="header-section-number">5.8</span> Children and electronic devices</a></li>
  <li><a href="#parking-close-to-the-curb-1" id="toc-parking-close-to-the-curb-1" class="nav-link" data-scroll-target="#parking-close-to-the-curb-1"><span class="header-section-number">5.9</span> Parking close to the curb</a></li>
  <li><a href="#bell-peppers-and-too-much-water-1" id="toc-bell-peppers-and-too-much-water-1" class="nav-link" data-scroll-target="#bell-peppers-and-too-much-water-1"><span class="header-section-number">5.10</span> Bell peppers and too much water</a></li>
  <li><a href="#exercise-and-anxiety-and-bullying-mice-1" id="toc-exercise-and-anxiety-and-bullying-mice-1" class="nav-link" data-scroll-target="#exercise-and-anxiety-and-bullying-mice-1"><span class="header-section-number">5.11</span> Exercise and anxiety and bullying mice</a></li>
  <li><a href="#diet-and-growth-in-boys-1" id="toc-diet-and-growth-in-boys-1" class="nav-link" data-scroll-target="#diet-and-growth-in-boys-1"><span class="header-section-number">5.12</span> Diet and growth in boys</a></li>
  <li><a href="#handspans-of-males-and-females-1" id="toc-handspans-of-males-and-females-1" class="nav-link" data-scroll-target="#handspans-of-males-and-females-1"><span class="header-section-number">5.13</span> Handspans of males and females</a></li>
  <li><a href="#the-anchoring-effect-australia-vs-us-1" id="toc-the-anchoring-effect-australia-vs-us-1" class="nav-link" data-scroll-target="#the-anchoring-effect-australia-vs-us-1"><span class="header-section-number">5.14</span> The anchoring effect: Australia vs US</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Two-sample inference</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="children-and-electronic-devices" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="children-and-electronic-devices"><span class="header-section-number">5.1</span> Children and electronic devices</h2>
<p>Do children (aged 8–17) spend more time on electronic devices now than they did 10 years ago? Samples of 15 children aged 8–17 were taken in each of two years, 1999 and 2009, and the children (with their parents’ help) were asked to keep a diary of the number of hours they spent using electronic devices on a certain day. The data are in the file <a href="http://ritsokiguess.site/datafiles/pluggedin.txt">http://ritsokiguess.site/datafiles/pluggedin.txt</a>.</p>
<ol type="a">
<li><p>Read in the data and verify that you have 30 rows of data from two different years.</p></li>
<li><p>Draw side-by-side boxplots of the number of hours for each year. <code>year</code> is a numeric variable that we want to treat as a factor, so we need to <em>make</em> it into a factor.</p></li>
<li><p>Test whether the mean number of hours has <em>increased</em> since 1999. Which test did R do?</p></li>
<li><p>Obtain a 99% confidence interval for the difference in means.</p></li>
</ol>
</section>
<section id="parking-close-to-the-curb" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="parking-close-to-the-curb"><span class="header-section-number">5.2</span> Parking close to the curb</h2>
<p>In 2009, the Toronto Star commissioned a survey to address the issue of who is better at parking a car: men or women. The researchers recorded 93 drivers who were parallel-parking their car in downtown Toronto, and for each driver, recorded the distance between the car and the curb, in inches, when the driver was finished parking their car. The data are in an Excel spreadsheet, <a href="http://ritsokiguess.site/datafiles/parking.xlsx">link</a>. Click on the link. The data will probably download automatically. Check the folder on your computer where things get downloaded.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> If the spreadsheet is just displayed and not downloaded, save it somewhere on your computer.</p>
<ol type="a">
<li><p>There are two sheets in this spreadsheet workbook. They are of the same data in two different formats. Take a look at Sheet 1 and Sheet 2. Describe the format of the data in each case. Which will be the most suitable data layout, bearing in mind that one of the first things we do is to make side-by-side boxplots of parking distances for males and females? Explain briefly.</p></li>
<li><p>Read your preferred sheet directly into R, <em>without</em> using a <code>.csv</code> file. (There is a clue in the lecture notes, in the section about reading in files.) If you get stuck, make a <code>.csv</code> file and read that in.</p></li>
<li><p>Obtain side-by-side boxplots of parking distances for males and females. Does one gender seem to be better at parking than the other? Explain briefly.</p></li>
<li><p>Explain briefly why this is two independent samples rather than matched pairs.</p></li>
<li><p>Run a suitable <span class="math inline">\(t\)</span>-test for comparing parking distances for males and females. What do you conclude, in the context of the data?</p></li>
<li><p>Why might you have some doubts about the <span class="math inline">\(t\)</span>-test that you just did? Explain briefly.</p></li>
<li><p>The Toronto Star in its report said that females are more accurate at parking their cars. Why do you think they concluded that, and do you think they were right to do so? Explain briefly.</p></li>
</ol>
</section>
<section id="bell-peppers-and-too-much-water" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="bell-peppers-and-too-much-water"><span class="header-section-number">5.3</span> Bell peppers and too much water</h2>
<p>A pathogen called <em>Phytophthora capsici</em> causes bell peppers to wilt and die. It is thought that too much water aids in the spread of the pathogen. Two fields are under study, labelled <code>a</code> and <code>b</code>. The first step in the research project is to compare the mean soil water content of the two fields. There is a suspicion that field <code>a</code> will have a higher water content than field <code>b</code>. The data are in the file <a href="http://ritsokiguess.site/datafiles/bellpepper.csv">link</a>.</p>
<ol type="a">
<li><p>Read the file in using <code>read_csv</code>, and list the resulting data frame.</p></li>
<li><p>Make side-by-side boxplots of the water content values for the two fields. How do the fields seem to compare?</p></li>
<li><p>Do a two-sample <span class="math inline">\(t\)</span>-test to test whether there is evidence that the mean water content in field <code>a</code> is higher than that of field <code>b</code>. What do you conclude? Explain briefly. (You’ll need to figure out a way of doing a one-sided test, or how to adapt the results from a two-sided test.)</p></li>
<li><p>Is the result of your test consistent with the boxplot, or not? Explain briefly.</p></li>
</ol>
</section>
<section id="exercise-and-anxiety-and-bullying-mice" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="exercise-and-anxiety-and-bullying-mice"><span class="header-section-number">5.4</span> Exercise and anxiety and bullying mice</h2>
<p>Does exercise help to reduce anxiety? To assess this, some researchers randomly assigned mice to either an enriched environment where there was an exercise wheel available, or a standard environment with no exercise options. After three weeks in the specified environment, for five minutes a day for two weeks, the mice were each exposed to a “mouse bully” — a mouse who was very strong, aggressive, and territorial. One measure of mouse anxiety is amount of time hiding in a dark compartment, with mice who are more anxious spending more time in darkness. The amount of time spent in darkness is recorded for each of the mice.</p>
<p>The data can be found at <a href="http://ritsokiguess.site/datafiles/stressedmice.txt">link</a>.</p>
<ol type="a">
<li><p>Read the data into R, and display your data frame. Count the number of mice in each group.</p></li>
<li><p>Draw side-by-side boxplots of time spent in darkness for each group of mice.</p></li>
<li><p>Do the boxplots support the hypothesis about exercise and anxiety? Explain briefly.</p></li>
<li><p>Carry out a <span class="math inline">\(t\)</span>-test for comparing the mean time spent in darkness for the mice in the two groups. Think carefully about the details of the <span class="math inline">\(t\)</span>-test (and what you need evidence in favour of).</p></li>
<li><p>What do you conclude, in terms of anxiety and exercise (at least for mice)? Explain briefly.</p></li>
<li><p>Does anything in the previous parts suggest any problems with the analysis you just did? Explain briefly.</p></li>
</ol>
</section>
<section id="diet-and-growth-in-boys" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="diet-and-growth-in-boys"><span class="header-section-number">5.5</span> Diet and growth in boys</h2>
<p>A dietician is studying the effect of different diets on children’s growth. In part of the study, the dietician is investigating two religious sects, labelled <code>a</code> and <code>b</code> in our data set. Both sects are vegetarian; the difference between them is that people in Sect A only eat vegetables from below the ground, and Sect B only eats vegetables from above the ground. The height and weight of the boys<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> are measured at regular intervals. The data in <a href="http://ritsokiguess.site/datafiles/kids-diet.txt">link</a> are the heights of the boys at age 12.</p>
<ol type="a">
<li><p>Read in the data and find out how many observations you have and which variables.</p></li>
<li><p>Obtain side-by-side boxplots of the heights for boys from each sect. Does it look as if the heights of the boys in each sect are different? Comment briefly.</p></li>
<li><p>Looking at your boxplots, do you see any problems with doing a two-sample <span class="math inline">\(t\)</span>-test? Explain briefly.</p></li>
<li><p>Run a <span class="math inline">\(t\)</span>-test to determine whether the mean heights differ significantly. What do you conclude? Explain briefly. (Run the <span class="math inline">\(t\)</span>-test even if your previous work suggests that it is not the right thing to do.)</p></li>
</ol>
</section>
<section id="handspans-of-males-and-females" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="handspans-of-males-and-females"><span class="header-section-number">5.6</span> Handspans of males and females</h2>
<p>Take your right hand, and stretch the fingers out as far as you can. The distance between the tip of your thumb and the tip of your little (pinky) finger is your handspan. The students in a Statistics class at Penn State measured their handspans and also whether they identified as male or female. The data are at <a href="http://ritsokiguess.site/datafiles/handspan.txt">http://ritsokiguess.site/datafiles/handspan.txt</a>, with handspans measured in inches. Thinking of these as a random sample of all possible students, is it true that males have a larger mean handspan than females? This is what we will explore.</p>
<ol type="a">
<li><p>Read in and display (some of) the data.</p></li>
<li><p>Make a suitable graph of the two columns.</p></li>
<li><p>Run a suitable two-sample <span class="math inline">\(t\)</span>-test to address the question of interest. What do you conclude, in the context of the data?</p></li>
<li><p>Obtain a 90% confidence interval for the difference in mean handspan between males and females. Do you need to run any more code? Explain briefly.</p></li>
<li><p>Explain briefly why you might have some concerns about the validity of the <span class="math inline">\(t\)</span>-tests you ran in this question. Or, if you don’t have any concerns, explain briefly why that is.</p></li>
</ol>
</section>
<section id="the-anchoring-effect-australia-vs-us" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="the-anchoring-effect-australia-vs-us"><span class="header-section-number">5.7</span> The anchoring effect: Australia vs US</h2>
<p>Two groups of students (in a class at a American university) were asked what they thought the population of Canada was. (The correct answer at the time was just over 30 million.) Some of the students, before having to answer this, were told that the population of the United States was about 270 million. The other students in the class were told that the population of Australia was about 18 million. The data are in <a href="http://ritsokiguess.site/datafiles/anchoring.csv">http://ritsokiguess.site/datafiles/anchoring.csv</a>. The first column contains the country whose population the student was told, and the second contains the student’s guess at the population of Canada.</p>
<p>You might wonder how being told the population of an unrelated country would have any impact on a student’s guess at the population of Canada. Psychology says it does: it’s called the <em>anchoring effect</em>, and the idea is that the number mentioned first acts as an “anchor”: a person’s guess will be closer to the anchor than it would have been otherwise. In this case, that would mean that the guesses for the students given the US as an anchor will be higher than for the students given Australia as an anchor. We are interested in seeing whether there is evidence for that here.</p>
<ol type="a">
<li><p>Read in and display (some of) the data.</p></li>
<li><p>Draw a suitable graph of these data.</p></li>
<li><p>Explain briefly why a Welch <span class="math inline">\(t\)</span>-test would be better than a pooled <span class="math inline">\(t\)</span>-test in this case.</p></li>
<li><p>Run a suitable Welch <span class="math inline">\(t\)</span>-test and display the output.</p></li>
<li><p>What do you conclude from your test, in the context of the data?</p></li>
</ol>
<p>My solutions follow:</p>
</section>
<section id="children-and-electronic-devices-1" class="level2" data-number="5.8">
<h2 data-number="5.8" class="anchored" data-anchor-id="children-and-electronic-devices-1"><span class="header-section-number">5.8</span> Children and electronic devices</h2>
<p>Do children (aged 8–17) spend more time on electronic devices now than they did 10 years ago? Samples of 15 children aged 8–17 were taken in each of two years, 1999 and 2009, and the children (with their parents’ help) were asked to keep a diary of the number of hours they spent using electronic devices on a certain day. The data are in the file <a href="http://ritsokiguess.site/datafiles/pluggedin.txt">http://ritsokiguess.site/datafiles/pluggedin.txt</a>.</p>
<ol type="a">
<li>Read in the data and verify that you have 30 rows of data from two different years.</li>
</ol>
<p>Solution</p>
<p>I see this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>myurl<span class="ot">=</span><span class="st">"http://ritsokiguess.site/datafiles/pluggedin.txt"</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>plugged<span class="ot">=</span><span class="fu">read_delim</span>(myurl,<span class="st">" "</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 30 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: " "
dbl (2): year, hours

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>plugged</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["year"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["hours"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"1999","2":"4"},{"1":"1999","2":"5"},{"1":"1999","2":"7"},{"1":"1999","2":"7"},{"1":"1999","2":"5"},{"1":"1999","2":"7"},{"1":"1999","2":"5"},{"1":"1999","2":"6"},{"1":"1999","2":"5"},{"1":"1999","2":"6"},{"1":"1999","2":"7"},{"1":"1999","2":"8"},{"1":"1999","2":"5"},{"1":"1999","2":"6"},{"1":"1999","2":"6"},{"1":"2009","2":"5"},{"1":"2009","2":"9"},{"1":"2009","2":"5"},{"1":"2009","2":"8"},{"1":"2009","2":"7"},{"1":"2009","2":"6"},{"1":"2009","2":"7"},{"1":"2009","2":"9"},{"1":"2009","2":"7"},{"1":"2009","2":"9"},{"1":"2009","2":"6"},{"1":"2009","2":"9"},{"1":"2009","2":"10"},{"1":"2009","2":"9"},{"1":"2009","2":"8"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>I see only the first ten rows (with an indication that there are 20 more, so 30 altogether). In your notebook, it’ll look a bit different: again, you’ll see the first 10 rows, but you’ll see exactly how many rows and columns there are, and there will be buttons “Next” and “Previous” to see earlier and later rows, and a little right-arrow to see more columns to the right (to which is added a little left-arrow if there are previous columns to scroll back to). If you want to check for yourself that there are 30 rows, you can click Next a couple of times to get down to row 30, and then see that the Next button cannot be clicked again, and therefore that 30 rows is how many there are.</p>
<p>Or, you can summarize the years by counting how many there are of each:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>plugged <span class="sc">%&gt;%</span> <span class="fu">count</span>(year)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["year"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["n"],"name":[2],"type":["int"],"align":["right"]}],"data":[{"1":"1999","2":"15"},{"1":"2009","2":"15"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>or the more verbose form of the same thing:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>plugged <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(year) <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">rows=</span><span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["year"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["rows"],"name":[2],"type":["int"],"align":["right"]}],"data":[{"1":"1999","2":"15"},{"1":"2009","2":"15"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>Any of those says that it looks good. 30 rows, 1999 and 2009, 15 measurements for each.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" type="a">
<li>Draw side-by-side boxplots of the number of hours for each year. <code>year</code> is a numeric variable that we want to treat as a factor, so we need to <em>make</em> it into a factor.</li>
</ol>
<p>Solution</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plugged,<span class="fu">aes</span>(<span class="at">x=</span><span class="fu">factor</span>(year),<span class="at">y=</span>hours))<span class="sc">+</span><span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="two-sample-inference_files/figure-html/waehingen-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The <code>fct_inorder</code> trick will also work, since the years are in the data in the order we want them to be displayed. (An option in case you have seen this.)</p>
<p>The median for 2009 is noticeably higher, and there is no skewness or outliers worth worrying about.</p>
<p>The measurements for the two years have a very similar spread, so there would be no problem running the pooled test here.</p>
<p>You might be bothered by the <code>factor(year)</code> on the <span class="math inline">\(x\)</span>-axis. To get around that, you can define year-as-factor <em>first</em>, using <code>mutate</code>, then feed your new column into the boxplot. That goes like this. There is a wrinkle that I explain afterwards:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>plugged <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">the_year=</span><span class="fu">factor</span>(year)) <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>the_year, <span class="at">y=</span>hours))<span class="sc">+</span><span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="two-sample-inference_files/figure-html/bisslerin-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>You could even redefine <code>year</code> to be the factor version of itself (if you don’t need the year-as-number anywhere else). The wrinkle I mentioned above is that in the <code>ggplot</code> you <em>do not</em> name the data frame first; the data frame used is the (nameless) data frame that came out of the previous step, not <code>plugged</code> but <code>plugged</code> with a new column <code>the_year</code>.</p>
<p>Note how the <span class="math inline">\(x\)</span>-axis now has the name of the new variable.</p>
<p>If you forget to make <code>year</code> into a factor, this happens:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plugged, <span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> hours)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Continuous x aesthetic
ℹ did you forget `aes(group = ...)`?</code></pre>
</div>
<div class="cell-output-display">
<p><img src="two-sample-inference_files/figure-html/luotter-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>You get <em>one</em> boxplot, for all the hours, without distinguishing by year, and a warning message that tries (and fails) to read our mind: yes, we have a continuous, quantitative <code>x</code>, but <code>geom_boxplot</code> doesn’t take a <code>group</code>. Or maybe it does. Try it and see:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plugged,<span class="fu">aes</span>(<span class="at">x =</span> year, <span class="at">y =</span> hours, <span class="at">group =</span> year)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="two-sample-inference_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The <span class="math inline">\(x\)</span>-axis treats the year as a number, which looks a little odd, but adding a <code>group</code> correctly gets us two boxplots side by side, so this is also a good way to do it. So maybe the error message <em>did</em> read our mind after all.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" type="a">
<li>Test whether the mean number of hours has <em>increased</em> since 1999. Which test did R do?</li>
</ol>
<p>Solution</p>
<p>The hard part to remember is how you specify a one-sided test in R; it’s <code>alternative="less"</code> (rather than “greater”) because 1999 is “before” 2009:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(hours<span class="sc">~</span>year,<span class="at">data=</span>plugged,<span class="at">alternative=</span><span class="st">"less"</span>)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  hours by year
t = -3.3323, df = 24.861, p-value = 0.001348
alternative hypothesis: true difference in means between group 1999 and group 2009 is less than 0
95 percent confidence interval:
       -Inf -0.8121415
sample estimates:
mean in group 1999 mean in group 2009 
          5.933333           7.600000 </code></pre>
</div>
</div>
<p>The P-value is 0.0013. R does the Welch-Satterthwaite test by default (the unequal-variances one). Since we didn’t change that, that’s what we got. (The pooled test is below.)</p>
<p>This is the cleanest way to do it, because this version of <code>t.test</code>, with a “model formula” (the thing with the squiggle) allows a <code>data=</code> to say which data frame to get things from. The other ways, using (for example) <code>with</code>, also work:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(plugged,<span class="fu">t.test</span>(hours<span class="sc">~</span>year,<span class="at">alternative=</span><span class="st">"less"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  hours by year
t = -3.3323, df = 24.861, p-value = 0.001348
alternative hypothesis: true difference in means between group 1999 and group 2009 is less than 0
95 percent confidence interval:
       -Inf -0.8121415
sample estimates:
mean in group 1999 mean in group 2009 
          5.933333           7.600000 </code></pre>
</div>
</div>
<p>This also works, but is <em>ugly</em>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(plugged<span class="sc">$</span>hours<span class="sc">~</span>plugged<span class="sc">$</span>year,<span class="at">alternative=</span><span class="st">"less"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  plugged$hours by plugged$year
t = -3.3323, df = 24.861, p-value = 0.001348
alternative hypothesis: true difference in means between group 1999 and group 2009 is less than 0
95 percent confidence interval:
       -Inf -0.8121415
sample estimates:
mean in group 1999 mean in group 2009 
          5.933333           7.600000 </code></pre>
</div>
</div>
<p>Ugly because you’ve just typed the name of the data frame and the dollar sign <em>twice</em> for no reason. As a general principle, if you as a programmer are repeating yourself, you should stop and ask yourself how you can avoid the repeat.</p>
<p>If you want the pooled test in R, you have to ask for it:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(hours<span class="sc">~</span>year, <span class="at">alternative =</span> <span class="st">"less"</span>, <span class="at">data =</span> plugged, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)    </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  hours by year
t = -3.3323, df = 28, p-value = 0.001216
alternative hypothesis: true difference in means between group 1999 and group 2009 is less than 0
95 percent confidence interval:
       -Inf -0.8158312
sample estimates:
mean in group 1999 mean in group 2009 
          5.933333           7.600000 </code></pre>
</div>
</div>
<p>As is often the case, the P-values for the pooled and Welch-Satterthwaite tests are very similar, so from that point of view it doesn’t matter much which one you use. If you remember back to the boxplots, the number of hours had about the same spread for the two years, so if you used the pooled test instead of the Welch-Satterthwaite test, that would have been just fine.</p>
<p>There is a school of thought that says we should learn the Welch-Satterthwaite test and use that always. This is because W-S (i) works when the populations from which the groups are sampled have different SDs and (ii) is pretty good even when those SDs are the same.</p>
<p>The pooled test can go badly wrong if the groups have very different SDs. The story is this: if the larger sample is from the population with the larger SD, the probability of a type I error will be smaller than <span class="math inline">\(\alpha\)</span>, and if the larger sample is from the population with the <em>smaller</em> SD, the probability of a type I error will be larger than <span class="math inline">\(\alpha\)</span>. This is why you see S-W in STAB22. You see the pooled test in STAB57 because the logic of its derivation is so much clearer, not because it’s really the better test in practice. The theory says that if your data are normal in both groups with the same variance, then the pooled test is best, but it says <em>nothing</em> about the quality of the pooled test if any of that goes wrong. The usual approach to assessing things like this is via simulation, as we do for estimating power (later): generate some random data eg. from normal distributions with the same means, SDs 10 and 20 and sample sizes 15 and 30, run the pooled <span class="math inline">\(t\)</span>-test, see if you reject, then repeat lots of times and see whether you reject about 5% of the time. Then do the same thing again with the sample sizes switched around. Or, do the same thing with Welch-Satterthwaite.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" type="a">
<li>Obtain a 99% confidence interval for the difference in means.</li>
</ol>
<p>Solution</p>
<p>Take off the thing that made it one-sided, and put in a thing that gets the right CI:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(hours<span class="sc">~</span>year,<span class="at">data=</span>plugged,<span class="at">conf.level=</span><span class="fl">0.99</span>)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  hours by year
t = -3.3323, df = 24.861, p-value = 0.002696
alternative hypothesis: true difference in means between group 1999 and group 2009 is not equal to 0
99 percent confidence interval:
 -3.0614628 -0.2718705
sample estimates:
mean in group 1999 mean in group 2009 
          5.933333           7.600000 </code></pre>
</div>
</div>
<p><span class="math inline">\(-3.06\)</span> to <span class="math inline">\(-0.27\)</span>. The interval contains only negative values, which is consistent with our having rejected a null hypothesis of no difference in means.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</section>
<section id="parking-close-to-the-curb-1" class="level2" data-number="5.9">
<h2 data-number="5.9" class="anchored" data-anchor-id="parking-close-to-the-curb-1"><span class="header-section-number">5.9</span> Parking close to the curb</h2>
<p>In 2009, the Toronto Star commissioned a survey to address the issue of who is better at parking a car: men or women. The researchers recorded 93 drivers who were parallel-parking their car in downtown Toronto, and for each driver, recorded the distance between the car and the curb, in inches, when the driver was finished parking their car. The data are in an Excel spreadsheet, <a href="http://ritsokiguess.site/datafiles/parking.xlsx">link</a>. Click on the link. The data will probably download automatically. Check the folder on your computer where things get downloaded.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> If the spreadsheet is just displayed and not downloaded, save it somewhere on your computer.</p>
<ol type="a">
<li>There are two sheets in this spreadsheet workbook. They are of the same data in two different formats. Take a look at Sheet 1 and Sheet 2. Describe the format of the data in each case. Which will be the most suitable data layout, bearing in mind that one of the first things we do is to make side-by-side boxplots of parking distances for males and females? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>The data in Sheet 1 has one column of parking distances for males, and another for females. This is often how you see data of this sort laid out. Sheet 2 has <em>one</em> column of parking distances, all combined together, and a second column indicating the gender of the driver whose distance is in the first column. If you look back at the kind of data we’ve used to make side-by-side boxplots, it’s always been in the format of Sheet 2: one column containing all the values of the variable we’re interested in, with a second column indicating which group each observation belongs to (“group” here being “gender of driver”). So we need to use the data in Sheet 2, because the data in Sheet 1 are not easy to handle with R. The layout of Sheet 2 is the way R likes to do most things: so-called “long format” with a lot of rows and not many columns. This is true for descriptive stuff: side-by-side boxplots or histograms or means by group, as well as modelling such as (here) a two-sample <span class="math inline">\(t\)</span>-test, or (in other circumstances, as with several groups) a one-way analysis of variance. Hadley Wickham, the guy behind the <code>tidyverse</code>, likes to talk about “tidy data” (like Sheet 2), with each column containing a variable, and “untidy data” (like Sheet 1), where the two columns are the same thing (distances), but under different circumstances (genders). As we’ll see later, it is possible to convert from one format to the other. Usually you want to make untidy data tidy (the function for this is called <code>pivot_longer</code>).</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" type="a">
<li>Read your preferred sheet directly into R, <em>without</em> using a <code>.csv</code> file. (There is a clue in the lecture notes, in the section about reading in files.) If you get stuck, make a <code>.csv</code> file and read that in.</li>
</ol>
<p>Solution</p>
<p>The direct way is to use the package <code>readxl</code>. This has a <code>read_excel</code> that works the same way as any of the other <code>read_</code> functions. You’ll have to make sure that you read in sheet 2, since that’s the one you want. There is some setup first. There are a couple of ways you can do that:</p>
<ul>
<li><p>Download the spreadsheet to your computer, and upload it to your project on R Studio Cloud (or, if you are running R Studio on your computer, use something like <code>file.choose</code> to get the file from wherever it got downloaded to).</p></li>
<li><p>Use the function <code>download.file</code> to get the file from the URL and store it in your project folder directly. This also works in R Studio Cloud, and completely by-passes the download-upload steps that you would have to do otherwise. (I am grateful to Rose Gao for this idea.) Here is how you can use <code>download.file</code> here:</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>my_url <span class="ot">&lt;-</span> <span class="st">"http://ritsokiguess.site/datafiles/parking.xlsx"</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>local <span class="ot">&lt;-</span> <span class="st">"parking.xlsx"</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">download.file</span>(my_url, local, <span class="at">mode =</span> <span class="st">"wb"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>When you’ve gotten the spreadsheet into your project folder via one of those two ways, you go ahead and do this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>parking <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"parking.xlsx"</span>, <span class="at">sheet =</span> <span class="dv">2</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>parking</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["distance"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["gender"],"name":[2],"type":["chr"],"align":["left"]}],"data":[{"1":"0.5","2":"male"},{"1":"1.0","2":"male"},{"1":"1.5","2":"male"},{"1":"1.5","2":"male"},{"1":"1.5","2":"male"},{"1":"3.0","2":"male"},{"1":"3.5","2":"male"},{"1":"5.0","2":"male"},{"1":"6.0","2":"male"},{"1":"6.0","2":"male"},{"1":"7.0","2":"male"},{"1":"7.0","2":"male"},{"1":"7.0","2":"male"},{"1":"7.0","2":"male"},{"1":"7.0","2":"male"},{"1":"8.0","2":"male"},{"1":"8.0","2":"male"},{"1":"8.5","2":"male"},{"1":"8.5","2":"male"},{"1":"9.0","2":"male"},{"1":"9.0","2":"male"},{"1":"9.5","2":"male"},{"1":"10.0","2":"male"},{"1":"10.0","2":"male"},{"1":"11.0","2":"male"},{"1":"12.0","2":"male"},{"1":"12.0","2":"male"},{"1":"12.0","2":"male"},{"1":"13.0","2":"male"},{"1":"14.0","2":"male"},{"1":"14.0","2":"male"},{"1":"14.0","2":"male"},{"1":"14.0","2":"male"},{"1":"14.0","2":"male"},{"1":"14.0","2":"male"},{"1":"14.5","2":"male"},{"1":"14.5","2":"male"},{"1":"14.5","2":"male"},{"1":"17.0","2":"male"},{"1":"18.0","2":"male"},{"1":"18.0","2":"male"},{"1":"19.0","2":"male"},{"1":"19.0","2":"male"},{"1":"20.0","2":"male"},{"1":"21.0","2":"male"},{"1":"48.0","2":"male"},{"1":"2.0","2":"female"},{"1":"2.5","2":"female"},{"1":"3.0","2":"female"},{"1":"3.0","2":"female"},{"1":"3.0","2":"female"},{"1":"3.0","2":"female"},{"1":"3.0","2":"female"},{"1":"4.0","2":"female"},{"1":"4.5","2":"female"},{"1":"4.5","2":"female"},{"1":"4.5","2":"female"},{"1":"5.0","2":"female"},{"1":"5.0","2":"female"},{"1":"5.0","2":"female"},{"1":"6.0","2":"female"},{"1":"6.0","2":"female"},{"1":"7.0","2":"female"},{"1":"7.0","2":"female"},{"1":"7.0","2":"female"},{"1":"7.0","2":"female"},{"1":"7.5","2":"female"},{"1":"8.0","2":"female"},{"1":"8.5","2":"female"},{"1":"8.5","2":"female"},{"1":"9.0","2":"female"},{"1":"9.0","2":"female"},{"1":"9.0","2":"female"},{"1":"9.0","2":"female"},{"1":"10.0","2":"female"},{"1":"10.0","2":"female"},{"1":"12.0","2":"female"},{"1":"12.0","2":"female"},{"1":"12.0","2":"female"},{"1":"12.0","2":"female"},{"1":"12.5","2":"female"},{"1":"13.0","2":"female"},{"1":"13.0","2":"female"},{"1":"13.0","2":"female"},{"1":"14.0","2":"female"},{"1":"14.0","2":"female"},{"1":"14.0","2":"female"},{"1":"15.5","2":"female"},{"1":"16.0","2":"female"},{"1":"18.0","2":"female"},{"1":"20.0","2":"female"},{"1":"21.0","2":"female"},{"1":"25.0","2":"female"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>You have to do it this way, using the version of the spreadsheet on your computer, since <code>read_excel</code> won’t take a URL, or if it does, I can’t make it work.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> I put the spreadsheet in R Studio’s current folder, so I could read it in by name, or you can do the <code>f &lt;- file.choose()</code> thing, find it, then read it in. The <code>sheet=</code> thing can take either a number (as here: the second sheet in the workbook), or a name (whatever name the sheet has on its tab in the workbook).</p>
<p>Extra: Rose actually came up with a better idea, which I will show you and explain:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>tf <span class="ot">&lt;-</span> <span class="fu">tempfile</span>()</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">download.file</span>(my_url, tf, <span class="at">mode =</span> <span class="st">"wb"</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(tf, <span class="at">sheet =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>What <code>tempfile()</code> does is to create a temporary file to hold the spreadsheet that you are about to download. After downloading the spreadsheet to the temporary file, you then use <code>read_excel</code> to read <em>from the temporary file</em> into the data frame.</p>
<p>The advantage of this approach is that the temporary file disappears as soon as you close R, and so you don’t have a copy of the spreadsheet lying around that you don’t need (once you have created the dataframe that I called <code>parking</code>, anyway).</p>
<p>If you are wondering about that <code>mode</code> thing on <code>download.file</code>: files are of two different types, “text” (like the text of an email, that you can open and look at in something like Notepad), and “binary” that you can’t look at directly, but for which you need special software like Word or Excel to decode it for you.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a><br>
The first character in <code>mode</code> is either <code>w</code> for “write a new file”, which is what we want here, or <code>a</code> for “append”, which would mean adding to the end of a file that already exists. Thus <code>mode="wb"</code> means “create a new binary file”. End of Extra.</p>
<p>If you can’t make any of this work, then do it in two steps: save the appropriate sheet as a <code>.csv</code> file, and then read the <code>.csv</code> file using <code>read_csv</code>. If you experiment, you’ll find that saving a spreadsheet workbook as <code>.csv</code> only saves the sheet you’re looking at, so make sure you are looking at sheet 2 before you Save As <code>.csv</code>. I did that, and called my saved <code>.csv</code> <code>parking2.csv</code> (because it was from sheet 2, but you can use any name you like). Then I read this into R thus:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>parking2 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"parking2.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 93 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): gender
dbl (1): distance

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>parking2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["distance"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["gender"],"name":[2],"type":["chr"],"align":["left"]}],"data":[{"1":"0.5","2":"male"},{"1":"1.0","2":"male"},{"1":"1.5","2":"male"},{"1":"1.5","2":"male"},{"1":"1.5","2":"male"},{"1":"3.0","2":"male"},{"1":"3.5","2":"male"},{"1":"5.0","2":"male"},{"1":"6.0","2":"male"},{"1":"6.0","2":"male"},{"1":"7.0","2":"male"},{"1":"7.0","2":"male"},{"1":"7.0","2":"male"},{"1":"7.0","2":"male"},{"1":"7.0","2":"male"},{"1":"8.0","2":"male"},{"1":"8.0","2":"male"},{"1":"8.5","2":"male"},{"1":"8.5","2":"male"},{"1":"9.0","2":"male"},{"1":"9.0","2":"male"},{"1":"9.5","2":"male"},{"1":"10.0","2":"male"},{"1":"10.0","2":"male"},{"1":"11.0","2":"male"},{"1":"12.0","2":"male"},{"1":"12.0","2":"male"},{"1":"12.0","2":"male"},{"1":"13.0","2":"male"},{"1":"14.0","2":"male"},{"1":"14.0","2":"male"},{"1":"14.0","2":"male"},{"1":"14.0","2":"male"},{"1":"14.0","2":"male"},{"1":"14.0","2":"male"},{"1":"14.5","2":"male"},{"1":"14.5","2":"male"},{"1":"14.5","2":"male"},{"1":"17.0","2":"male"},{"1":"18.0","2":"male"},{"1":"18.0","2":"male"},{"1":"19.0","2":"male"},{"1":"19.0","2":"male"},{"1":"20.0","2":"male"},{"1":"21.0","2":"male"},{"1":"48.0","2":"male"},{"1":"2.0","2":"female"},{"1":"2.5","2":"female"},{"1":"3.0","2":"female"},{"1":"3.0","2":"female"},{"1":"3.0","2":"female"},{"1":"3.0","2":"female"},{"1":"3.0","2":"female"},{"1":"4.0","2":"female"},{"1":"4.5","2":"female"},{"1":"4.5","2":"female"},{"1":"4.5","2":"female"},{"1":"5.0","2":"female"},{"1":"5.0","2":"female"},{"1":"5.0","2":"female"},{"1":"6.0","2":"female"},{"1":"6.0","2":"female"},{"1":"7.0","2":"female"},{"1":"7.0","2":"female"},{"1":"7.0","2":"female"},{"1":"7.0","2":"female"},{"1":"7.5","2":"female"},{"1":"8.0","2":"female"},{"1":"8.5","2":"female"},{"1":"8.5","2":"female"},{"1":"9.0","2":"female"},{"1":"9.0","2":"female"},{"1":"9.0","2":"female"},{"1":"9.0","2":"female"},{"1":"10.0","2":"female"},{"1":"10.0","2":"female"},{"1":"12.0","2":"female"},{"1":"12.0","2":"female"},{"1":"12.0","2":"female"},{"1":"12.0","2":"female"},{"1":"12.5","2":"female"},{"1":"13.0","2":"female"},{"1":"13.0","2":"female"},{"1":"13.0","2":"female"},{"1":"14.0","2":"female"},{"1":"14.0","2":"female"},{"1":"14.0","2":"female"},{"1":"15.5","2":"female"},{"1":"16.0","2":"female"},{"1":"18.0","2":"female"},{"1":"20.0","2":"female"},{"1":"21.0","2":"female"},{"1":"25.0","2":"female"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>The read-in data frame <code>parking</code> has 93 rows (<span class="math inline">\(47+46=93\)</span> drivers) and two columns: the distance from the curb that the driver ended up at, and the gender of the driver. This is as the spreadsheet Sheet 2 was, and the first few distances match the ones in the spreadsheet.</p>
<p>If I were grading this, you’d get some credit for the <code>.csv</code> route, but I really wanted you to figure out how to read the Excel spreadsheet directly, so that’s what would be worth full marks.</p>
<p>You might want to check that you have some males and some females, and how many of each, which you could do this way:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>parking <span class="sc">%&gt;%</span> <span class="fu">count</span>(gender)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["gender"],"name":[1],"type":["chr"],"align":["left"]},{"label":["n"],"name":[2],"type":["int"],"align":["right"]}],"data":[{"1":"female","2":"47"},{"1":"male","2":"46"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" type="a">
<li>Obtain side-by-side boxplots of parking distances for males and females. Does one gender seem to be better at parking than the other? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>With the right data set, this is a piece of cake:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(parking, <span class="fu">aes</span>(<span class="at">x =</span> gender, <span class="at">y =</span> distance)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="two-sample-inference_files/figure-html/parking-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The outcome variable is distance from the curb, so smaller should be better (more accurate parking). With that in mind, the median for females is a little smaller than for males (about 8.5 vs.&nbsp;about 10), so it seems that on average females are more accurate parkers than males are. The difference is small, however (and so you might be wondering at this point whether it’s a statistically significant difference — don’t worry, that’s coming up).</p>
<p>Before I leave this one, I want to show you something else: above-and-below histograms, as another way of comparing males and females (two or more groups, in general). First, we make a histogram of all the distances, without distinguishing by gender:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(parking, <span class="fu">aes</span>(<span class="at">x =</span> distance)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="two-sample-inference_files/figure-html/parking-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>That big outlier is the very inaccurate male driver.</p>
<p>Now, how do we get a <em>separate</em> histogram for each <code>gender</code>? In <code>ggplot</code>, separate plots for each “something” are called <strong>facets</strong>, and the way to get facets arranged as you want them is called <code>facet_grid</code>.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> Let me show you the code first, and then explain how it works:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(parking, <span class="fu">aes</span>(<span class="at">x =</span> distance)) <span class="sc">+</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">7</span>) <span class="sc">+</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(gender <span class="sc">~</span> .)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="two-sample-inference_files/figure-html/parking-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><code>facet_grid</code> takes a “model formula” with a squiggle, with <span class="math inline">\(y\)</span> on the left and <span class="math inline">\(x\)</span> on the right. We want to compare our two histograms, one for males and one for females, and I think the best way to compare histograms is to have one on top of the other. Note that the same <code>distance</code> scale is used for both histograms, so that it is a fair comparison. The above-and-below is accomplished by having <code>gender</code> as the <span class="math inline">\(y\)</span> in the arrangement of the facets, so it goes before the squiggle. We don’t have any <span class="math inline">\(x\)</span> in the arrangement of the facets, and we tell <code>ggplot</code> this by putting a dot where the <span class="math inline">\(x\)</span> would be.<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a></p>
<p>You can also use <code>facet_wrap</code> for this, but you have to be more careful since you don’t have any control over how the histograms come out (you probably get them side by side, which is not so helpful for comparing distributions). You can make it work by using <code>ncol=1</code> to arrange <em>all</em> the histograms in one column:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(parking, <span class="fu">aes</span>(<span class="at">x =</span> distance)) <span class="sc">+</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">7</span>) <span class="sc">+</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>gender, <span class="at">ncol =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="two-sample-inference_files/figure-html/parking-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The centres of both histograms are somewhere around 10, so it’s hard to see any real difference between males and females here. Maybe this is further evidence that the small difference we saw between the boxplots is really not worth getting excited about.</p>
<p>You might be concerned about how you know what to put with the squiggle-thing in <code>facet_grid</code> and <code>facet_wrap</code>. The answer is that <code>facet_wrap</code> <em>only</em> has something to the right of the squiggle (which <code>ggplot</code> then decides how to arrange), but <code>facet_grid</code> <em>must</em> have something on <em>both</em> sides of the squiggle (how to arrange in the <span class="math inline">\(y\)</span> direction on the left, how to arrange in the <span class="math inline">\(x\)</span> direction on the right), and if you don’t have anything else to put there, you put a dot. Here’s my <code>facet_grid</code> code from above, again:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(parking, <span class="fu">aes</span>(<span class="at">x =</span> distance)) <span class="sc">+</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">7</span>) <span class="sc">+</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(gender <span class="sc">~</span> .)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We wanted gender to go up and down, and we had nothing to go left and right, hence the dot. Contrast that with my <code>facet_wrap</code> code:<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(parking, <span class="fu">aes</span>(<span class="at">x =</span> distance)) <span class="sc">+</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">7</span>) <span class="sc">+</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>gender)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This says “make a separate facet for each gender”, but it doesn’t say anything about how to arrange them. The choice of bins for my histogram(s) came from Sturges’ rule: with <span class="math inline">\(n\)</span> being the number of observations, you use <span class="math inline">\(k\)</span> bins where <span class="math inline">\(k=\log_2(n)+1\)</span>, rounded up. If we were to make a histogram of all the parking distances combined together, we would have <span class="math inline">\(n=47+48=95\)</span> observations, so we should use this many bins:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>sturges <span class="ot">&lt;-</span> <span class="fu">log</span>(<span class="dv">95</span>, <span class="dv">2</span>) <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>sturges</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7.569856</code></pre>
</div>
</div>
<p>Round this up to 8. (The second thing in <code>log</code> is the base of the logs, if you specify it, otherwise it defaults to <span class="math inline">\(e\)</span> and gives you “natural” logs.) I seem to have the powers of 2 in my head, so I can do it mentally by saying “the next power of 2 is 128, which is <span class="math inline">\(2^7\)</span>, so I need <span class="math inline">\(7+1=8\)</span> bins.”</p>
<p>Or:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(parking, <span class="fu">nclass.Sturges</span>(distance))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8</code></pre>
</div>
</div>
<p>Sturges’ rule tends to produce not enough bins if <span class="math inline">\(n\)</span> is small, so be prepared to increase it a bit if you don’t have much data. I think that gives a fairly bare-bones picture of the shape: skewed to the right with outlier.</p>
<p>The other rule we saw was Freedman-Diaconis:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(parking, <span class="fu">nclass.FD</span>(distance))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 14</code></pre>
</div>
</div>
<p>and that leads to this histogram:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(parking, <span class="fu">aes</span>(<span class="at">x =</span> distance)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">14</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="two-sample-inference_files/figure-html/parking-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>That gives rather more detail (a lot more bars: the binwidth in the Sturges-rule histogram is about 7, or twice what you see here), but in this case the overall story is about the same.</p>
<p>In the case of faceted histograms, you would want to apply a rule that uses the number of observations in <em>each</em> histogram. The facets might have quite different numbers of observations, but you can only use one <code>binwidth</code> (or <code>bins</code>), so you may have to compromise. For example, using Sturges’ rule based on 47 observations (the number of males; the number of females is one more):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">log</span>(<span class="dv">47</span>, <span class="dv">2</span>) <span class="sc">+</span> <span class="dv">1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.554589</code></pre>
</div>
</div>
<p>and so each facet should have that many bins, rounded up. That’s where I got my 7 for the facetted histogram from. This one doesn’t work immediately with <code>nclass.Sturges</code>, because we do not have <em>one</em> column whose length is the number of observations we want: we have one column of distances that are males and females mixed up. To do <em>that</em>, <code>filter</code> one of the genders first:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>parking <span class="sc">%&gt;%</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(gender <span class="sc">==</span> <span class="st">"female"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">with</span>(., <span class="fu">nclass.Sturges</span>(distance))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7</code></pre>
</div>
</div>
<p>I used the “dot” trick again, which you can read as “it”: “from <code>parking</code>, take only the rows for the females, and with it, give me the number of bins for a histogram by Sturges’ rule.”</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" type="a">
<li>Explain briefly why this is two independent samples rather than matched pairs.</li>
</ol>
<p>Solution</p>
<p>There is no way to pair any male with a corresponding female, because they are unrelated people. You might also notice that there are not even the <em>same number</em> of males and females, so there can be no way of pairing them up without leaving one over. (In general, if the two samples are paired, there must be the same number of observations in each; if there are different numbers in each, as here, they cannot be paired.) If you want that more mathematically, let <span class="math inline">\(n_1\)</span> and <span class="math inline">\(n_2\)</span> be the two sample sizes; then:</p>
<p><span class="math display">\[
\mbox{Paired} \Longrightarrow n_1=n_2
\]</span></p>
<p>from which it follows logically (the “contrapositive”) that</p>
<p><span class="math display">\[
n_1 \ne n_2 \Longrightarrow \mbox{not paired}
\]</span></p>
<p>You’ll note from the logic that if the two sample sizes are the same, that tells you <em>nothing</em> about whether it’s paired or independent samples: it could be either, and in that case you have to look at the description of the data to decide between them.</p>
<p>Here, anything that gets at why the males and females cannot be paired up is good.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" type="a">
<li>Run a suitable <span class="math inline">\(t\)</span>-test for comparing parking distances for males and females. What do you conclude, in the context of the data?</li>
</ol>
<p>Solution</p>
<p>A two-sample <span class="math inline">\(t\)</span>-test. I think either the Welch or the pooled one can be justified (and I would expect them to give similar answers). You can do the Welch one either without comment or by asserting that the boxplots show different spreads; if you are going to do the pooled one, you need to say that the spreads are “about equal”, by comparing the heights of the boxes on the boxplots:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(distance <span class="sc">~</span> gender, <span class="at">data =</span> parking)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  distance by gender
t = -1.3238, df = 79.446, p-value = 0.1894
alternative hypothesis: true difference in means between group female and group male is not equal to 0
95 percent confidence interval:
 -4.5884103  0.9228228
sample estimates:
mean in group female   mean in group male 
            9.308511            11.141304 </code></pre>
</div>
</div>
<p>This is the Welch-Satterthwaite version of the test, the one that does not assume equal SDs in the two groups. The P-value of 0.1894 is not small, so there is no evidence of any difference in parking accuracy between males and females.</p>
<p>Or, this being the pooled one:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(distance <span class="sc">~</span> gender, <span class="at">data =</span> parking, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  distance by gender
t = -1.329, df = 91, p-value = 0.1872
alternative hypothesis: true difference in means between group female and group male is not equal to 0
95 percent confidence interval:
 -4.5722381  0.9066506
sample estimates:
mean in group female   mean in group male 
            9.308511            11.141304 </code></pre>
</div>
</div>
<p>You might have thought, looking at the boxplots, that the groups had about the same SD (based, for example, on noting that the two boxes were about the same height, so the IQRs were about the same). In that case, you might run a pooled <span class="math inline">\(t\)</span>-test, which here gives an almost identical P-value of 0.1872, and the exact same conclusion.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="6" type="a">
<li>Why might you have some doubts about the <span class="math inline">\(t\)</span>-test that you just did? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>The two-sample <span class="math inline">\(t\)</span>-test is based on an assumption of normally-distributed data within each group. If you go back and look at the boxplots, you’ll see either (depending on your point of view) that both groups are right-skewed, or that both groups have outliers, neither of which fits a normal distribution. The outlier in the male group is particularly egregious.<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a> So I think we are entitled to question whether a two-sample <span class="math inline">\(t\)</span>-test is the right thing to do. Having said that, we should go back and remember that the <span class="math inline">\(t\)</span>-tests are “robust to departures from normality” (since we are working with the Central Limit Theorem here), and therefore that this test might be quite good even though the data are not normal, because the sample sizes of 40-plus are large (by the standards of what typically makes the Central Limit Theorem work for us). So it may not be as bad as it seems. A common competitor for the two-sample <span class="math inline">\(t\)</span>-test is the Mann-Whitney test. This doesn’t assume normality, but it <em>does</em> assume symmetric distributions, which it’s not clear that we have here. I like a test called Mood’s Median Test, which is kind of the two-sample equivalent of the sign test (which we will also see later). It goes like this: Work out the overall median of all the distances, regardless of gender:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>parking <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">med =</span> <span class="fu">median</span>(distance))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["med"],"name":[1],"type":["dbl"],"align":["right"]}],"data":[{"1":"9"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>The overall median is 9.</p>
<p>Count up how many distances of each gender were above or below the overall median. (Strictly, I’m supposed to throw away any values that are exactly equal to the overall median, but I won’t here for clarity of exposition.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>tab <span class="ot">&lt;-</span> <span class="fu">with</span>(parking, <span class="fu">table</span>(gender, distance <span class="sc">&lt;</span> <span class="dv">9</span>))</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>tab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        
gender   FALSE TRUE
  female    23   24
  male      27   19</code></pre>
</div>
</div>
<p>For example, 19 of the male drivers had a distance (strictly) less than 9. Both genders are pretty close to 50–50 above and below the overall median, which suggests that the males and females have about the same median. This can be tested (it’s a chi-squared test for independence, if you know that):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(tab, <span class="at">correct =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  tab
X-squared = 0.89075, df = 1, p-value = 0.3453</code></pre>
</div>
</div>
<p>This is even less significant (P-value 0.3453) than the two-sample <span class="math inline">\(t\)</span>-test, and so is consistent with our conclusion from before that there is actually no difference between males and females in terms of average parking distance. The Mood’s median test is believable because it is not affected by outliers or distribution shape.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="7" type="a">
<li>The Toronto Star in its report said that females are more accurate at parking their cars. Why do you think they concluded that, and do you think they were right to do so? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>The conclusion from the boxplots was that the female median distance was less than the males, slightly, in this sample. That is probably what the Star seized on. Were they right? Well, that was why we did the test of significance. We were trying to see whether this observed difference between males and females was “real” (would hold up if you looked at “all” male and female drivers) or “reproducible” (you would expect to see it again if you did another study like this one). The large, non-significant P-values in all our tests tell us that the difference observed here was nothing more than chance. So it was not reasonable to conclude that females generally are more accurate at parallel-parking than males are.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</section>
<section id="bell-peppers-and-too-much-water-1" class="level2" data-number="5.10">
<h2 data-number="5.10" class="anchored" data-anchor-id="bell-peppers-and-too-much-water-1"><span class="header-section-number">5.10</span> Bell peppers and too much water</h2>
<p>A pathogen called <em>Phytophthora capsici</em> causes bell peppers to wilt and die. It is thought that too much water aids in the spread of the pathogen. Two fields are under study, labelled <code>a</code> and <code>b</code>. The first step in the research project is to compare the mean soil water content of the two fields. There is a suspicion that field <code>a</code> will have a higher water content than field <code>b</code>. The data are in the file <a href="http://ritsokiguess.site/datafiles/bellpepper.csv">link</a>.</p>
<ol type="a">
<li>Read the file in using <code>read_csv</code>, and list the resulting data frame.</li>
</ol>
<p>Solution</p>
<p>Reading directly from the URL is easiest:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>my_url <span class="ot">&lt;-</span> <span class="st">"http://ritsokiguess.site/datafiles/bellpepper.csv"</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>pepper <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(my_url)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 30 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): field
dbl (1): water

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>pepper</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["field"],"name":[1],"type":["chr"],"align":["left"]},{"label":["water"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"a","2":"10.2"},{"1":"a","2":"10.7"},{"1":"a","2":"15.5"},{"1":"a","2":"10.4"},{"1":"a","2":"9.9"},{"1":"a","2":"10.0"},{"1":"a","2":"16.6"},{"1":"a","2":"15.1"},{"1":"a","2":"15.2"},{"1":"a","2":"13.8"},{"1":"a","2":"14.1"},{"1":"a","2":"11.4"},{"1":"a","2":"11.5"},{"1":"a","2":"11.0"},{"1":"b","2":"8.1"},{"1":"b","2":"8.5"},{"1":"b","2":"8.4"},{"1":"b","2":"7.3"},{"1":"b","2":"8.0"},{"1":"b","2":"7.1"},{"1":"b","2":"13.9"},{"1":"b","2":"12.2"},{"1":"b","2":"13.4"},{"1":"b","2":"11.3"},{"1":"b","2":"12.6"},{"1":"b","2":"12.6"},{"1":"b","2":"12.7"},{"1":"b","2":"12.4"},{"1":"b","2":"11.3"},{"1":"b","2":"12.5"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>If you like, find out how many observations you have from each field, thus:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>pepper <span class="sc">%&gt;%</span> <span class="fu">count</span>(field)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["field"],"name":[1],"type":["chr"],"align":["left"]},{"label":["n"],"name":[2],"type":["int"],"align":["right"]}],"data":[{"1":"a","2":"14"},{"1":"b","2":"16"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>Fourteen and sixteen.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" type="a">
<li>Make side-by-side boxplots of the water content values for the two fields. How do the fields seem to compare?</li>
</ol>
<p>Solution</p>
<p>This kind of thing:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pepper, <span class="fu">aes</span>(<span class="at">x =</span> field, <span class="at">y =</span> water)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="two-sample-inference_files/figure-html/dartmouth-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This one is rather interesting: the distribution of water contents for field <code>a</code> is generally higher than that for field <code>b</code>, but the median for <code>a</code> is actually <em>lower</em>.</p>
<p>The other reasonable plot is a facetted histogram, something like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pepper, <span class="fu">aes</span>(<span class="at">x =</span> water)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">6</span>) <span class="sc">+</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(field <span class="sc">~</span> .)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="two-sample-inference_files/figure-html/bellpepper-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The distribution of water content in field <code>b</code> is actually bimodal, which is probably the explanation of the funny thing with the median. What actually seems to be happening (at least for these data) is that the water content in field B is either about the same as field A, or a lot less (nothing in between). I can borrow an idea from earlier to find the five-number summaries for each field:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>pepper <span class="sc">%&gt;%</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nest</span>(<span class="sc">-</span>field) <span class="sc">%&gt;%</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">qq =</span> <span class="fu">list</span>(<span class="fu">enframe</span>(<span class="fu">quantile</span>(data<span class="sc">$</span>water))))<span class="sc">%&gt;%</span></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest</span>(qq) <span class="sc">%&gt;%</span></span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>data) <span class="sc">%&gt;%</span> </span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from=</span>name, <span class="at">values_from=</span>value)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Supplying `...` without names was deprecated in tidyr 1.0.0.
ℹ Please specify a name for each selection.
ℹ Did you want `data = -field`?</code></pre>
</div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["field"],"name":[1],"type":["chr"],"align":["left"]},{"label":["0%"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["25%"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["50%"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["75%"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["100%"],"name":[6],"type":["dbl"],"align":["right"]}],"data":[{"1":"a","2":"9.9","3":"10.475","4":"11.45","5":"14.85","6":"16.6"},{"1":"b","2":"7.1","3":"8.325","4":"11.75","5":"12.60","6":"13.9"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>This is a weird one: all the quantiles are greater for field A <em>except</em> for the median.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" type="a">
<li>Do a two-sample <span class="math inline">\(t\)</span>-test to test whether there is evidence that the mean water content in field <code>a</code> is higher than that of field <code>b</code>. What do you conclude? Explain briefly. (You’ll need to figure out a way of doing a one-sided test, or how to adapt the results from a two-sided test.)</li>
</ol>
<p>Solution</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(water <span class="sc">~</span> field, <span class="at">alternative =</span> <span class="st">"greater"</span>, <span class="at">data =</span> pepper)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  water by field
t = 2.0059, df = 27.495, p-value = 0.0274
alternative hypothesis: true difference in means between group a and group b is greater than 0
95 percent confidence interval:
 0.2664399       Inf
sample estimates:
mean in group a mean in group b 
       12.52857        10.76875 </code></pre>
</div>
</div>
<p>Note the use of <code>alternative</code> to specify that the first group mean (that of field <code>a</code>) is bigger than the second, field <code>b</code>, under the alternative hypothesis.</p>
<p>The P-value, 0.0274, is less than 0.05, so we reject the null (equal means) in favour of the <code>a</code> mean being bigger than the <code>b</code> mean: field <code>a</code> really does have a higher mean water content.</p>
<p>Another way to tackle this is to do a two-sided test and adapt the P-value:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(water <span class="sc">~</span> field, <span class="at">data =</span> pepper)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  water by field
t = 2.0059, df = 27.495, p-value = 0.0548
alternative hypothesis: true difference in means between group a and group b is not equal to 0
95 percent confidence interval:
 -0.03878411  3.55842696
sample estimates:
mean in group a mean in group b 
       12.52857        10.76875 </code></pre>
</div>
</div>
<p>This time we do <em>not</em> go straight to the P-value. First we check that we are on the correct side, which we are since the sample mean for field <code>a</code> <em>is</em> bigger than for field <code>b</code>. Then we are entitled to take the two-sided P-value 0.0548 and <em>halve</em> it to get the same 0.0274 that we did before.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" type="a">
<li>Is the result of your test consistent with the boxplot, or not? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>The test said that field <code>a</code> had a greater mean water content. Looking at the boxplot, this is consistent with where the boxes sit (<code>a</code>’s box is higher up than <code>b</code>’s). However, it is not consistent with the medians, where <code>b</code>’s median is actually <em>bigger</em>. You have two possible right answers here: comparing the boxes with the test result (they agree) or comparing the medians with the test result (they disagree). Either is good. If you like, you could also take the angle that the two boxes overlap a fair bit, so it is surprising that the test came out significant. (The resolution of this one is that we have 30 measurements altogether, 14 and 16 in the two groups, so the sample size is not tiny. With smaller samples, having overlapping boxes would probably lead to a non-significant difference.)</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</section>
<section id="exercise-and-anxiety-and-bullying-mice-1" class="level2" data-number="5.11">
<h2 data-number="5.11" class="anchored" data-anchor-id="exercise-and-anxiety-and-bullying-mice-1"><span class="header-section-number">5.11</span> Exercise and anxiety and bullying mice</h2>
<p>Does exercise help to reduce anxiety? To assess this, some researchers randomly assigned mice to either an enriched environment where there was an exercise wheel available, or a standard environment with no exercise options. After three weeks in the specified environment, for five minutes a day for two weeks, the mice were each exposed to a “mouse bully” — a mouse who was very strong, aggressive, and territorial. One measure of mouse anxiety is amount of time hiding in a dark compartment, with mice who are more anxious spending more time in darkness. The amount of time spent in darkness is recorded for each of the mice.</p>
<p>The data can be found at <a href="http://ritsokiguess.site/datafiles/stressedmice.txt">link</a>.</p>
<ol type="a">
<li>Read the data into R, and display your data frame. Count the number of mice in each group.</li>
</ol>
<p>Solution</p>
<p>These are aligned columns with spaces in between, so we need <code>read_table</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>my_url <span class="ot">&lt;-</span> <span class="st">"http://ritsokiguess.site/datafiles/stressedmice.txt"</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>mice <span class="ot">&lt;-</span> <span class="fu">read_table</span>(my_url)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
── Column specification ────────────────────────────────────────────────────────
cols(
  Time = col_double(),
  Environment = col_character()
)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>mice</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["Time"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["Environment"],"name":[2],"type":["chr"],"align":["left"]}],"data":[{"1":"359","2":"Enriched"},{"1":"280","2":"Enriched"},{"1":"138","2":"Enriched"},{"1":"227","2":"Enriched"},{"1":"203","2":"Enriched"},{"1":"184","2":"Enriched"},{"1":"231","2":"Enriched"},{"1":"394","2":"Standard"},{"1":"477","2":"Standard"},{"1":"439","2":"Standard"},{"1":"428","2":"Standard"},{"1":"391","2":"Standard"},{"1":"488","2":"Standard"},{"1":"454","2":"Standard"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>You can call the data frame whatever you like.</p>
<p>If you must, you can physically count the number of mice in each group, but you ought to get in the habit of coding this kind of thing:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>mice <span class="sc">%&gt;%</span> <span class="fu">count</span>(Environment)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["Environment"],"name":[1],"type":["chr"],"align":["left"]},{"label":["n"],"name":[2],"type":["int"],"align":["right"]}],"data":[{"1":"Enriched","2":"7"},{"1":"Standard","2":"7"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>Seven in each.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" type="a">
<li>Draw side-by-side boxplots of time spent in darkness for each group of mice.</li>
</ol>
<p>Solution</p>
<p>This:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mice, <span class="fu">aes</span>(<span class="at">x =</span> Environment, <span class="at">y =</span> Time)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="two-sample-inference_files/figure-html/artichoke-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>You did remember to put capital letters on the variable names, didn’t you?</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" type="a">
<li>Do the boxplots support the hypothesis about exercise and anxiety? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>The hypothesis about exercise and anxiety is that mice who exercise more should be less anxious. How does that play out in this study? Well, mice in the enriched environment at least have the opportunity to exercise, which the mice in the standard environment do not, and anxiety is measured by the amount of time spent in darkness (more equals more anxious). So we’d expect the mice in the standard environment to spend more time in darkness, if that hypothesis is correct. That’s exactly what the boxplots show, with very little doubt.<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a> Your answer needs to make two points: (i) what you would expect to see, if the hypothesis about anxiety and exercise is true, and (ii) whether you actually did see it. You can do this either way around: for example, you can say what you see in the boxplot, and then make the case that this <em>does</em> support the idea of more exercise corresponding with less anxiety.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" type="a">
<li>Carry out a <span class="math inline">\(t\)</span>-test for comparing the mean time spent in darkness for the mice in the two groups. Think carefully about the details of the <span class="math inline">\(t\)</span>-test (and what you need evidence in favour of).</li>
</ol>
<p>Solution</p>
<p>We are trying to prove that exercise goes with <em>less</em> anxiety, so a one-sided test is called for. The other thing to think about is how R organizes the groups for <code>Environment</code>: in alphabetical order. Thus <code>Enriched</code> is first (like on the boxplot). We’re trying to prove that the mean <code>Time</code> is <em>less</em> for <code>Enriched</code> than for <code>Standard</code>, so we need <code>alternative="less"</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(mice, <span class="fu">t.test</span>(Time <span class="sc">~</span> Environment, <span class="at">alternative =</span> <span class="st">"less"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  Time by Environment
t = -6.7966, df = 9.1146, p-value = 3.734e-05
alternative hypothesis: true difference in means between group Enriched and group Standard is less than 0
95 percent confidence interval:
      -Inf -151.2498
sample estimates:
mean in group Enriched mean in group Standard 
              231.7143               438.7143 </code></pre>
</div>
</div>
<p>A common clue that you have the wrong alternative hypothesis is a P-value coming out close to <em>1</em>, which is what you would have gotten from something like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(mice, <span class="fu">t.test</span>(Time <span class="sc">~</span> Environment, <span class="at">alternative =</span> <span class="st">"greater"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  Time by Environment
t = -6.7966, df = 9.1146, p-value = 1
alternative hypothesis: true difference in means between group Enriched and group Standard is greater than 0
95 percent confidence interval:
 -262.7502       Inf
sample estimates:
mean in group Enriched mean in group Standard 
              231.7143               438.7143 </code></pre>
</div>
</div>
<p>Here, we looked at the pictures and expected to find a difference, so we expected to find a P-value close to 0 rather than close to 1.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" type="a">
<li>What do you conclude, in terms of anxiety and exercise (at least for mice)? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>The P-value (from the previous part) is 0.000037, which is way less than 0.05 (or 0.01 or whatever <span class="math inline">\(\alpha\)</span> you chose). So the null hypothesis (equal means) is resoundingly rejected in favour of the one-sided alternative that the mean anxiety (as measured by time spent in darkness) is less for the mice who (can) exercise. You need to end up by doing a one-sided test. An alternative to what I did is to do a two-sided test in the previous part. Then you can fix it up by recognizing that the means are the right way around for the research hypothesis (the mean time in darkness is way less for <code>Enriched</code>), and then dividing the two-sided P-value by 2. But you need to do the “correct side” thing: just halving the two-sided P-value is not enough, because the sample mean for <code>Enriched</code> might have been <em>more</em> than for <code>Standard</code>.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="6" type="a">
<li>Does anything in the previous parts suggest any problems with the analysis you just did? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>Look at the side-by-side boxplots. The strict assumptions hiding behind the <span class="math inline">\(t\)</span>-tests are that the data in each group come from normal distributions (equal standard deviations are not required). Are the data symmetric? Are there any outliers? Well, I see a high outlier in the <code>Enriched</code> group, so I have some doubts about the normality. On the other hand, I only have seven observations in each group, so there is no guarantee even if the populations from which they come are normal that the samples will be. So maybe things are not so bad. This is one of those situations where you make a case and defend it. I don’t mind so much which case you make, as long as you can defend it. Thus, something like either of these two is good:</p>
<ul>
<li><p>I see an outlier in the <code>Enriched</code> group. The data within each group are supposed to be normally distributed, and the <code>Enriched</code> group is not. So I see a problem.</p></li>
<li><p>I see an outlier in the <code>Enriched</code> group. But the sample sizes are small, and an apparent outlier could arise by chance. So I do not see a problem.</p></li>
</ul>
<p>Extra: another way to think about this is normal quantile plots to assess normality within each group. This uses the facetting trick to get a separate normal quantile plot for each <code>Environment</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mice, <span class="fu">aes</span>(<span class="at">sample =</span> Time)) <span class="sc">+</span> <span class="fu">stat_qq</span>() <span class="sc">+</span> <span class="fu">stat_qq_line</span>() <span class="sc">+</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Environment, <span class="at">scales =</span> <span class="st">"free"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="two-sample-inference_files/figure-html/mousebully-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>For the <code>Enriched</code> group, the upper-end outlier shows up. In a way this plot is no more illuminating than the boxplot, because you still have to make a call about whether this is “too big”. Bear in mind also that these facetted normal quantile plots, with two groups, come out tall and skinny, so vertical deviations from the line are exaggerated. On this plot, the lowest value also looks too low.</p>
<p>For the <code>Standard</code> group, there are no problems with normality at all.</p>
<p>What happens if we change the shape of the plots?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mice, <span class="fu">aes</span>(<span class="at">sample =</span> Time)) <span class="sc">+</span> <span class="fu">stat_qq</span>() <span class="sc">+</span> <span class="fu">stat_qq_line</span>() <span class="sc">+</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Environment, <span class="at">scales =</span> <span class="st">"free"</span>, <span class="at">ncol =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="two-sample-inference_files/figure-html/mousebully-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This makes the plots come out in one column, that is, short and squat. I prefer these. I’d still call the highest value in <code>Enriched</code> an outlier, but the lowest value now looks pretty close to what you’d expect.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</section>
<section id="diet-and-growth-in-boys-1" class="level2" data-number="5.12">
<h2 data-number="5.12" class="anchored" data-anchor-id="diet-and-growth-in-boys-1"><span class="header-section-number">5.12</span> Diet and growth in boys</h2>
<p>A dietician is studying the effect of different diets on children’s growth. In part of the study, the dietician is investigating two religious sects, labelled <code>a</code> and <code>b</code> in our data set. Both sects are vegetarian; the difference between them is that people in Sect A only eat vegetables from below the ground, and Sect B only eats vegetables from above the ground. The height and weight of the boys<a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a> are measured at regular intervals. The data in <a href="http://ritsokiguess.site/datafiles/kids-diet.txt">link</a> are the heights of the boys at age 12.</p>
<ol type="a">
<li>Read in the data and find out how many observations you have and which variables.</li>
</ol>
<p>Solution</p>
<p>The data values are separated by one space, so:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>my_url <span class="ot">&lt;-</span> <span class="st">"http://ritsokiguess.site/datafiles/kids-diet.txt"</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>diet <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(my_url, <span class="st">" "</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 21 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: " "
chr (1): sect
dbl (1): height

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>diet</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["sect"],"name":[1],"type":["chr"],"align":["left"]},{"label":["height"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"a","2":"140"},{"1":"a","2":"140"},{"1":"a","2":"140"},{"1":"a","2":"143"},{"1":"a","2":"135"},{"1":"a","2":"144"},{"1":"a","2":"156"},{"1":"a","2":"149"},{"1":"a","2":"146"},{"1":"a","2":"148"},{"1":"a","2":"144"},{"1":"a","2":"153"},{"1":"b","2":"151"},{"1":"b","2":"154"},{"1":"b","2":"139"},{"1":"b","2":"159"},{"1":"b","2":"159"},{"1":"b","2":"148"},{"1":"b","2":"140"},{"1":"b","2":"157"},{"1":"b","2":"145"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>21 observations on two variables, <code>sect</code> and <code>height</code>. (You should state this; it is not enough to make the reader figure it out for themselves.)</p>
<p>The heights are evidently in centimetres.</p>
<p>You can call the data frame whatever you like.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" type="a">
<li>Obtain side-by-side boxplots of the heights for boys from each sect. Does it look as if the heights of the boys in each sect are different? Comment briefly.</li>
</ol>
<p>Solution</p>
<p>The boxplot is the kind of thing we’ve seen before:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(diet, <span class="fu">aes</span>(<span class="at">x =</span> sect, <span class="at">y =</span> height)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="two-sample-inference_files/figure-html/kids-diet-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>It looks to me as if the boys in Sect B are taller on average.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" type="a">
<li>Looking at your boxplots, do you see any problems with doing a two-sample <span class="math inline">\(t\)</span>-test? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>The assumption is that the data in each group are “approximately normal”. Boxplots don’t tell you about normality specifically, but they tell you whether there are any outliers (none here) and something about the shape (via the lengths of the whiskers). I’d say the Sect A values are as symmetric as we could hope for. For Sect B, you can say either that they’re skewed to the left (and that therefore we have a problem), or that the heights are close enough to symmetric (and that therefore we don’t). For me, either is good. As ever, normal quantile plots can offer more insight. With data in this form, the two samples are mixed up, but using facets is the way to go. Philosophically, we draw a normal quantile plot of <em>all</em> the heights, and then say at the end that we would actually like a separate plot for each sect:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>diet <span class="sc">%&gt;%</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">sample =</span> height)) <span class="sc">+</span> <span class="fu">stat_qq</span>() <span class="sc">+</span> <span class="fu">stat_qq_line</span>() <span class="sc">+</span></span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>sect, <span class="at">ncol =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="two-sample-inference_files/figure-html/kids-diet-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>I decided that I wanted short squat plots rather than tall skinny ones.</p>
<p>With the sizes of the samples, I really don’t see any problems here. Most of the evidence for the left skewness in Sect B is actually coming from that largest value being too small. Sect A is as good as you could wish for. Having extreme values being <em>not extreme enough</em> is not a problem, since it won’t be distorting the mean.</p>
<p>The other way of doing this is to use <code>filter</code> to pull out the rows you want and then feed that into the plot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>secta <span class="ot">&lt;-</span> <span class="fu">filter</span>(diet, sect <span class="sc">==</span> <span class="st">"a"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">sample =</span> sect)) <span class="sc">+</span> <span class="fu">stat_qq</span>() <span class="sc">+</span> <span class="fu">stat_qq_line</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>and the same for sect B. This is the usual <code>ggplot</code>-in-pipeline thing where you don’t have a named data frame in the <code>ggplot</code> because it will use whatever came out of the previous step of the pipeline.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" type="a">
<li>Run a <span class="math inline">\(t\)</span>-test to determine whether the mean heights differ significantly. What do you conclude? Explain briefly. (Run the <span class="math inline">\(t\)</span>-test even if your previous work suggests that it is not the right thing to do.)</li>
</ol>
<p>Solution</p>
<p>The wording states that a two-sided test is correct, which is the default, so you don’t need anything special:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(height <span class="sc">~</span> sect, <span class="at">data =</span> diet)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  height by sect
t = -1.7393, df = 14.629, p-value = 0.103
alternative hypothesis: true difference in means between group a and group b is not equal to 0
95 percent confidence interval:
 -12.007505   1.229728
sample estimates:
mean in group a mean in group b 
       144.8333        150.2222 </code></pre>
</div>
</div>
<p>This is a two-sample test, so it takes a <code>data=</code>.</p>
<p>Our null hypothesis is that the two sects have equal mean height. The P-value of 0.103 is larger than 0.05, so we do not reject that null hypothesis. That is, there is no evidence that the sects differ in mean height. (That is, our earlier thought that the boys in Sect B were taller is explainable by chance.)</p>
<p>You <em>must</em> end up with a statement about mean heights, and when you do a test, you must state the conclusion in the context of the problem, whether I ask you to or not. “Don’t reject the null hypothesis” is a step on the way to an answer, not an answer in itself. If you think it’s an answer in itself, you won’t be of much use to the world as a statistician.</p>
<p>You might have been thinking that Mood’s median test was the thing, if you were worried about that skewness in Sect B. My guess is that the <span class="math inline">\(t\)</span>-test is all right, so it will be the better test (and give the smaller P-value) here, but if you want to do it, you could do it this way:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(smmr)</span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a><span class="fu">median_test</span>(diet, height, sect)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$table
     above
group above below
    a     4     7
    b     6     3

$test
       what     value
1 statistic 1.8181818
2        df 1.0000000
3   P-value 0.1775299</code></pre>
</div>
</div>
<p>My suspicion (that I wrote before doing the test) is correct: there is even less evidence of a difference in median height between the sects. The table shows that both sects are pretty close to 50–50 above and below the overall median, and with sample sizes this small, they are certainly not significantly different from an even split. The small frequencies bring a warning about the chi-squared approximation possibly not working (that <code>smmr</code> suppresses). We had one like this elsewhere, but there the result was very significant, and this one is very non-significant. However, the implication is the same: even if the P-value is not very accurate (because the expected frequencies for sect B are both 4.5), the conclusion is unlikely to be wrong because the P-value is so far from 0.05.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</section>
<section id="handspans-of-males-and-females-1" class="level2" data-number="5.13">
<h2 data-number="5.13" class="anchored" data-anchor-id="handspans-of-males-and-females-1"><span class="header-section-number">5.13</span> Handspans of males and females</h2>
<p>Take your right hand, and stretch the fingers out as far as you can. The distance between the tip of your thumb and the tip of your little (pinky) finger is your handspan. The students in a Statistics class at Penn State measured their handspans and also whether they identified as male or female. The data are at <a href="http://ritsokiguess.site/datafiles/handspan.txt">http://ritsokiguess.site/datafiles/handspan.txt</a>, with handspans measured in inches. Thinking of these as a random sample of all possible students, is it true that males have a larger mean handspan than females? This is what we will explore.</p>
<ol type="a">
<li>Read in and display (some of) the data.</li>
</ol>
<p>Solution</p>
<p>This is a delimited (by spaces) file, so:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>my_url <span class="ot">&lt;-</span> <span class="st">"http://ritsokiguess.site/datafiles/handspan.txt"</span></span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>span <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(my_url, <span class="st">" "</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 190 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: " "
chr (1): sex
dbl (1): handspan

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>span</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["sex"],"name":[1],"type":["chr"],"align":["left"]},{"label":["handspan"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"M","2":"21.50"},{"1":"M","2":"22.50"},{"1":"M","2":"23.50"},{"1":"F","2":"20.00"},{"1":"F","2":"19.00"},{"1":"F","2":"20.50"},{"1":"F","2":"20.50"},{"1":"F","2":"20.25"},{"1":"M","2":"23.00"},{"1":"M","2":"24.50"},{"1":"M","2":"23.00"},{"1":"F","2":"20.00"},{"1":"M","2":"26.00"},{"1":"M","2":"23.00"},{"1":"F","2":"18.00"},{"1":"M","2":"21.50"},{"1":"F","2":"20.50"},{"1":"M","2":"21.50"},{"1":"F","2":"22.00"},{"1":"M","2":"24.50"},{"1":"F","2":"20.00"},{"1":"F","2":"21.50"},{"1":"M","2":"23.50"},{"1":"F","2":"17.00"},{"1":"F","2":"16.00"},{"1":"M","2":"22.00"},{"1":"F","2":"22.00"},{"1":"F","2":"22.00"},{"1":"F","2":"20.00"},{"1":"M","2":"23.50"},{"1":"M","2":"22.00"},{"1":"M","2":"22.00"},{"1":"M","2":"24.50"},{"1":"F","2":"20.00"},{"1":"F","2":"20.00"},{"1":"F","2":"20.00"},{"1":"F","2":"21.70"},{"1":"F","2":"22.00"},{"1":"F","2":"20.00"},{"1":"F","2":"21.00"},{"1":"F","2":"21.00"},{"1":"F","2":"19.00"},{"1":"F","2":"21.00"},{"1":"F","2":"20.25"},{"1":"F","2":"21.00"},{"1":"F","2":"22.00"},{"1":"F","2":"18.00"},{"1":"F","2":"20.00"},{"1":"M","2":"23.00"},{"1":"M","2":"22.50"},{"1":"M","2":"19.50"},{"1":"M","2":"22.50"},{"1":"M","2":"22.00"},{"1":"M","2":"23.00"},{"1":"M","2":"22.50"},{"1":"M","2":"20.50"},{"1":"M","2":"21.50"},{"1":"M","2":"23.00"},{"1":"M","2":"22.50"},{"1":"M","2":"21.50"},{"1":"M","2":"25.00"},{"1":"F","2":"21.00"},{"1":"F","2":"19.00"},{"1":"F","2":"22.50"},{"1":"F","2":"21.00"},{"1":"F","2":"20.00"},{"1":"F","2":"19.00"},{"1":"F","2":"21.00"},{"1":"F","2":"20.50"},{"1":"F","2":"21.00"},{"1":"F","2":"22.00"},{"1":"F","2":"20.00"},{"1":"F","2":"20.00"},{"1":"F","2":"18.00"},{"1":"F","2":"21.00"},{"1":"F","2":"22.50"},{"1":"F","2":"22.50"},{"1":"M","2":"24.00"},{"1":"M","2":"21.50"},{"1":"M","2":"21.50"},{"1":"M","2":"18.00"},{"1":"M","2":"20.00"},{"1":"M","2":"22.00"},{"1":"M","2":"24.00"},{"1":"M","2":"22.00"},{"1":"M","2":"23.00"},{"1":"M","2":"22.00"},{"1":"M","2":"22.00"},{"1":"M","2":"23.00"},{"1":"M","2":"22.50"},{"1":"M","2":"25.50"},{"1":"M","2":"24.00"},{"1":"F","2":"19.00"},{"1":"F","2":"19.00"},{"1":"F","2":"19.00"},{"1":"F","2":"22.50"},{"1":"F","2":"20.00"},{"1":"F","2":"13.00"},{"1":"F","2":"20.00"},{"1":"F","2":"22.50"},{"1":"F","2":"19.50"},{"1":"F","2":"18.50"},{"1":"F","2":"19.00"},{"1":"F","2":"17.50"},{"1":"F","2":"18.00"},{"1":"F","2":"21.00"},{"1":"F","2":"19.50"},{"1":"F","2":"20.00"},{"1":"F","2":"19.00"},{"1":"F","2":"21.50"},{"1":"F","2":"18.00"},{"1":"F","2":"19.00"},{"1":"F","2":"19.50"},{"1":"F","2":"20.00"},{"1":"F","2":"22.50"},{"1":"M","2":"23.50"},{"1":"M","2":"21.00"},{"1":"M","2":"25.50"},{"1":"M","2":"23.00"},{"1":"M","2":"22.50"},{"1":"M","2":"24.00"},{"1":"M","2":"21.50"},{"1":"M","2":"22.00"},{"1":"M","2":"22.50"},{"1":"M","2":"23.00"},{"1":"M","2":"18.50"},{"1":"M","2":"21.00"},{"1":"M","2":"24.00"},{"1":"M","2":"23.50"},{"1":"M","2":"24.50"},{"1":"M","2":"23.00"},{"1":"M","2":"22.00"},{"1":"M","2":"23.00"},{"1":"M","2":"23.00"},{"1":"M","2":"24.00"},{"1":"M","2":"24.50"},{"1":"F","2":"21.00"},{"1":"F","2":"18.00"},{"1":"F","2":"22.00"},{"1":"F","2":"18.50"},{"1":"F","2":"19.00"},{"1":"F","2":"22.00"},{"1":"F","2":"12.50"},{"1":"F","2":"18.00"},{"1":"F","2":"20.50"},{"1":"F","2":"19.00"},{"1":"F","2":"20.00"},{"1":"F","2":"21.00"},{"1":"F","2":"19.00"},{"1":"F","2":"19.00"},{"1":"F","2":"21.00"},{"1":"F","2":"18.50"},{"1":"F","2":"19.00"},{"1":"F","2":"21.50"},{"1":"F","2":"21.50"},{"1":"F","2":"23.00"},{"1":"F","2":"23.25"},{"1":"F","2":"20.00"},{"1":"F","2":"18.80"},{"1":"F","2":"21.00"},{"1":"F","2":"17.00"},{"1":"F","2":"21.00"},{"1":"F","2":"20.00"},{"1":"F","2":"20.50"},{"1":"F","2":"20.00"},{"1":"F","2":"19.50"},{"1":"F","2":"21.00"},{"1":"F","2":"21.00"},{"1":"F","2":"20.00"},{"1":"M","2":"20.50"},{"1":"M","2":"24.00"},{"1":"M","2":"22.00"},{"1":"M","2":"23.00"},{"1":"M","2":"21.00"},{"1":"M","2":"22.50"},{"1":"M","2":"21.50"},{"1":"M","2":"24.50"},{"1":"M","2":"22.00"},{"1":"M","2":"22.00"},{"1":"M","2":"21.00"},{"1":"M","2":"23.00"},{"1":"M","2":"22.50"},{"1":"M","2":"24.00"},{"1":"M","2":"22.50"},{"1":"M","2":"23.00"},{"1":"M","2":"23.00"},{"1":"M","2":"23.00"},{"1":"M","2":"21.50"},{"1":"M","2":"19.00"},{"1":"M","2":"21.50"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" type="a">
<li>Make a suitable graph of the two columns.</li>
</ol>
<p>Solution</p>
<p>One quantitative variable and one categorical one, so a boxplot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(span, <span class="fu">aes</span>(<span class="at">x=</span>sex, <span class="at">y=</span>handspan)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="two-sample-inference_files/figure-html/handspan-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" type="a">
<li>Run a suitable two-sample <span class="math inline">\(t\)</span>-test to address the question of interest. What do you conclude, in the context of the data?</li>
</ol>
<p>Solution</p>
<p>We are trying to show that males have a <em>larger</em> mean handspan, so we need an <code>alternative</code>. To see which: there are two sexes, F and M in that order, and we are trying to show that F is less than M:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(handspan<span class="sc">~</span>sex, <span class="at">data=</span>span, <span class="at">alternative=</span><span class="st">"less"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  handspan by sex
t = -10.871, df = 187.92, p-value &lt; 2.2e-16
alternative hypothesis: true difference in means between group F and group M is less than 0
95 percent confidence interval:
      -Inf -2.154173
sample estimates:
mean in group F mean in group M 
       20.01699        22.55747 </code></pre>
</div>
</div>
<p>The P-value is very small, so there is no doubt that males have larger average handspans than females.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" type="a">
<li>Obtain a 90% confidence interval for the difference in mean handspan between males and females. Do you need to run any more code? Explain briefly.</li>
</ol>
<p>Solution</p>
<p>A confidence interval is two-sided, so we have to re-run the test without the to make it two-sided. Note also that we need a 90% interval, which is different from the default 95%, so we have to ask for that too:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(handspan<span class="sc">~</span>sex, <span class="at">data=</span>span, <span class="at">conf.level=</span><span class="fl">0.90</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  handspan by sex
t = -10.871, df = 187.92, p-value &lt; 2.2e-16
alternative hypothesis: true difference in means between group F and group M is not equal to 0
90 percent confidence interval:
 -2.926789 -2.154173
sample estimates:
mean in group F mean in group M 
       20.01699        22.55747 </code></pre>
</div>
</div>
<p>The interval is <span class="math inline">\(-2.93\)</span> to <span class="math inline">\(-2.15\)</span>, <em>which you should say</em>. It would be even better to say that males have a mean handspan between 2.15 and 2.93 inches larger than that of females. You also need to round off your answer: the data are given to 0 or 1 decimals, so your interval should be given to 1 or 2 decimals (since the confidence interval is for a mean).</p>
<p>On a question like this, the grader is looking for three things:</p>
<ul>
<li>getting the output</li>
<li>saying what the interval is</li>
<li>rounding it to a suitable number of decimals.</li>
</ul>
<p>Thus, getting the output alone is only one out of three things.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" type="a">
<li>Explain briefly why you might have some concerns about the validity of the <span class="math inline">\(t\)</span>-tests you ran in this question. Or, if you don’t have any concerns, explain briefly why that is.</li>
</ol>
<p>Solution</p>
<p>The major assumption here is that the male and female handspans have (approximate) normal distributions. The boxplots we drew earlier both had low-end outliers, so the normality is questionable.</p>
<p>Also, say something about the sample sizes and whether or not you think they are large enough to be helpful.</p>
<p>How big are our sample sizes?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a>span <span class="sc">%&gt;%</span> <span class="fu">count</span>(sex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["sex"],"name":[1],"type":["chr"],"align":["left"]},{"label":["n"],"name":[2],"type":["int"],"align":["right"]}],"data":[{"1":"F","2":"103"},{"1":"M","2":"87"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>My suspicion is that we are saved by two things: the sample sizes are large enough for the central limit theorem to help us, and in any case, the conclusion is so clear that the assumptions can afford to be off by a bit.</p>
<p>Extra: one way to think about whether we should be concerned about the lack of normality is to use the <code>bootstrap</code> to see what the sampling distribution of the sample mean might look like for males and for females. (This is the stuff in Lecture 5a.) The way this works is to sample from each distribution <em>with replacement</em>, work out the mean of each sample, then repeat many times, once for the females and once for the males.</p>
<p>To start with the females, the first thing to do is to grab <em>only</em> the rows containing the females. This, using an idea from Lecture 5a that we see again properly later, is <code>filter</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a>span <span class="sc">%&gt;%</span> <span class="fu">filter</span>(sex<span class="sc">==</span><span class="st">"F"</span>) <span class="ot">-&gt;</span> females</span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a>females</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["sex"],"name":[1],"type":["chr"],"align":["left"]},{"label":["handspan"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"F","2":"20.00"},{"1":"F","2":"19.00"},{"1":"F","2":"20.50"},{"1":"F","2":"20.50"},{"1":"F","2":"20.25"},{"1":"F","2":"20.00"},{"1":"F","2":"18.00"},{"1":"F","2":"20.50"},{"1":"F","2":"22.00"},{"1":"F","2":"20.00"},{"1":"F","2":"21.50"},{"1":"F","2":"17.00"},{"1":"F","2":"16.00"},{"1":"F","2":"22.00"},{"1":"F","2":"22.00"},{"1":"F","2":"20.00"},{"1":"F","2":"20.00"},{"1":"F","2":"20.00"},{"1":"F","2":"20.00"},{"1":"F","2":"21.70"},{"1":"F","2":"22.00"},{"1":"F","2":"20.00"},{"1":"F","2":"21.00"},{"1":"F","2":"21.00"},{"1":"F","2":"19.00"},{"1":"F","2":"21.00"},{"1":"F","2":"20.25"},{"1":"F","2":"21.00"},{"1":"F","2":"22.00"},{"1":"F","2":"18.00"},{"1":"F","2":"20.00"},{"1":"F","2":"21.00"},{"1":"F","2":"19.00"},{"1":"F","2":"22.50"},{"1":"F","2":"21.00"},{"1":"F","2":"20.00"},{"1":"F","2":"19.00"},{"1":"F","2":"21.00"},{"1":"F","2":"20.50"},{"1":"F","2":"21.00"},{"1":"F","2":"22.00"},{"1":"F","2":"20.00"},{"1":"F","2":"20.00"},{"1":"F","2":"18.00"},{"1":"F","2":"21.00"},{"1":"F","2":"22.50"},{"1":"F","2":"22.50"},{"1":"F","2":"19.00"},{"1":"F","2":"19.00"},{"1":"F","2":"19.00"},{"1":"F","2":"22.50"},{"1":"F","2":"20.00"},{"1":"F","2":"13.00"},{"1":"F","2":"20.00"},{"1":"F","2":"22.50"},{"1":"F","2":"19.50"},{"1":"F","2":"18.50"},{"1":"F","2":"19.00"},{"1":"F","2":"17.50"},{"1":"F","2":"18.00"},{"1":"F","2":"21.00"},{"1":"F","2":"19.50"},{"1":"F","2":"20.00"},{"1":"F","2":"19.00"},{"1":"F","2":"21.50"},{"1":"F","2":"18.00"},{"1":"F","2":"19.00"},{"1":"F","2":"19.50"},{"1":"F","2":"20.00"},{"1":"F","2":"22.50"},{"1":"F","2":"21.00"},{"1":"F","2":"18.00"},{"1":"F","2":"22.00"},{"1":"F","2":"18.50"},{"1":"F","2":"19.00"},{"1":"F","2":"22.00"},{"1":"F","2":"12.50"},{"1":"F","2":"18.00"},{"1":"F","2":"20.50"},{"1":"F","2":"19.00"},{"1":"F","2":"20.00"},{"1":"F","2":"21.00"},{"1":"F","2":"19.00"},{"1":"F","2":"19.00"},{"1":"F","2":"21.00"},{"1":"F","2":"18.50"},{"1":"F","2":"19.00"},{"1":"F","2":"21.50"},{"1":"F","2":"21.50"},{"1":"F","2":"23.00"},{"1":"F","2":"23.25"},{"1":"F","2":"20.00"},{"1":"F","2":"18.80"},{"1":"F","2":"21.00"},{"1":"F","2":"17.00"},{"1":"F","2":"21.00"},{"1":"F","2":"20.00"},{"1":"F","2":"20.50"},{"1":"F","2":"20.00"},{"1":"F","2":"19.50"},{"1":"F","2":"21.00"},{"1":"F","2":"21.00"},{"1":"F","2":"20.00"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>There are 103 females. From these we need to take a “large” number of bootstrap samples to get a sense of how the mean handspan of the females varies:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">457299</span>)</span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(<span class="at">sim =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb98-3"><a href="#cb98-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb98-4"><a href="#cb98-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">the_sample =</span> <span class="fu">list</span>(<span class="fu">sample</span>(females<span class="sc">$</span>handspan, <span class="at">replace =</span> <span class="cn">TRUE</span>))) <span class="sc">%&gt;%</span> </span>
<span id="cb98-5"><a href="#cb98-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">the_mean =</span> <span class="fu">mean</span>(the_sample)) <span class="ot">-&gt;</span> d</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then we make a histogram of the bootstrap sampling distribution of the sample mean for the females:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> the_mean)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="two-sample-inference_files/figure-html/handspan-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>I don’t know what you think of this. There are a few more extreme values than I would like, and it looks otherwise a bit left-skewed to me. But maybe I am worrying too much.</p>
<p>The males one works exactly the same way:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a>span <span class="sc">%&gt;%</span> <span class="fu">filter</span>(sex<span class="sc">==</span><span class="st">"M"</span>) <span class="ot">-&gt;</span> males</span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(<span class="at">sim =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb100-3"><a href="#cb100-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb100-4"><a href="#cb100-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">the_sample =</span> <span class="fu">list</span>(<span class="fu">sample</span>(males<span class="sc">$</span>handspan, <span class="at">replace =</span> <span class="cn">TRUE</span>))) <span class="sc">%&gt;%</span> </span>
<span id="cb100-5"><a href="#cb100-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">the_mean =</span> <span class="fu">mean</span>(the_sample)) <span class="ot">-&gt;</span> d</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> the_mean)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="two-sample-inference_files/figure-html/handspan-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>There is a similar story here. I think these are good enough overall, and so I am happy with the two-sample <span class="math inline">\(t\)</span>-test, but it is not as clear-cut as I was expecting.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</section>
<section id="the-anchoring-effect-australia-vs-us-1" class="level2" data-number="5.14">
<h2 data-number="5.14" class="anchored" data-anchor-id="the-anchoring-effect-australia-vs-us-1"><span class="header-section-number">5.14</span> The anchoring effect: Australia vs US</h2>
<p>Two groups of students (in a class at a American university) were asked what they thought the population of Canada was. (The correct answer at the time was just over 30 million.) Some of the students, before having to answer this, were told that the population of the United States was about 270 million. The other students in the class were told that the population of Australia was about 18 million. The data are in <a href="http://ritsokiguess.site/datafiles/anchoring.csv">http://ritsokiguess.site/datafiles/anchoring.csv</a>. The first column contains the country whose population the student was told, and the second contains the student’s guess at the population of Canada.</p>
<p>You might wonder how being told the population of an unrelated country would have any impact on a student’s guess at the population of Canada. Psychology says it does: it’s called the <em>anchoring effect</em>, and the idea is that the number mentioned first acts as an “anchor”: a person’s guess will be closer to the anchor than it would have been otherwise. In this case, that would mean that the guesses for the students given the US as an anchor will be higher than for the students given Australia as an anchor. We are interested in seeing whether there is evidence for that here.</p>
<ol type="a">
<li>Read in and display (some of) the data.</li>
</ol>
<p>Solution</p>
<p>I made it as easy as I could:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a>my_url <span class="ot">&lt;-</span> <span class="st">"http://ritsokiguess.site/datafiles/anchoring.csv"</span></span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a>canada <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(my_url)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 21 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): anchor
dbl (1): estimate

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a>canada</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["anchor"],"name":[1],"type":["chr"],"align":["left"]},{"label":["estimate"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"US","2":"20.0"},{"1":"US","2":"90.0"},{"1":"US","2":"1.5"},{"1":"US","2":"100.0"},{"1":"US","2":"132.0"},{"1":"US","2":"150.0"},{"1":"US","2":"130.0"},{"1":"US","2":"40.0"},{"1":"US","2":"200.0"},{"1":"US","2":"20.0"},{"1":"australia","2":"12.0"},{"1":"australia","2":"20.0"},{"1":"australia","2":"10.0"},{"1":"australia","2":"81.0"},{"1":"australia","2":"15.0"},{"1":"australia","2":"20.0"},{"1":"australia","2":"30.0"},{"1":"australia","2":"20.0"},{"1":"australia","2":"9.0"},{"1":"australia","2":"10.0"},{"1":"australia","2":"20.0"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>You might need to scroll down to see that both “anchor” countries are indeed represented.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="2" type="a">
<li>Draw a suitable graph of these data.</li>
</ol>
<p>Solution</p>
<p>One categorical variable and one quantitative one, so a boxplot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(canada, <span class="fu">aes</span>(<span class="at">x =</span> anchor, <span class="at">y =</span> estimate)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="two-sample-inference_files/figure-html/ozvus-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="3" type="a">
<li>Explain briefly why a Welch <span class="math inline">\(t\)</span>-test would be better than a pooled <span class="math inline">\(t\)</span>-test in this case.</li>
</ol>
<p>Solution</p>
<p>The decision between these two tests lies in whether you think the two groups have equal spread (variance, strictly). Here, the spread for the US group is much larger than for the Australia group, even taking into account the big outlier in the latter group. Since the spreads are different, we should do a Welch <span class="math inline">\(t\)</span>-test rather than a pooled one.</p>
<p>Make sure you answer the question I asked, not the one you think I should have asked.</p>
<p>There is a separate question about whether the groups are close enough to normal, but I wasn’t asking about that here. I was asking: <em>given</em> that we have decided to do some kind of <span class="math inline">\(t\)</span>-test, why is the Welch one better than the pooled one? I am not asking whether we should be doing any kind of <span class="math inline">\(t\)</span>-test at all; if I had, you could <em>then</em> reasonably talk about the outlier in the Australia group, and other possible skewness in its distribution, but that’s not what I asked about.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="4" type="a">
<li>Run a suitable Welch <span class="math inline">\(t\)</span>-test and display the output.</li>
</ol>
<p>Solution</p>
<p>The word “suitable” is a hint that you may have to think a bit about how you run the test. If the anchoring effect is real, the mean of the guesses for the students told the population of the US will be higher on average than for those told the population of Australia, so we want a one-sided alternative. Australia is before the US alphabetically, so the alternative has to be <code>less</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(estimate<span class="sc">~</span>anchor, <span class="at">data =</span> canada, <span class="at">alternative =</span> <span class="st">"less"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  estimate by anchor
t = -3.0261, df = 10.558, p-value = 0.006019
alternative hypothesis: true difference in means between group australia and group US is less than 0
95 percent confidence interval:
      -Inf -26.63839
sample estimates:
mean in group australia        mean in group US 
               22.45455                88.35000 </code></pre>
</div>
</div>
<p>Note that the Welch test is the default, so you don’t have to do anything special to get it. Your output will tell you that a Welch test is what you have. It’s if you want a <em>pooled</em> test that you have to ask for it specifically (with <code>var.equal = TRUE</code>).</p>
<p>If you get a P-value close to 1, this is often an indication that you have the alternative the wrong way around.</p>
<p><span class="math inline">\(\blacksquare\)</span></p>
<ol start="5" type="a">
<li>What do you conclude from your test, in the context of the data?</li>
</ol>
<p>Solution</p>
<p>The P-value is definitely less than 0.05, so we reject the null hypothesis (which says that the mean guess is the same regardless of the anchor the student was given). So we have evidence that the mean guess is higher for the students who were given the US population first.</p>
<p>Extra 1: this is perhaps the place to think about what effect that outlier in the <code>australia</code> group might have had. Since it is a high outlier, its effect will be to make the the <code>australia</code> mean higher than it would have been otherwise, and therefore to make the two group means closer together. Despite this, the difference still came out strongly significant, so that we can be <em>even more sure than the P-value says</em> that there is a real difference between the means of estimates of the population of Canada. (To say it differently, if the outlier had not been there, the difference in means would have been even bigger and thus even more significant.)</p>
<p>Extra 2: if you are still worried about doing a two-sample <span class="math inline">\(t\)</span>-test here, you might consider looking at the bootstrapped sampling distribution of the sample mean of the <code>australia</code> group:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a>canada <span class="sc">%&gt;%</span> <span class="fu">filter</span>(anchor <span class="sc">==</span> <span class="st">"australia"</span>) <span class="ot">-&gt;</span> oz</span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(<span class="at">sim =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb108-3"><a href="#cb108-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb108-4"><a href="#cb108-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">the_sample =</span> <span class="fu">list</span>(<span class="fu">sample</span>(oz<span class="sc">$</span>estimate, <span class="at">replace =</span> <span class="cn">TRUE</span>))) <span class="sc">%&gt;%</span> </span>
<span id="cb108-5"><a href="#cb108-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">the_mean =</span> <span class="fu">mean</span>(the_sample)) <span class="sc">%&gt;%</span> </span>
<span id="cb108-6"><a href="#cb108-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> the_mean)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="two-sample-inference_files/figure-html/ozvus-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This is indeed skewed to the right (though, with 11 observations, not nearly so non-normal as the original data), and so the P-value we got from the <span class="math inline">\(t\)</span>-test may not be reliable. But, as discussed in Extra 1, the “correct” P-value is, if anything, <em>even smaller</em> than the one we got, and so the conclusion we drew earlier (that there is a significant anchoring effect) is not going to change.</p>
<p>Extra 3: looking even further ahead, there is a test that definitely <em>does</em> apply here, called Mood’s Median Test. You won’t have installed the package yet, so this won’t work for you just yet (<a href="http://ritsokiguess.site/STAC33/inference_5_R_slides.pdf">read ahead</a> if you want to learn more), but here’s how it goes:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(smmr)</span>
<span id="cb109-2"><a href="#cb109-2" aria-hidden="true" tabindex="-1"></a><span class="fu">median_test</span>(canada, estimate, anchor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$table
           above
group       above below
  australia     2     5
  US            7     1

$test
       what      value
1 statistic 5.40178571
2        df 1.00000000
3   P-value 0.02011616</code></pre>
</div>
</div>
<p>This does (as it is written) a two-sided test, because it can also be used for comparing more than two groups. Since we want a one-sided test here, you can (i) check that we are on the correct side (we are)<a href="#fn12" class="footnote-ref" id="fnref12" role="doc-noteref"><sup>12</sup></a> (ii) halve the P-value to get 0.010.</p>
<p>This is a P-value you can trust. It is not smaller than the <span class="math inline">\(t\)</span>-test one, perhaps because this test is less powerful than the <span class="math inline">\(t\)</span>-test in most cases.<a href="#fn13" class="footnote-ref" id="fnref13" role="doc-noteref"><sup>13</sup></a></p>
<p><span class="math inline">\(\blacksquare\)</span></p>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Mine is rather prosaically called <code>Downloads</code>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>This was not sexism, but a recognition that boys and girls will be of different heights for reasons unrelated to diet. Doing it this way makes the analysis simpler.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Mine is rather prosaically called <code>Downloads</code>.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Let me know if you have more success than I did.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>A Word or Excel document has all kinds of formatting information hidden in the file as well as the text that you see on the screen.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>I wrote this question a long time ago, back when I thought that <code>facet_grid</code> was the only way to do facets. Now, I would use <code>facet_wrap</code>. See the discussion about <code>facet_wrap</code> near the bottom.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>You might have a second categorical variable by which you want to arrange the facets left and right, and that would go where the dot is.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>I took out the <code>ncol</code> since that confuses the explanation here.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>Google defines this as meaning “outstandingly bad, shocking”.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p>This means that I would expect to reject a null hypothesis of equal means, but I get ahead of myself.<a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn11"><p>This was not sexism, but a recognition that boys and girls will be of different heights for reasons unrelated to diet. Doing it this way makes the analysis simpler.<a href="#fnref11" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn12"><p>The test works by comparing the data values in each group to the overall median. The students who were given Australia as an anchor mostly guessed below the overall median, and the students given the US as an anchor mostly guessed above.<a href="#fnref12" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn13"><p>It uses the data less efficiently than the t-test; it just counts the number of values above and below the overall median in each group, rather than using the actual numbers to compute means.<a href="#fnref13" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./one-sample-inference.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">One-sample inference</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./power.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Power and sample size</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>