{
  "hash": "ebf98984242050f8dd22fa5eeaea0a35",
  "result": {
    "markdown": "# Functions\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n:::\n\n\n\n\n::: {.cell}\n\n:::\n\n\n##  Making some R functions\n\n\n Let's write some simple R functions to convert temperatures,\nand later to play with text.\n\n\n\n(a) A temperature in Celsius is converted to one in Kelvin by\nadding 273.15. (A temperature of $-273.15$ Celsius, 0 Kelvin, is the \"absolute zero\" \ntemperature that nothing can be colder than.) Write a\nfunction called `c_to_k` that converts an input Celsius\ntemperature to one in Kelvin, and test that it works.\n\n\n(b) Write a function to convert a Fahrenheit temperature to\nCelsius. The way you do that is to subtract 32 and then multiply by\n$5/9$. \n\n\n(c) *Using the functions you already wrote*, write a function\nto convert an input Fahrenheit temperature to Kelvin.\n\n\n(d) Rewrite your Fahrenheit-to-Celsius convertor to take a\nsuitable default value and check that it works as a default.\n\n\n(e) What happens if you feed your Fahrenheit-to-Celsius convertor\na *vector* of Fahrenheit temperatures? What if you use it in a\n`mutate`? \n\n\n(f) Write another function called `wrap` that takes two\narguments: a piece of text called `text`, which defaults to\n`hello`, and another piece of text called `outside`,\nwhich defaults to `*`. The function returns `text`\nwith the text `outside` placed before and after, so that\ncalling the function with the defaults should return\n`*hello*`. To do this, you can use `str_c` from\n`stringr` (loaded with the `tidyverse`) which places\nits text arguments side by side and glues them together into one\npiece of text.  Test your function briefly.\n\n\n(g) What happens if you want to change the default\n`outside` but use the default for `text`? How do you\nmake sure that happens? Explore.\n\n\n(h) What happens if you feed your function `wrap` a vector\nfor either of its arguments? What about if you use it in a\n`mutate`? \n\n\n\n\n\n\n\n\n##  The Collatz sequence\n\n\n The Collatz sequence is a sequence of integers $x_1, x_2,\n\\ldots$ defined in a\ndeceptively simple way: if $x_n$ is the current term of the sequence,\nthen $x_{n+1}$ is defined as $x_n/2$ if $x_n$ is even, and $3x_n+1$ if\n$x_n$ is odd.\nWe are interested in understanding how this sequence\nbehaves; for example, what happens to it as $n$ gets large, for\ndifferent choices of the first term $x_1$? We will explore this\nnumerically with R; the ambitious among you might like to look into\nthe mathematics of it.\n\n\n\n(a) What happens to the sequence when it reaches 4? What would be\na sensible way of defining where it ends? Explain briefly.\n\n\n(b) Write an R function called `is_odd` that returns\n`TRUE` if its input is an odd number and `FALSE` if it\nis even (you can assume that the input is an integer and not a\ndecimal number). To do *that*, you can use the function `%%` where \n`a %% b` is the remainder when `a` is divided by\n`b`. To think about oddness or evenness, consider the\nremainder when you divide by 2.\n\n\n(c) Write an R function called\n`hotpo1`^[*Hotpo* is short for half or triple-plus-one.] \nthat takes an\ninteger as input and returns the next number in the Collatz\nsequence. To do this, use the function you just wrote that\ndetermines whether a number is even or odd.\n\n\n(d) Now write a function `hotpo` that will return the whole\nCollatz sequence for an input $x_1$. For this, assume that you will\neventually get to 1.\n\n\n(e) Write two (very small) functions that take an entire sequence\nas input and return (i) the length of the sequence and (ii) the\nmaximum value it attains.\n\n\n(f) Make a data frame consisting of the values 11 through 20, and,\nusing `tidyverse` ideas, obtain a data frame containing the\nCollatz sequences starting at each of those values, along with their\nlengths and their maximum values. Which sequence is longest? Which\none goes up highest?\n\n\n\n\n## Coefficient of Variation\n\n The coefficient of variation of a vector `x` is defined as the standard deviation of `x` divided by the mean of `x`. \n\n\n\n(a) Write a function called `cv` that calculates the coefficient of variation of its input and returns the result. You should use base R's functions that reliably compute the pieces that you need.\n\n\n\n(b) Use your function to find the coefficient of variation of the set of integers 1 through 5.\n\n\n\n\n(c) Define a vector as follows:\n\n::: {.cell}\n\n```{.r .cell-code}\nv <- c(-2.8, -1.8, -0.8, 1.2, 4.2)\n```\n:::\n\nWhat is its coefficient of variation, according to your function? Does this make sense? Why did this happen? Explain briefly.\n\n\n\n(d) Most people only calculate a coefficient of variation if there are no negative numbers. Rewrite your function so that it gives an error if there are any negative numbers in the input, and test it with the vector `v` above. Hint: you might need to add `#|error=TRUE` as the first line of your code chunk, to allow your document to render properly.\n\n\n\n\n\n\n\n## Rescaling\n\n Suppose we have this vector of values:\n\n::: {.cell}\n\n```{.r .cell-code}\nz <- c(10, 14, 11)\nz\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 10 14 11\n```\n:::\n:::\n\nWe want to scale these so that the smallest value is 0 and the largest is 1. We are going to be doing this a lot, so we are going to write a function that will work for any input.\n\n\n\n(a) Using a copy of my `z`, work out `min(z)` and `max(z)`. What do they do? Explain (very) briefly.\n\n\n\n\n(b) What do these lines of code do, using the same `z` that I had? Run them and see, and describe briefly what `s` contains.\n\n::: {.cell}\n\n```{.r .cell-code}\nlo <- min(z)\nhi <- max(z)\ns <- (z - lo) / (hi - lo)\ns\n```\n:::\n\n\n\n\n\n\n(c) Write a function called `rescale` that implements the calculation above, for any input vector called `x`. (Note that I changed the name.)\n\n\n\n(d) Test your function on my `z`, and on another vector of your choosing. Explain briefly why the answer you get from your vector makes sense.\n\n\n\n(e) What happens if your input to `rescale` is a vector of numbers all the same? Give an example. Rewrite your function to intercept this case and give a helpful error message.\n\n\n\n(f) Make a dataframe (containing any numeric values), and in it create a new column containing the rescaled version of one of its columns, using your function. Show your result.\n\n\n\n(g) We might want to rescale the input not to be between 0 and 1, but between two values `a` and `b` that we specify as input. If `a` and/or `b` are not given, we want to use the values 0 for `a` and 1 for `b`. Rewrite your function to rescale the input to be between `a` and `b` instead of 0 and 1. Hint: allow your function to produce values between 0 and 1 as before, and then note that if all the values in a vector `s` are between 0 and 1, then all the values in `a+(b-a)*s`\nare between $a$ and $b$.\n\n\n\n(h) Test your new function two or more times, on input where you know or can guess what the output is going to be. In each case, explain briefly why your output makes sense.\n\n\n\n\n\n\n\n\n\nMy solutions follow:\n\n\n\n\n##  Making some R functions\n\n\n Let's write some simple R functions to convert temperatures,\nand later to play with text.\n\n\n\n(a) A temperature in Celsius is converted to one in Kelvin by\nadding 273.15. (A temperature of $-273.15$ Celsius, 0 Kelvin, is the \"absolute zero\" \ntemperature that nothing can be colder than.) Write a\nfunction called `c_to_k` that converts an input Celsius\ntemperature to one in Kelvin, and test that it works.\n\nSolution\n\n\nThis is mostly an exercise in structuring your function\ncorrectly. Let's call the input `C` (uppercase C, since\nlowercase c has a special meaning to R):\n\n::: {.cell}\n\n```{.r .cell-code}\nc_to_k <- function(C) {\n  C + 273.15\n}\nc_to_k(0)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 273.15\n```\n:::\n\n```{.r .cell-code}\nc_to_k(20)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 293.15\n```\n:::\n:::\n\n     \n\nThis is the simplest way to do it: the last line of the function, if\ncalculated but not saved, is the value that gets returned to the\noutside world. The checks suggest that it worked.\n\nIf you're used to Python or similar, you might prefer to calculate the\nvalue to be returned and then return it. You can do that in R too:\n\n::: {.cell}\n\n```{.r .cell-code}\nc_to_k <- function(C) {\n  K <- C + 273.15\n  return(K)\n}\nc_to_k(0)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 273.15\n```\n:::\n\n```{.r .cell-code}\nc_to_k(20)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 293.15\n```\n:::\n:::\n\n \n\nThat works just as well, and for the rest of this question, you can go\neither way.^[R style is to use the last line of the function  for the return value, unless you are jumping out of the function  before the end, in which case use `return`.]\n\n$\\blacksquare$\n\n(b) Write a function to convert a Fahrenheit temperature to\nCelsius. The way you do that is to subtract 32 and then multiply by\n$5/9$. \n\nSolution\n\n\nOn the model of the previous one, we should call this\n`f_to_c`. I'm going to return the last line, but you can\nsave the calculated value and return that instead:\n\n::: {.cell}\n\n```{.r .cell-code}\nf_to_c <- function(F) {\n  (F - 32) * 5 / 9\n}\nf_to_c(32)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n\n```{.r .cell-code}\nf_to_c(50)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 10\n```\n:::\n\n```{.r .cell-code}\nf_to_c(68)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 20\n```\n:::\n:::\n\n     \n\nAmericans are very good at saying things like \"temperatures in the 50s\", \nwhich don't mean much to me, so I like to have benchmarks to\nwork with: these are the Fahrenheit versions of 0, 10, and 20 Celsius.\n\nThus \"in the 50s\" means \"between about 10 and 15 Celsius\".\n\n$\\blacksquare$\n\n(c) *Using the functions you already wrote*, write a function\nto convert an input Fahrenheit temperature to Kelvin.\n\nSolution\n\n\nThis implies that you can piggy-back on the functions you just\nwrote, which goes as below. First you convert the Fahrenheit to\nCelsius, and then you convert *that* to Kelvin. (This is less\nerror-prone than trying to use algebra to get a formula for this\nconversion and then implementing that):\n\n::: {.cell}\n\n```{.r .cell-code}\nf_to_k <- function(F) {\n  C <- f_to_c(F)\n  K <- c_to_k(C)\n  return(K)\n}\nf_to_k(32)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 273.15\n```\n:::\n\n```{.r .cell-code}\nf_to_k(68)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 293.15\n```\n:::\n:::\n\n     \n\nThese check because in Celsius they are 0 and 20 and we found the\nKelvin equivalents of those to be these values earlier.\n\nI wrote this one with a `return` because I thought it made the\nstructure clearer: run one function, save the result, run another\nfunction, save the result, then return what you've got.\n\n$\\blacksquare$\n\n(d) Rewrite your Fahrenheit-to-Celsius convertor to take a\nsuitable default value and check that it works as a default.\n\nSolution\n\n\nYou can choose any default you like. I'll take a default of 68\n(what I would call \"a nice day\"):\n\n::: {.cell}\n\n```{.r .cell-code}\nf_to_c <- function(F = 68) {\n  (F - 32) * 5 / 9\n}\nf_to_c(68)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 20\n```\n:::\n\n```{.r .cell-code}\nf_to_c()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 20\n```\n:::\n:::\n\n     \n\nThe change is in the top line of the function. You see the result: if\nwe run it without an input, we get the same answer as if the input had\nbeen 68.\n\n$\\blacksquare$\n\n(e) What happens if you feed your Fahrenheit-to-Celsius convertor\na *vector* of Fahrenheit temperatures? What if you use it in a\n`mutate`? \n\nSolution\n\n\nTry it and see:\n\n::: {.cell}\n\n```{.r .cell-code}\ntemps <- seq(30, 80, 10)\ntemps\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 30 40 50 60 70 80\n```\n:::\n\n```{.r .cell-code}\nf_to_c(temps)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -1.111111  4.444444 10.000000 15.555556 21.111111 26.666667\n```\n:::\n:::\n\n     \n\nEach of the Fahrenheit temperatures gets converted into a Celsius\none. This is perhaps more useful in a data frame, thus:\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(temps = seq(30, 80, 10)) %>%\n  mutate(celsius = f_to_c(temps))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"temps\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"celsius\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"30\",\"2\":\"-1.111111\"},{\"1\":\"40\",\"2\":\"4.444444\"},{\"1\":\"50\",\"2\":\"10.000000\"},{\"1\":\"60\",\"2\":\"15.555556\"},{\"1\":\"70\",\"2\":\"21.111111\"},{\"1\":\"80\",\"2\":\"26.666667\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n \n\nAll the temperatures are side-by-side with their equivalents.\n\nHere's another way to do the above:\n\n::: {.cell}\n\n```{.r .cell-code}\ntemps <- seq(30, 80, 10)\ntemps %>%\n  enframe(value = \"fahrenheit\") %>%\n  mutate(celsius = f_to_c(temps))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"name\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"fahrenheit\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"celsius\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"1\",\"2\":\"30\",\"3\":\"-1.111111\"},{\"1\":\"2\",\"2\":\"40\",\"3\":\"4.444444\"},{\"1\":\"3\",\"2\":\"50\",\"3\":\"10.000000\"},{\"1\":\"4\",\"2\":\"60\",\"3\":\"15.555556\"},{\"1\":\"5\",\"2\":\"70\",\"3\":\"21.111111\"},{\"1\":\"6\",\"2\":\"80\",\"3\":\"26.666667\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n \n\n`enframe` creates a two-column data frame out of a vector (like\n`temps`). A vector can have \"names\", in which case they'll be\nused as the `name` column; the values will go in a column\ncalled `value` unless you rename it, as I did.\n\n$\\blacksquare$\n\n(f) Write another function called `wrap` that takes two\narguments: a piece of text called `text`, which defaults to\n`hello`, and another piece of text called `outside`,\nwhich defaults to `*`. The function returns `text`\nwith the text `outside` placed before and after, so that\ncalling the function with the defaults should return\n`*hello*`. To do this, you can use `str_c` from\n`stringr` (loaded with the `tidyverse`) which places\nits text arguments side by side and glues them together into one\npiece of text.  Test your function briefly.\n\nSolution\n\n\nThis:\n\n::: {.cell}\n\n```{.r .cell-code}\nwrap <- function(text = \"hello\", outside = \"*\") {\n  str_c(outside, text, outside)\n}\n```\n:::\n\n     \n\nI can run this with the defaults:\n\n::: {.cell}\n\n```{.r .cell-code}\nwrap()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"*hello*\"\n```\n:::\n:::\n\n \n\nor with text of my choosing:\n\n::: {.cell}\n\n```{.r .cell-code}\nwrap(\"goodbye\", \"_\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"_goodbye_\"\n```\n:::\n:::\n\n \n\nI think that's what I meant by \"test briefly\".\n\n$\\blacksquare$\n\n(g) What happens if you want to change the default\n`outside` but use the default for `text`? How do you\nmake sure that happens? Explore.\n\nSolution\n\n\nThe obvious thing is this, which doesn't work:\n\n::: {.cell}\n\n```{.r .cell-code}\nwrap(\"!\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"*!*\"\n```\n:::\n:::\n\n     \n\nThis takes *`text`* to be `!`, and `outside`\nto be the default. How do we get `outside` to be `!`\ninstead? The key is to specify the input by name:\n\n::: {.cell}\n\n```{.r .cell-code}\nwrap(outside = \"!\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"!hello!\"\n```\n:::\n:::\n\n \n\nThis correctly uses the default for `text`.\n\nIf you specify inputs without names, they are\ntaken to be in the order that they appear in the function\ndefinition. As soon as they get out of order, which typically happens\nby using the default for something early in the list, as we did here\nfor `text`, you have to specify names for anything that comes\nafter that. These are the names you put on the function's top line.\n\nYou can always use names:\n\n::: {.cell}\n\n```{.r .cell-code}\nwrap(text = \"thing\", outside = \"**\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"**thing**\"\n```\n:::\n:::\n\n \n\nand if you use names, they don't even have to be in order:\n\n::: {.cell}\n\n```{.r .cell-code}\nwrap(outside = \"!?\", text = \"fred\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"!?fred!?\"\n```\n:::\n:::\n\n \n$\\blacksquare$\n\n(h) What happens if you feed your function `wrap` a vector\nfor either of its arguments? What about if you use it in a\n`mutate`? \n\nSolution\n\n\nLet's try:\n\n::: {.cell}\n\n```{.r .cell-code}\nmytext <- c(\"a\", \"b\", \"c\")\nwrap(text = mytext)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"*a*\" \"*b*\" \"*c*\"\n```\n:::\n:::\n\n     \n\n::: {.cell}\n\n```{.r .cell-code}\nmyout <- c(\"*\", \"!\")\nwrap(outside = myout)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"*hello*\" \"!hello!\"\n```\n:::\n:::\n\n \n\nIf one of the inputs is a vector, the other one gets \"recycled\" as\nmany times as the vector is long. What if they're both vectors?\n\n::: {.cell}\n\n```{.r .cell-code}\nmytext2 <- c(\"a\", \"b\", \"c\", \"d\")\nwrap(mytext2, myout)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in `str_c()`:\n! Can't recycle `..1` (size 2) to match `..2` (size 4).\n```\n:::\n:::\n\nThis gives an error because `str_c` won't let you recycle things that are both vectors.\n \nThe `mutate` thing is easier, because all the columns in a data\nframe have to be the same length. `LETTERS` is a vector with\nthe uppercase letters in it:\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(mytext = LETTERS[1:6], myout = c(\"*\", \"**\", \"!\", \"!!\", \"_\", \"__\")) %>%\n  mutate(newthing = wrap(mytext, myout))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"mytext\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"myout\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"newthing\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"A\",\"2\":\"*\",\"3\":\"*A*\"},{\"1\":\"B\",\"2\":\"**\",\"3\":\"**B**\"},{\"1\":\"C\",\"2\":\"!\",\"3\":\"!C!\"},{\"1\":\"D\",\"2\":\"!!\",\"3\":\"!!D!!\"},{\"1\":\"E\",\"2\":\"_\",\"3\":\"_E_\"},{\"1\":\"F\",\"2\":\"__\",\"3\":\"__F__\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n$\\blacksquare$\n\n\n\n\n\n\n\n##  The Collatz sequence\n\n\n The Collatz sequence is a sequence of integers $x_1, x_2,\n\\ldots$ defined in a\ndeceptively simple way: if $x_n$ is the current term of the sequence,\nthen $x_{n+1}$ is defined as $x_n/2$ if $x_n$ is even, and $3x_n+1$ if\n$x_n$ is odd.\nWe are interested in understanding how this sequence\nbehaves; for example, what happens to it as $n$ gets large, for\ndifferent choices of the first term $x_1$? We will explore this\nnumerically with R; the ambitious among you might like to look into\nthe mathematics of it.\n\n\n\n(a) What happens to the sequence when it reaches 4? What would be\na sensible way of defining where it ends? Explain briefly.\n\nSolution\n\n\nWhen the sequence reaches 4 (that is, when its current term is 4),\nthe next term is 2 and the one after that is 1. Then the following\nterm is 4 again ($(3 \\times 1)+1$) and then it repeats\nindefinitely, $4, 2, 1, 4, 2, 1, \\ldots$. \nI think a sensible way to define where the sequence ends is to say\n\"when it reaches 1\", since if you start at 2 you'll never reach\n4 (so \"when it reaches 4\" won't work), and it seems at least\nplausible that it will hit the cycle 4, 2, 1 sometime.\n\n$\\blacksquare$\n\n(b) Write an R function called `is_odd` that returns\n`TRUE` if its input is an odd number and `FALSE` if it\nis even (you can assume that the input is an integer and not a\ndecimal number). To do *that*, you can use the function `%%` where \n`a %% b` is the remainder when `a` is divided by\n`b`. To think about oddness or evenness, consider the\nremainder when you divide by 2.\n\nSolution\n\n\nLet's try this out. For example, 5 is odd and 6 is even, so\n\n::: {.cell}\n\n```{.r .cell-code}\n5 %% 2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1\n```\n:::\n\n```{.r .cell-code}\n6 %% 2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n:::\n\n     \n\nWhen a number is odd, its remainder on dividing by 2 is 1, and when\neven, the remainder is 0. There is an additional shortcut here in that\n1 is the numeric value of `TRUE` and 0 of `FALSE`, so\nall we have to do is calculate the remainder on dividing by 2, turn it\ninto a `logical`, and return it:\n\n::: {.cell}\n\n```{.r .cell-code}\nis_odd <- function(x) {\n  r <- x %% 2\n  as.logical(r)\n}\n```\n:::\n\n \n\nYou probably haven't seen `as.logical` before, but it's the\nsame idea as `as.numeric`: turn something that looks like a\n`TRUE` or `FALSE` into something that actually\n*is*. \n\nWe should test it:\n\n::: {.cell}\n\n```{.r .cell-code}\nis_odd(19)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] TRUE\n```\n:::\n\n```{.r .cell-code}\nis_odd(12)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] FALSE\n```\n:::\n\n```{.r .cell-code}\nis_odd(0)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] FALSE\n```\n:::\n:::\n\n \n\n0 is usually considered an even number, so this is good.\n\n$\\blacksquare$\n\n(c) Write an R function called\n`hotpo1`^[*Hotpo* is short for half or triple-plus-one.] \nthat takes an\ninteger as input and returns the next number in the Collatz\nsequence. To do this, use the function you just wrote that\ndetermines whether a number is even or odd.\n\nSolution\n\n\nThe logic is \"if the input is odd, return 3 times it plus 1, otherwise return half of it\". \nThe R structure is an\n`if-then-else`: \n\n::: {.cell}\n\n```{.r .cell-code}\nhotpo1 <- function(x) {\n  if (is_odd(x)) 3 * x + 1 else x / 2\n}\n```\n:::\n\n     \n\nIn R, the condition that is tested goes in brackets, and then if the\nvalue-if-true and the value-if-false are single statements, you just\ntype them. (If they are more complicated than that, you put them in\ncurly brackets.) Now you see the value of writing `is_odd`\nearlier; this code almost looks like the English-language description\nof the sequence. If we had not written `is_odd` before, the\ncondition would have looked something like \n\n::: {.cell}\n\n```{.r .cell-code}\nif (x %% 2 == 1) 3 * x + 1 else x / 2\n```\n:::\n\n \n\nwhich would have been a lot harder to read.\n\nAll right, let's try that out:\n\n::: {.cell}\n\n```{.r .cell-code}\nhotpo1(4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2\n```\n:::\n\n```{.r .cell-code}\nhotpo1(7)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 22\n```\n:::\n\n```{.r .cell-code}\nhotpo1(24)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 12\n```\n:::\n:::\n\n \n\nThat looks all right so far.\n\n$\\blacksquare$\n\n(d) Now write a function `hotpo` that will return the whole\nCollatz sequence for an input $x_1$. For this, assume that you will\neventually get to 1.\n\nSolution\n\n\nThis is a loop, but not a `for` loop (or something that we\ncould do `rowwise`), because we don't know how many\ntimes we have to go around. This is the kind of thing that we\nshould use a `while` loop for: \n\"keep going while a condition is true\".\nIn this case, we should keep going if we haven't reached 1 yet. If\nwe haven't reached 1, we should generate the next value of the\nsequence and glue it onto what we have so far. To initialize the\nsequence, we start with the input value. There is an R trick to\nglue a value onto the sequence, which is to use `c` with a\nvector and a value, and save it back into the vector:\n\n::: {.cell}\n\n```{.r .cell-code}\nhotpo <- function(x) {\n  sequence <- x\n  term <- x\n  while (term > 1) {\n    term <- hotpo1(term)\n    sequence <- c(sequence, term)\n  }\n  sequence\n}\n```\n:::\n\n     \nI use `term` to hold the current term of the sequence, and\noverwrite it with the next one (since I don't need the old one any\nmore). \n\nDoes it work?\n\n::: {.cell}\n\n```{.r .cell-code}\nhotpo(4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 4 2 1\n```\n:::\n\n```{.r .cell-code}\nhotpo(12)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] 12  6  3 10  5 16  8  4  2  1\n```\n:::\n\n```{.r .cell-code}\nhotpo(97)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  [1]   97  292  146   73  220  110   55  166   83  250  125  376  188   94   47\n [16]  142   71  214  107  322  161  484  242  121  364  182   91  274  137  412\n [31]  206  103  310  155  466  233  700  350  175  526  263  790  395 1186  593\n [46] 1780  890  445 1336  668  334  167  502  251  754  377 1132  566  283  850\n [61]  425 1276  638  319  958  479 1438  719 2158 1079 3238 1619 4858 2429 7288\n [76] 3644 1822  911 2734 1367 4102 2051 6154 3077 9232 4616 2308 1154  577 1732\n [91]  866  433 1300  650  325  976  488  244  122   61  184   92   46   23   70\n[106]   35  106   53  160   80   40   20   10    5   16    8    4    2    1\n```\n:::\n:::\n\n \n\n97 is a wild ride, but it does eventually get to 1. \n\nExtra: where I originally saw this, which was \"Metamagical Themas\"\nby Douglas Hofstadter, he was illustrating the programming language\nLisp and the process of recursion, whereby you define a function in\nterms of itself. This one is a natural for that, because the Collatz\nsequence starting at $x$ is $x$ along with the Collatz sequence\nstarting at the next term. For example, if you start at 12, the next\nterm is 6, so that the Collatz sequence starting at 12 is 12 followed by\nthe Collatz sequence starting at 6. There is no dependence any further\nback. You can do recursion in R also; there is no problem with a\nfunction calling itself:\n\n::: {.cell}\n\n```{.r .cell-code}\nhotpo_rec <- function(x) {\n  if (x == 1) 1 else c(x, hotpo_rec(hotpo1(x)))\n}\n```\n:::\n\n \n\nRecursive functions have two parts: a \"base case\" that says how you\nknow you are done (the 1 here), and a \"recursion\" that says how you\nmove to a simpler case, here working out the next term, getting the\nwhole sequence for that, and gluing the input onto the front. It seems\nparadoxical that you define a function in terms of itself, but what\nyou are doing is calling a simpler sequence, in this case one that is\nlength one shorter than the sequence for the original input. Thus, we\nhope,^[Nobody knows whether you *always* get to 1, but also nobody has ever found a case where you don't. Collatz's conjecture, that you will get to 1 eventually, is known to be true for all starting $x_1$ up to some absurdly large number, but not for *all* starting points.]\nwe will eventually reach 1.\n\nDoes it work?\n\n::: {.cell}\n\n```{.r .cell-code}\nhotpo_rec(12)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] 12  6  3 10  5 16  8  4  2  1\n```\n:::\n\n```{.r .cell-code}\nhotpo_rec(97)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  [1]   97  292  146   73  220  110   55  166   83  250  125  376  188   94   47\n [16]  142   71  214  107  322  161  484  242  121  364  182   91  274  137  412\n [31]  206  103  310  155  466  233  700  350  175  526  263  790  395 1186  593\n [46] 1780  890  445 1336  668  334  167  502  251  754  377 1132  566  283  850\n [61]  425 1276  638  319  958  479 1438  719 2158 1079 3238 1619 4858 2429 7288\n [76] 3644 1822  911 2734 1367 4102 2051 6154 3077 9232 4616 2308 1154  577 1732\n [91]  866  433 1300  650  325  976  488  244  122   61  184   92   46   23   70\n[106]   35  106   53  160   80   40   20   10    5   16    8    4    2    1\n```\n:::\n:::\n\n \n\nIt does.\n\nRecursive functions are often simple to understand, but they are not\nalways very efficient. They can take a lot of memory, because they\nhave to handle the intermediate calls to the function, which they have\nto save to use later (in the case of `hotpo_rec(97)` there are a\nlot of those). Recursive functions are often paired with a technique\ncalled \"memoization\", where each time you calculate the function's\nvalue, you *save* it in another array. The first thing you do in\nthe recursive function is to check whether you already have the\nanswer, in which case you just look it up and return it. It was a lot\nof work here to calculate the sequence from 97, but if we had saved\nthe results, we would already have the answers for 292, 146, 73, 220\nand so on, and getting those later would be a table lookup rather than\nanother recursive calculation.\n\n$\\blacksquare$\n\n(e) Write two (very small) functions that take an entire sequence\nas input and return (i) the length of the sequence and (ii) the\nmaximum value it attains.\n\nSolution\n\n\nThese are both one-liners. Call the input whatever you like:\n\n::: {.cell}\n\n```{.r .cell-code}\nhotpo_len <- function(sequence) length(sequence)\nhotpo_max <- function(sequence) max(sequence)\n```\n:::\n\n \n\nBecause they are one-liners, you don't even need the curly brackets,\nalthough there's no problem if they are there.\n\nTesting:\n\n::: {.cell}\n\n```{.r .cell-code}\nhotpo_len(hotpo(12))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 10\n```\n:::\n\n```{.r .cell-code}\nhotpo_max(hotpo(97))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 9232\n```\n:::\n:::\n\n \n\nThis checks with what we had before.\n\n$\\blacksquare$\n\n(f) Make a data frame consisting of the values 11 through 20, and,\nusing `tidyverse` ideas, obtain a data frame containing the\nCollatz sequences starting at each of those values, along with their\nlengths and their maximum values. Which sequence is longest? Which\none goes up highest?\n\nSolution\n\n\nThis one uses `rowwise` ideas:^[I should have been more careful in my functions to make sure everything was integers, and, in particular, to do integer division by 2 because I knew that this division was going to come out even.] \n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(x = 11:20) %>%\n  rowwise %>% \n  mutate(sequence = list(hotpo(x))) %>%\n  mutate(length = hotpo_len(sequence)) %>%\n  mutate(high = hotpo_max(sequence))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"x\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"sequence\"],\"name\":[2],\"type\":[\"list\"],\"align\":[\"right\"]},{\"label\":[\"length\"],\"name\":[3],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"high\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"11\",\"2\":\"<dbl [15]>\",\"3\":\"15\",\"4\":\"52\"},{\"1\":\"12\",\"2\":\"<dbl [10]>\",\"3\":\"10\",\"4\":\"16\"},{\"1\":\"13\",\"2\":\"<dbl [10]>\",\"3\":\"10\",\"4\":\"40\"},{\"1\":\"14\",\"2\":\"<dbl [18]>\",\"3\":\"18\",\"4\":\"52\"},{\"1\":\"15\",\"2\":\"<dbl [18]>\",\"3\":\"18\",\"4\":\"160\"},{\"1\":\"16\",\"2\":\"<dbl [5]>\",\"3\":\"5\",\"4\":\"16\"},{\"1\":\"17\",\"2\":\"<dbl [13]>\",\"3\":\"13\",\"4\":\"52\"},{\"1\":\"18\",\"2\":\"<dbl [21]>\",\"3\":\"21\",\"4\":\"52\"},{\"1\":\"19\",\"2\":\"<dbl [21]>\",\"3\":\"21\",\"4\":\"88\"},{\"1\":\"20\",\"2\":\"<dbl [8]>\",\"3\":\"8\",\"4\":\"20\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n     \n\nFirst, we obtain a list-column containing the sequences (which is why its calculation needs a `list` around it), then two\nordinary columns of their lengths and their maximum values. \n\nThe sequences for 18 and 19 are the longest, but the sequence for 15\ngoes up the highest.\n\n\n$\\blacksquare$\n\n\n\n## Coefficient of Variation\n\n The coefficient of variation of a vector `x` is defined as the standard deviation of `x` divided by the mean of `x`. \n\n\n\n(a) Write a function called `cv` that calculates the coefficient of variation of its input and returns the result. You should use base R's functions that reliably compute the pieces that you need.\n\nSolution\n\n\nI like to make a function skeleton first to be sure I remember all the pieces. You can do this by making a code chunk, typing `fun`, waiting a moment, and selecting the \"snippet\" that is offered to you. That gives you this, with your cursor on `name`:\n\n::: {.cell}\n\n```{.r .cell-code}\nname <- function(variables) {\n\n}\n```\n:::\n\nGive your function a name (I asked you to use `cv`), hit tab, enter a name like x for the input, hit tab again, and then fill in the body of the function, to end up with something like this:\n\n::: {.cell}\n\n```{.r .cell-code}\ncv <- function(x) {\nmean_x <- mean(x)\nsd_x <- sd(x)\nsd_x/mean_x\n}\n```\n:::\n\nI think this is best, for reasons discussed below.\n\nSome observations:\n\n- in the last line of the function, you calculate something, and that something is the thing that gets returned. You *do not* need to save it in a variable, because then you have to return that variable by having its name alone on the last line.\n- R has a `return()` function, but it is *bad style* to use it to return a value at the end of a function. The time to use it is  when you test something early in the function and want to return early with a value like zero or missing without doing any actual calculation. Looking ahead a bit, you might want to return \"missing\" if the mean is zero *before* dividing by it, which you could do like this, this being *good* style:\n\n::: {.cell}\n\n```{.r .cell-code}\ncv2 <- function(x) {\nmean_x <- mean(x)\nif (mean_x == 0) return(NA)\nsd_x <- sd(x)\nsd_x/mean_x\n}\n```\n:::\n\n- use the built-in `mean` and `sd` rather than trying to roll your own, because they have been tested by many users over a long time and they work. That's what I meant by \"pieces\" in the question.\n\n- you might be tempted to do something like this:\n\n::: {.cell}\n\n```{.r .cell-code}\ncv3 <- function(x) {\nsd(x)/mean(x)\n}\n```\n:::\n\nThis will work, but it is not a good habit to get into, and thus not best as an answer to this question. This one line of code says three things: \"work out the SD of `x`\", \"work out the mean of `x`\", and \"divide them by each other\". It is much clearer, for anyone else reading the code (including yourself in six months when you have forgotten what you were thinking) to have the three things one per line, so that anyone reading the code sees that each line does one thing and what that one thing is. There is a reason why production code and [code golf](https://en.wikipedia.org/wiki/Code_golf) are two very different things. Code that is easy to read is also easy to maintain, either by you or others.\n\n- using something other than `mean` and `sd` as the names of your intermediate results is a good idea because these names are already used by R (as the names of the functions that compute the mean and SD). Redefining names that R uses can make other code behave unpredictably and cause hard-to-find bugs.^[This is something I've done in the past and been bitten by, so I am trying to get myself not to do it any more.]\n\n\n$\\blacksquare$\n\n\n(b) Use your function to find the coefficient of variation of the set of integers 1 through 5.\n\nSolution\n\n\nThis can be as simple as\n\n::: {.cell}\n\n```{.r .cell-code}\ncv(1:5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5270463\n```\n:::\n:::\n\nor, equally good, define this into a vector first:\n\n::: {.cell}\n\n```{.r .cell-code}\ny <- 1:5\ncv(y)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5270463\n```\n:::\n:::\n\nor, displaying a little less understanding, type the five numbers into the vector first (or directly as input to the function):\n\n::: {.cell}\n\n```{.r .cell-code}\ny <- c(1, 2, 3, 4, 5)\ncv(y)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5270463\n```\n:::\n\n```{.r .cell-code}\ncv(c(1, 2, 3, 4, 5))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5270463\n```\n:::\n:::\n\n\n\n$\\blacksquare$\n\n\n\n(c) Define a vector as follows:\n\n::: {.cell}\n\n```{.r .cell-code}\nv <- c(-2.8, -1.8, -0.8, 1.2, 4.2)\n```\n:::\n\nWhat is its coefficient of variation, according to your function? Does this make sense? Why did this happen? Explain briefly.\n\nSolution\n\n\nTry it and see:\n\n::: {.cell}\n\n```{.r .cell-code}\ncv(v)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 6.248491e+16\n```\n:::\n:::\n\nA very large number, much bigger than any of the data values; with these human-sized numbers, we'd expect a human-sized coefficient of variation as well. \n\nWhat actually happened was that the mean of `v` is this:\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(v)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 4.440892e-17\n```\n:::\n:::\n\nZero, or close enough, so that in calculating the coefficient of variation, we divided by something that was (almost) zero and got a result that was (almost) infinite.^[In computing with decimal numbers, things are almost never exactly zero or exactly infinite; they are very small or very  big. The mean here, which you would calculate to be zero, is less than the so-called machine epsilon, which is about 10 to the minus 16 in R (R works in double precision). A mean that small is, to the computer, indistinguishable from zero. It came out that way because the last value is added to a total that is by that point negative, and so you have a loss of accuracy because of subtracting nearly equal quantities. I learned all about this stuff in my first real computer science course, which I think was a numerical math course, some absurd number of years ago. It looks as if this gets taught in CSCC37 these days.]\n\nThe possibility of getting a zero mean is why most people only calculate a coefficient of variation if all of the numbers are positive, which brings us to the next part:\n\n\n$\\blacksquare$\n\n\n(d) Most people only calculate a coefficient of variation if there are no negative numbers. Rewrite your function so that it gives an error if there are any negative numbers in the input, and test it with the vector `v` above. Hint: you might need to add `#|error=TRUE` as the first line of your code chunk, to allow your document to render properly.\n\nSolution\n\n\nThis is a case for `stopifnot`, or of `if` coupled with `stop`. Check this up front, as the first thing you do before you calculate anything else. As to what to check, there are several possibilities:\n\n- stop if any of the numbers are negative\n- continue if all of the numbers are positive\n- stop if the *smallest* number is negative (the smallest number is negative if and only if not all the numbers are positive)\n\nR has functions `any` and `all` that do what you'd expect:\n\n::: {.cell}\n\n```{.r .cell-code}\nw <- 1:5\nw\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1 2 3 4 5\n```\n:::\n\n```{.r .cell-code}\nany(w>3.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] TRUE\n```\n:::\n\n```{.r .cell-code}\nall(w<4.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] FALSE\n```\n:::\n:::\n\n\nAre there any numbers greater than 3.5 (yes, 4 and 5); are all the numbers less than 4.5 (no, 5 isn't).\n\nCite your sources for these if you use either of them, since this is the first place in the course that I'm mentioning either of them.\n\nRemember that if you use `stopifnot`, the condition that goes in there is what has to be true if the function is to run; if you use `if` and `stop`, the condition is what will *stop* the function running. With that in mind, I would code my three possibilities above this way. First off, here's the original:\n\n::: {.cell}\n\n```{.r .cell-code}\ncv <- function(x) {\nmean_x <- mean(x)\nsd_x <- sd(x)\nsd_x/mean_x\n}\n```\n:::\n\nthen, stop if any of the numbers are negative:\n\n::: {.cell}\n\n```{.r .cell-code}\ncv <- function(x) {\nif (any(x<0)) stop(\"A value is negative\")\nmean_x <- mean(x)\nsd_x <- sd(x)\nsd_x/mean_x\n}\ncv(v)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in cv(v): A value is negative\n```\n:::\n:::\n\ncontinue if all the numbers are positive\n\n::: {.cell}\n\n```{.r .cell-code}\ncv <- function(x) {\nstopifnot(all(x>0))\nmean_x <- mean(x)\nsd_x <- sd(x)\nsd_x/mean_x\n}\ncv(v)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in cv(v): all(x > 0) is not TRUE\n```\n:::\n:::\n\nstop if the smallest value is negative\n\n::: {.cell}\n\n```{.r .cell-code}\ncv <- function(x) {\nif (min(x)<0) stop(\"Smallest value is negative\")\nmean_x <- mean(x)\nsd_x <- sd(x)\nsd_x/mean_x\n}\ncv(v)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in cv(v): Smallest value is negative\n```\n:::\n:::\n\nThere are (at least) three other possibilities: you can negate the logical condition and interchange `if/stop` and `stopifnot`, thus (at the expense of some clarity of reading):\n\ncontinue if it is not true that any of the numbers are negative\n\n::: {.cell}\n\n```{.r .cell-code}\ncv <- function(x) {\nstopifnot(!any(x<0))\nmean_x <- mean(x)\nsd_x <- sd(x)\nsd_x/mean_x\n}\ncv(v)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in cv(v): !any(x < 0) is not TRUE\n```\n:::\n:::\n\n(you might be thinking of De Morgan's laws here)\n\nstop if it is not true that all the numbers are positive\n\n::: {.cell}\n\n```{.r .cell-code}\ncv <- function(x) {\nif (!all(x>0)) stop(\"Not all values are positive\")\nmean_x <- mean(x)\nsd_x <- sd(x)\nsd_x/mean_x\n}\ncv(v)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in cv(v): Not all values are positive\n```\n:::\n:::\n\ncontinue if the smallest value is not negative\n\n::: {.cell}\n\n```{.r .cell-code}\ncv <- function(x) {\nstopifnot(min(x)>=0)\nmean_x <- mean(x)\nsd_x <- sd(x)\nsd_x/mean_x\n}\ncv(v)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in cv(v): min(x) >= 0 is not TRUE\n```\n:::\n:::\nor another way to do the last one, a more direct negation of the condition, which at my guess needs some extra brackets:\n\n::: {.cell}\n\n```{.r .cell-code}\ncv <- function(x) {\nstopifnot(!(min(x)<0))\nmean_x <- mean(x)\nsd_x <- sd(x)\nsd_x/mean_x\n}\ncv(v)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in cv(v): !(min(x) < 0) is not TRUE\n```\n:::\n:::\n\nThis one is hard to parse: what does that last message mean? I would take a negative off each side and read it as \"min of x is negative is TRUE\", but that takes extra effort. \n\nI said that last one needed some extra brackets. This is, I thought, to get the order of operations right (operator precedence); it turns out not to matter because \"not\" has lower precedence than most other things, so that these do actually work (the \"not\" is evaluated *after* the less-than and the other things, so last of all here, even though it appears to be \"glued\" to the `min`): \n\n::: {.cell}\n\n```{.r .cell-code}\n!min(v)<0\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] FALSE\n```\n:::\n\n```{.r .cell-code}\n!min(1:5)<0\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] TRUE\n```\n:::\n:::\n\nSee [this](https://stat.ethz.ch/R-manual/R-devel/library/base/html/Syntax.html) for details. See especially the second set of examples, the ones beginning with \"Special operators\", and see especially-especially the comment at the bottom of these examples! That is to say, *you* should put in the extra brackets unless you also make the case that they are not needed, because anyone reading your code is guaranteed to be confused by it when they read it (including you in six months, because you *will not* remember the operator priority of \"not\").\n\nMy take is that one of the first three of the seven possibilities for coding `stopifnot` or `if` with `stop` is the best, since these more obviously encode the condition for continuing or stopping as appropriate. There are two things here: one is that you have to get the code right, but the second is that you have to get the code *clear*, so that it is obvious to anyone reading it that it does the right thing (once again, this includes you in six months). On that score, the first three alternatives are a direct expression of what you want to achieve, and the last four make it look as if you found a way of coding it that worked and stopped there, without thinking about whether there were any other, clearer or more expressive, possibilities.\n\n\n$\\blacksquare$\n\n\n\n\n\n\n## Rescaling\n\n Suppose we have this vector of values:\n\n::: {.cell}\n\n```{.r .cell-code}\nz <- c(10, 14, 11)\nz\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 10 14 11\n```\n:::\n:::\n\nWe want to scale these so that the smallest value is 0 and the largest is 1. We are going to be doing this a lot, so we are going to write a function that will work for any input.\n\n\n\n(a) Using a copy of my `z`, work out `min(z)` and `max(z)`. What do they do? Explain (very) briefly.\n\nSolution\n\n\nSimply this -- define `z` first:\n\n::: {.cell}\n\n```{.r .cell-code}\nz <- c(10, 14, 11)\nmin(z)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 10\n```\n:::\n\n```{.r .cell-code}\nmax(z)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 14\n```\n:::\n:::\n\nThey are respectively (and as you would guess) the smallest and largest of the values in `z`. (A nice gentle warmup, but I wanted to get you on the right track for what is coming up.)\n\n\n$\\blacksquare$\n\n\n\n(b) What do these lines of code do, using the same `z` that I had? Run them and see, and describe briefly what `s` contains.\n\n::: {.cell}\n\n```{.r .cell-code}\nlo <- min(z)\nhi <- max(z)\ns <- (z - lo) / (hi - lo)\ns\n```\n:::\n\nSolution\n\n\nHere we go:\n\n::: {.cell}\n\n```{.r .cell-code}\nlo <- min(z)\nhi <- max(z)\ns <- (z - lo) / (hi - lo)\ns\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.00 1.00 0.25\n```\n:::\n:::\n\nThe lowest value became 0, the highest 1, and the other one to something in between. Saying this shows the greatest insight.\n\nExtra: the reason for doing it in three steps rather than one (see below) is (i) it makes it clearer what is going on (and thus makes it less likely that you make a mistake), and (ii) it is more efficient, since my way only finds the minimum once instead of twice. Compare this approach with mine above:\n\n::: {.cell}\n\n```{.r .cell-code}\n(z - min(z)) / (max(z) - min(z))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.00 1.00 0.25\n```\n:::\n:::\n\nMore complicated with all the brackets, and two `min(z)`. Admittedly the difference here will be thousandths of a second, but why call a function twice when you don't have to?\n\n\n\n\n$\\blacksquare$\n\n\n\n\n\n(c) Write a function called `rescale` that implements the calculation above, for any input vector called `x`. (Note that I changed the name.)\n\nSolution\n\n\nWrite a function skeleton:\n\n::: {.cell}\n\n```{.r .cell-code}\nrescale <- function(x) {\n\n}\n```\n:::\n\nand inside the curly brackets put the code from above, replacing `z` with `x` everywhere:\n\n::: {.cell}\n\n```{.r .cell-code}\nrescale <- function(x) {\nlo <- min(x)\nhi <- max(x)\n(x - lo) / (hi - lo)\n}\n```\n:::\n\nYou'll need to make sure your function returns something to the outside world. Either don't save the last line in `s` (as I did here), or save it in `s` and then return `s`:\n\n::: {.cell}\n\n```{.r .cell-code}\nrescale <- function(x) {\nlo <- min(x)\nhi <- max(x)\ns <- (x - lo) / (hi - lo)\ns\n}\n```\n:::\n\nor use `return()` if you must, but be aware that this is bad style in R (unlike Python, where you need it). The approved way of using `return` in R is when you are returning something *earlier* than the last line of a function, for example, you are testing a simple case first and returning the value that goes with that, before getting down to the serious computation. \n\nExtra: in the spirit of what's coming up below, you might check first whether the maximum and minimum are the same and return something else if that's the case:\n\n::: {.cell}\n\n```{.r .cell-code}\nrescale0 <- function(x) {\nlo <- min(x)\nhi <- max(x)\nif (lo == hi) return(0)\ns <- (x - lo) / (hi - lo)\ns\n}\n```\n:::\n\nThis is good style; in this case, if `lo` and `hi` are the same, we want to return something else (zero) to the outside world, and *then* we do the calculation, knowing that `lo` and `hi` are different, so that we are sure we are not dividing by zero (but I get ahead of myself).\n\nDoing it this way, there is something to be careful of: a function ought to return a predictable *type* of thing: numbers, in this case. If you have your function return *text* on error, like this:\n\n::: {.cell}\n\n```{.r .cell-code}\nrescale0 <- function(x) {\nlo <- min(x)\nhi <- max(x)\nif (lo == hi) return(\"High and low need to be different\")\ns <- (x - lo) / (hi - lo)\ns\n}\n```\n:::\n\nthen you can get into trouble:\n\n::: {.cell}\n\n```{.r .cell-code}\nrescale0(z)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.00 1.00 0.25\n```\n:::\n\n```{.r .cell-code}\nrescale0(c(3,3,3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"High and low need to be different\"\n```\n:::\n:::\nThe first one is numbers and the second one is text.\n\n\n\n$\\blacksquare$\n\n\n(d) Test your function on my `z`, and on another vector of your choosing. Explain briefly why the answer you get from your vector makes sense.\n\nSolution\n\n\nOn my `z`:\n\n::: {.cell}\n\n```{.r .cell-code}\nrescale(z)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.00 1.00 0.25\n```\n:::\n:::\n\nThe same values as I got before, so that works.\n\nFor your vector, use whatever you like. I think it makes sense to have the values already in order, to make it easier to check. Here's one possibility:\n\n::: {.cell}\n\n```{.r .cell-code}\nw <- 2:6\nw\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2 3 4 5 6\n```\n:::\n:::\n\nand then\n\n::: {.cell}\n\n```{.r .cell-code}\nrescale(w)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.00 0.25 0.50 0.75 1.00\n```\n:::\n:::\n\nThe smallest value is 2, which goes to zero; the largest is 6, which goes to 1, and the others are equally spaced between in both the input and the output.\n\nAnother possibility is to use a vector with values whose largest and smallest you can clearly see:\n\n::: {.cell}\n\n```{.r .cell-code}\nw <- c(10, 11, 100, 0, 20)\nrescale(w)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.10 0.11 1.00 0.00 0.20\n```\n:::\n:::\n\nClearly the smallest value is 0 and the largest is 100. These become 0 and 1, and these particular values make it easy to see what happened: each of the other values got divided by 100.\n\nSome discussion is needed here, in that you need to say something convincing about why your answer is right.\n\nExtra: This is why I had you use a name *other than* `z` for the input to your function. The function can be used on any input, not just the `z` that we tested it on. There's another R-specific reason, which is that you need to be careful about using the named inputs *only*. Consider this function:\n\n::: {.cell}\n\n```{.r .cell-code}\nff <- function(x) {\nx + z\n}\n\nff(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 20 24 21\n```\n:::\n:::\n\nWhere did `z` come from? R *used the `z` we had before*, which is rather dangerous: what if we had a `z` lying around from some completely different work? Much better to have a function work with only inputs in the top line:\n\n::: {.cell}\n\n```{.r .cell-code}\nff <- function(x, z) {\nx + z\n}\nff(10, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 13\n```\n:::\n\n```{.r .cell-code}\nff(10)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in ff(10): argument \"z\" is missing, with no default\n```\n:::\n:::\n\nThe first time, the two inputs are added together, but the second time it tells you it was expecting a value to use for `z` and didn't see one. Much safer.\n\n\n$\\blacksquare$\n\n\n(e) What happens if your input to `rescale` is a vector of numbers all the same? Give an example. Rewrite your function to intercept this case and give a helpful error message.\n\nSolution\n\n\nFirst, try it and see. Any collection of values all the same will do:\n\n::: {.cell}\n\n```{.r .cell-code}\nrescale(c(3,3,3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] NaN NaN NaN\n```\n:::\n:::\n\n`NaN` stands for \"not a number\". The way we got it is that the minimum and maximum were the same, so our function ended up dividing by zero (in fact, working out zero divided by zero). This is, in R terms, not even an error, but the answer is certainly not helpful.\n\nThe easiest way to check inputs is to use `stopifnot` to express what should be *true* if the function is to proceed. Here, we want the maximum and minimum to be different, so:\n\n::: {.cell}\n\n```{.r .cell-code}\nrescale <- function(x) {\nlo <- min(x)\nhi <- max(x)\nstopifnot(hi != lo)\n(x - lo) / (hi - lo)\n}\nrescale(c(3,3,3))\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in rescale(c(3, 3, 3)): hi != lo is not TRUE\n```\n:::\n:::\n\nThis is much clearer: I only have to recall what my `hi` and `lo` are to see what the problem is.\n\nExtra 1: by calculating and saving the min and max up front, I still only need to calculate them once. If you do it this way:\n\n::: {.cell}\n\n```{.r .cell-code}\nrescale <- function(x) {\nstopifnot(max(x) != min(x))\n(x - min(x)) / (max(x) - min(x))\n}\nrescale(c(3,3,3))\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in rescale(c(3, 3, 3)): max(x) != min(x) is not TRUE\n```\n:::\n:::\n\nyou get a slightly more informative error message, but you have calculated the max *twice* and the min *three times* for no reason.\n\nExtra 2: `stopifnot` is shorthand for this:\n\n::: {.cell}\n\n```{.r .cell-code}\nrescale <- function(x) {\nlo <- min(x)\nhi <- max(x)\nif (hi == lo) stop(\"min and max are the same!\")\n(x - lo) / (hi - lo)\n}\nrescale(c(3,3,3))\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in rescale(c(3, 3, 3)): min and max are the same!\n```\n:::\n:::\n\nI didn't show you this, so if you use `stop`, you must tell me where you found out about it. This is better than returning some text (see `rescale0` above) or printing a message: it's an error, so you want to make it look like an error. I am very sympathetic to being persuaded that this is *better* than `stopifnot`, because you can customize the message (and, also, you don't have to go through the double-negative contortions of `stopifnot`). Another way to use `stopifnot` and get a customized message is this one (that I only learned about right when you were writing this Assignment):\n\n::: {.cell}\n\n```{.r .cell-code}\nrescale <- function(x) {\nlo <- min(x)\nhi <- max(x)\nstopifnot(\"high and low must be different\" = (hi != lo))\n(x - lo) / (hi - lo)\n}\nrescale(c(3,3,3))\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in rescale(c(3, 3, 3)): high and low must be different\n```\n:::\n:::\nThis is called a \"named argument\", and the name, if given, is used as an error message.\n\n\nExtra 3: returning to my `rescale0` from above:\n\n::: {.cell}\n\n```{.r .cell-code}\nrescale0\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nfunction(x) {\nlo <- min(x)\nhi <- max(x)\nif (lo == hi) return(\"High and low need to be different\")\ns <- (x - lo) / (hi - lo)\ns\n}\n<bytecode: 0x55de8013c470>\n```\n:::\n:::\n\nthis can get you into trouble if you use it in a dataframe. This is a bit complicated, since it has to use list-columns. Here we go:\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(x = list(z, c(3,3,3)))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"x\"],\"name\":[1],\"type\":[\"list\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"<dbl [3]>\"},{\"1\":\"<dbl [3]>\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\nJust to check that this does contain what you think it does:\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(x = list(z, c(3,3,3))) %>% unnest(x)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"x\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"10\"},{\"1\":\"14\"},{\"1\":\"11\"},{\"1\":\"3\"},{\"1\":\"3\"},{\"1\":\"3\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\nSo now, for each of those two input vectors, what happens when we run `rescale0` on them? This is `rowwise`:\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(x = list(z, c(3,3,3))) %>% \n  rowwise() %>% \n  mutate(ans = list(rescale0(x)))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"x\"],\"name\":[1],\"type\":[\"list\"],\"align\":[\"right\"]},{\"label\":[\"ans\"],\"name\":[2],\"type\":[\"list\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"<dbl [3]>\",\"2\":\"<dbl [3]>\"},{\"1\":\"<dbl [3]>\",\"2\":\"<chr [1]>\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\nThe first `ans` is a vector of 3 numbers, and the second one is one piece of text (the \"error message\"). I was actually surprised it got this far. So what happens when we `unnest` the second column?\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(x = list(z, c(3,3,3))) %>% \n  rowwise() %>% \n  mutate(ans = list(rescale0(x))) %>% \n  unnest(ans)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in `list_unchop()`:\n! Can't combine `x[[1]]` <double> and `x[[2]]` <character>.\n```\n:::\n:::\n\nNow we get a confusing error: it's *here* that combining some numbers and some text in one column of a dataframe doesn't work. To forestall this, we need to go back and rewrite `rescale0` to not mix things up. Having it return an error, as the latest version of `rescale` does, gives an error here too, but at least we know what it means:\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(x = list(z, c(3,3,3))) %>% \n  rowwise() %>% \n  mutate(ans = list(rescale(x))) %>% \n  unnest(ans)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in `mutate()`:\nℹ In argument: `ans = list(rescale(x))`.\nℹ In row 2.\nCaused by error in `rescale()`:\n! high and low must be different\n```\n:::\n:::\n\nbecause this is the error we anticipated: it says \"somewhere within the list-column `x`, specifically in its second row, is a vector where everything is the same\".\n\n\n$\\blacksquare$\n\n\n(f) Make a dataframe (containing any numeric values), and in it create a new column containing the rescaled version of one of its columns, using your function. Show your result.\n\nSolution\n\n\nThis is less difficult than you might be expecting: make a dataframe with at least one numeric column, and use `mutate`:\n\n::: {.cell}\n\n```{.r .cell-code}\nd <- tibble(y=2:6)\nd\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"y\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"2\"},{\"1\":\"3\"},{\"1\":\"4\"},{\"1\":\"5\"},{\"1\":\"6\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\nand then\n\n::: {.cell}\n\n```{.r .cell-code}\nd %>% mutate(s=rescale(y))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"y\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"s\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"2\",\"2\":\"0.00\"},{\"1\":\"3\",\"2\":\"0.25\"},{\"1\":\"4\",\"2\":\"0.50\"},{\"1\":\"5\",\"2\":\"0.75\"},{\"1\":\"6\",\"2\":\"1.00\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\nYou can supply the values for what I called `y`, or use random numbers. It's easier for you to check that it has worked if your column playing the role of my `y` has not too many values in it.\n\nExtra: this is actually already in the `tidyverse` under the name `percent_rank` (\"percentile ranks\"):\n\n::: {.cell}\n\n```{.r .cell-code}\nd %>% mutate(s = percent_rank(y))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"y\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"s\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"2\",\"2\":\"0.00\"},{\"1\":\"3\",\"2\":\"0.25\"},{\"1\":\"4\",\"2\":\"0.50\"},{\"1\":\"5\",\"2\":\"0.75\"},{\"1\":\"6\",\"2\":\"1.00\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\nThe value 5, for example, is at the 75th percentile.\n\n\n$\\blacksquare$\n\n\n(g) We might want to rescale the input not to be between 0 and 1, but between two values `a` and `b` that we specify as input. If `a` and/or `b` are not given, we want to use the values 0 for `a` and 1 for `b`. Rewrite your function to rescale the input to be between `a` and `b` instead of 0 and 1. Hint: allow your function to produce values between 0 and 1 as before, and then note that if all the values in a vector `s` are between 0 and 1, then all the values in `a+(b-a)*s`\nare between $a$ and $b$.\n\nSolution\n\n\nI'm showing you my thought process in this one. The answer I want from you is the one at the end.\n\nSo, start by copying and pasting what you had before:\n\n::: {.cell}\n\n```{.r .cell-code}\nrescale <- function(x) {\nlo <- min(x)\nhi <- max(x)\nstopifnot(hi != lo)\n(x - lo) / (hi - lo)\n}\n```\n:::\n\nOn the top line, add the extra inputs and their default values. I also changed the name of my function, for reasons you'll see later:\n\n::: {.cell}\n\n```{.r .cell-code}\nrescale2 <- function(x, a=0, b=1) {\nlo <- min(x)\nhi <- max(x)\nstopifnot(hi != lo)\n(x - lo) / (hi - lo)\n}\n```\n:::\n\nSave the last line, since we have to do something else with it:\n\n::: {.cell}\n\n```{.r .cell-code}\nrescale2 <- function(x, a=0, b=1) {\nlo <- min(x)\nhi <- max(x)\nstopifnot(hi != lo)\ns <- (x - lo) / (hi - lo)\n}\n```\n:::\n\nand finally add the calculation in the hint, which we don't need to save because we are returning it:\n\n::: {.cell}\n\n```{.r .cell-code}\nrescale2 <- function(x, a=0, b=1) {\nlo <- min(x)\nhi <- max(x)\nstopifnot(hi != lo)\ns <- (x - lo) / (hi - lo)\na + (b-a) * s\n}\n```\n:::\n\nThis complete function is what I want to see from you. (You should keep the `stopifnot`, because this function will have the exact same problem as the previous one if all the values in `x` are the same.)\n\nA better way is to observe that you can call functions inside functions. The function above is now a bit messy since it has several steps. Something that corresponds better to my hint is to call the original `rescale` first, and then modify its result:\n\n::: {.cell}\n\n```{.r .cell-code}\nrescale3 <- function(x, a=0, b=1) {\ns <- rescale(x)\na + (b-a) * s\n}\n```\n:::\n\nThe logic to this is rather clearly \"rescale the input to be between 0 and 1, then rescale *that* to be between $a$ and $b$.\" My `rescale2` does exactly the same thing, but it's much less clear that it does so, unless you happen to have in your head how `rescale` works. (I think you are more likely to remember, sometime in the future, what `rescale` *does*, compared to precisely how it *works*.)\n\nThat is why `rescale3` is better than `rescale2`. Remember that you can, and generally should, use functions that have already been written (by you or someone else) as part of functions that do more complex things. See also my second point below.\n\nExtra: there are two important principles about why functions are important:\n\n1.  they allow you to re-do a calculation on many different inputs (the point I've been making up to now)\n1.  by abstracting a calculation into a thing with a name, it makes it easier to understand that calculation's role in something bigger. The only thing we had to remember in `rescale3` is what the last line did, because the name of the function called on the first line tells us what happens there. This is much easier than remembering what the first four lines of `rescale2` do.\n\nThe second principle here is what psychologists call \"chunking\": you view a thing like my function `rescale` as a single item, rather than as four separate lines of code, and then that single item can be part of something larger (like my `rescale3`), and you have a smaller number of things to keep track of.\n\n\n$\\blacksquare$\n\n\n(h) Test your new function two or more times, on input where you know or can guess what the output is going to be. In each case, explain briefly why your output makes sense.\n\nSolution\n\n\nI'll start by using the default values for `a` and `b` (so I don't have to specify them):\n\n::: {.cell}\n\n```{.r .cell-code}\nrescale2(2:6)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.00 0.25 0.50 0.75 1.00\n```\n:::\n\n```{.r .cell-code}\nrescale3(2:6)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.00 0.25 0.50 0.75 1.00\n```\n:::\n:::\n\nI did both of the variants of my function; of course, you'll only have one variant.\n\nWe got the same answer as before for the same input, so the default values $a=0, b=1$ look as if they have been used.\n\nLet's try a different one:\n\n::: {.cell}\n\n```{.r .cell-code}\nv <- c(7, 11, 12)\nrescale2(v, 10, 30)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 10 26 30\n```\n:::\n\n```{.r .cell-code}\nrescale3(v, 10, 30)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 10 26 30\n```\n:::\n:::\n\nThe lowest value in `v` has become 10, and the highest has become 30. (Also, the in-between value 11 was closer to 12 than to 7, and it has become something closer to 30 than to 10.)\n\nExtra: you can also name any of your inputs:\n\n::: {.cell}\n\n```{.r .cell-code}\nrescale3(x=v, a=10, b=30)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 10 26 30\n```\n:::\n:::\n\nand if you name them, you can shuffle the order too:\n\n::: {.cell}\n\n```{.r .cell-code}\nrescale3(a=10, b=30, x=v)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 10 26 30\n```\n:::\n:::\n\nThe point of doing more than one test is to check that different aspects of your function all work. Therefore, the best testing here checks that the defaults work, and that the answer is sensible for some different `a` and `b` (to check that this works as well).\n\nWhen you write your version of `rescale` with the optional inputs, it's best if you do it so that the things you have to supply (the vector of numbers) is *first*. If you put `a` and `b` first, when you want to omit them, you'll have to call the input vector by name, like this:\n\n::: {.cell}\n\n```{.r .cell-code}\nrescale3(x=v)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.0 0.8 1.0\n```\n:::\n:::\n\nbecause otherwise the input vector will be taken to be `a`, not what you want.\n\n$\\blacksquare$\n\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}